'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,k,l){c instanceof String&&(c=String(c));for(var q=c.length,p=0;p<q;p++){var u=c[p];if(k.call(l,u,p,c))return{i:p,v:u}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,k,l){c!=Array.prototype&&c!=Object.prototype&&(c[k]=l.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,k,l,q){if(k){l=$jscomp.global;c=c.split(".");for(q=0;q<c.length-1;q++){var p=c[q];p in l||(l[p]={});l=l[p]}c=c[c.length-1];q=l[c];k=k(q);k!=q&&null!=k&&$jscomp.defineProperty(l,c,{configurable:!0,writable:!0,value:k})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,l){return $jscomp.findInternal(this,c,l).v}},"es6-impl","es3");
(function(c){"object"==typeof exports&&"object"==typeof module?c(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],c):c(CodeMirror)})(function(c){function k(b){if(!b.global){var a=b.flags;b=new RegExp(b.source,(null!=a?a:(b.ignoreCase?"i":"")+(b.global?"g":"")+(b.multiline?"m":""))+"g")}return b}function l(b,a,d){a=k(a);var e=d.line,f=d.ch;for(d=b.lastLine();e<=d;e++,f=0)if(a.lastIndex=f,f=b.getLine(e),f=a.exec(f))return{from:h(e,f.index),to:h(e,
f.index+f[0].length),match:f}}function q(b,a,d){if(!/\\s|\\n|\n|\\W|\\D|\[\^/.test(a.source))return l(b,a,d);a=k(a);for(var e,f=1,c=d.line,r=b.lastLine();c<=r;){for(var g=0;g<f;g++){var n=b.getLine(c++);e=null==e?n:e+"\n"+n}f*=2;a.lastIndex=d.ch;if(g=a.exec(e))return a=e.slice(0,g.index).split("\n"),b=g[0].split("\n"),d=d.line+a.length-1,a=a[a.length-1].length,{from:h(d,a),to:h(d+b.length-1,1==b.length?a+b[0].length:b[b.length-1].length),match:g}}}function p(b,a){for(var d=0,e;;){a.lastIndex=d;d=
a.exec(b);if(!d)return e;e=d;d=e.index+(e[0].length||1);if(d==b.length)return e}}function u(b,a,d){a=k(a);var e=d.line,f=d.ch;for(d=b.firstLine();e>=d;e--,f=-1){var c=b.getLine(e);-1<f&&(c=c.slice(0,f));if(f=p(c,a))return{from:h(e,f.index),to:h(e,f.index+f[0].length),match:f}}}function y(b,a,d){a=k(a);for(var e,f=1,c=d.line,r=b.firstLine();c>=r;){for(var g=0;g<f;g++){var n=b.getLine(c--);e=null==e?n.slice(0,d.ch):n+"\n"+e}f*=2;if(g=p(e,a))return a=e.slice(0,g.index).split("\n"),b=g[0].split("\n"),
c+=a.length,a=a[a.length-1].length,{from:h(c,a),to:h(c+b.length-1,1==b.length?a+b[0].length:b[b.length-1].length),match:g}}}function t(b,a,d){if(b.length==a.length)return d;for(a=Math.min(d,b.length);;){var c=b.slice(0,a).toLowerCase().length;if(c<d)++a;else if(c>d)--a;else return a}}function z(b,a,d,c){if(!a.length)return null;c=c?v:w;a=c(a).split(/\r|\n\r?/);var f=d.line;d=d.ch;var e=b.lastLine()+1-a.length;a:for(;f<=e;f++,d=0){var r=b.getLine(f).slice(d),g=c(r);if(1==a.length){var n=g.indexOf(a[0]);
if(-1==n)continue a;t(r,g,n);return{from:h(f,t(r,g,n)+d),to:h(f,t(r,g,n+a[0].length)+d)}}n=g.length-a[0].length;if(g.slice(n)!=a[0])continue a;for(var m=1;m<a.length-1;m++)if(c(b.getLine(f+m))!=a[m])continue a;var m=b.getLine(f+a.length-1),k=c(m),l=a[a.length-1];if(m.slice(0,l.length)!=l)continue a;return{from:h(f,t(r,g,n)+d),to:h(f+a.length-1,t(m,k,l.length))}}}function A(b,a,d,c){if(!a.length)return null;c=c?v:w;a=c(a).split(/\r|\n\r?/);var f=d.line,e=d.ch,l=b.firstLine()-1+a.length;a:for(;f>=l;f--,
e=-1){var g=b.getLine(f);-1<e&&(g=g.slice(0,e));e=c(g);if(1==a.length){d=e.lastIndexOf(a[0]);if(-1==d)continue a;return{from:h(f,t(g,e,d)),to:h(f,t(g,e,d+a[0].length))}}var k=a[a.length-1];if(e.slice(0,k.length)!=k)continue a;var m=1;for(d=f-a.length+1;m<a.length-1;m++)if(c(b.getLine(d+m))!=a[m])continue a;d=b.getLine(f+1-a.length);m=c(d);if(m.slice(m.length-a[0].length)!=a[0])continue a;return{from:h(f+1-a.length,t(d,m,d.length-a[0].length)),to:h(f,t(g,e,k.length))}}}function x(b,a,c,e){this.atOccurrence=
!1;this.doc=b;c=c?b.clipPos(c):h(0,0);this.pos={from:c,to:c};if("object"==typeof e)var d=e.caseFold;else d=e,e=null;"string"==typeof a?(null==d&&(d=!1),this.matches=function(c,e){return(c?A:z)(b,a,e,d)}):(a=k(a),this.matches=e&&!1===e.multiline?function(c,d){return(c?u:l)(b,a,d)}:function(c,d){return(c?y:q)(b,a,d)})}var h=c.Pos;if(String.prototype.normalize){var v=function(b){return b.normalize("NFD").toLowerCase()};var w=function(b){return b.normalize("NFD")}}else v=function(b){return b.toLowerCase()},
w=function(b){return b};x.prototype={findNext:function(){return this.find(!1)},findPrevious:function(){return this.find(!0)},find:function(b){for(var a=this.matches(b,this.doc.clipPos(b?this.pos.from:this.pos.to));a&&0==c.cmpPos(a.from,a.to);)b?a.from.ch?a.from=h(a.from.line,a.from.ch-1):a=a.from.line==this.doc.firstLine()?null:this.matches(b,this.doc.clipPos(h(a.from.line-1))):a.to.ch<this.doc.getLine(a.to.line).length?a.to=h(a.to.line,a.to.ch+1):a=a.to.line==this.doc.lastLine()?null:this.matches(b,
h(a.to.line+1,0));if(a)return this.pos=a,this.atOccurrence=!0,this.pos.match||!0;b=h(b?this.doc.firstLine():this.doc.lastLine()+1,0);this.pos={from:b,to:b};return this.atOccurrence=!1},from:function(){if(this.atOccurrence)return this.pos.from},to:function(){if(this.atOccurrence)return this.pos.to},replace:function(b,a){this.atOccurrence&&(b=c.splitLines(b),this.doc.replaceRange(b,this.pos.from,this.pos.to,a),this.pos.to=h(this.pos.from.line+b.length-1,b[b.length-1].length+(1==b.length?this.pos.from.ch:
0)))}};c.defineExtension("getSearchCursor",function(b,a,c){return new x(this.doc,b,a,c)});c.defineDocExtension("getSearchCursor",function(b,a,c){return new x(this,b,a,c)});c.defineExtension("selectMatches",function(b,a){var d=[];for(b=this.getSearchCursor(b,this.getCursor("from"),a);b.findNext()&&!(0<c.cmpPos(b.to(),this.getCursor("to")));)d.push({anchor:b.from(),head:b.to()});d.length&&this.setSelections(d,0)})});
