'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,k,f){b instanceof String&&(b=String(b));for(var g=b.length,l=0;l<g;l++){var n=b[l];if(k.call(f,n,l,b))return{i:l,v:n}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,k,f){if(b==Array.prototype||b==Object.prototype)return b;b[k]=f.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<b.length;++k){var f=b[k];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,k){var f=$jscomp.propertyToPolyfillSymbol[k];if(null==f)return b[k];f=b[f];return void 0!==f?f:b[k]};
$jscomp.polyfill=function(b,k,f,g){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,k,f,g):$jscomp.polyfillUnisolated(b,k,f,g))};$jscomp.polyfillUnisolated=function(b,k,f,g){f=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var l=b[g];if(!(l in f))return;f=f[l]}b=b[b.length-1];g=f[b];k=k(g);k!=g&&null!=k&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(b,k,f,g){var l=b.split(".");b=1===l.length;g=l[0];g=!b&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var n=0;n<l.length-1;n++){var r=l[n];if(!(r in g))return;g=g[r]}l=l[l.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?g[l]:null;k=k(f);null!=k&&(b?$jscomp.defineProperty($jscomp.polyfills,l,{configurable:!0,writable:!0,value:k}):k!==f&&($jscomp.propertyToPolyfillSymbol[l]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(l):$jscomp.POLYFILL_PREFIX+l,l=
$jscomp.propertyToPolyfillSymbol[l],$jscomp.defineProperty(g,l,{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6","es3");
(function(b){"object"==typeof exports&&"object"==typeof module?b(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],b):b(CodeMirror)})(function(b){function k(c,a){var d=c.flags;for(var h=d=null!=d?d:(c.ignoreCase?"i":"")+(c.global?"g":"")+(c.multiline?"m":""),e=0;e<a.length;e++)-1==h.indexOf(a.charAt(e))&&(h+=a.charAt(e));return d==h?c:new RegExp(c.source,h)}function f(c,a,d){a=k(a,"g");var h=d.line,e=d.ch;for(d=c.lastLine();h<=d;h++,e=0)if(a.lastIndex=
e,e=c.getLine(h),e=a.exec(e))return{from:m(h,e.index),to:m(h,e.index+e[0].length),match:e}}function g(c,a,d){if(!/\\s|\\n|\n|\\W|\\D|\[\^/.test(a.source))return f(c,a,d);a=k(a,"gm");for(var h,e=1,b=d.line,l=c.lastLine();b<=l;){for(var p=0;p<e&&!(b>l);p++){var g=c.getLine(b++);h=null==h?g:h+"\n"+g}e*=2;a.lastIndex=d.ch;if(p=a.exec(h))return a=h.slice(0,p.index).split("\n"),c=p[0].split("\n"),d=d.line+a.length-1,a=a[a.length-1].length,{from:m(d,a),to:m(d+c.length-1,1==c.length?a+c[0].length:c[c.length-
1].length),match:p}}}function l(c,a,d){for(var h,e=0;e<=c.length;){a.lastIndex=e;e=a.exec(c);if(!e)break;var b=e.index+e[0].length;if(b>c.length-d)break;if(!h||b>h.index+h[0].length)h=e;e=e.index+1}return h}function n(c,a,d){a=k(a,"g");var b=d.line,e=d.ch;for(d=c.firstLine();b>=d;b--,e=-1){var f=c.getLine(b);if(e=l(f,a,0>e?0:f.length-e))return{from:m(b,e.index),to:m(b,e.index+e[0].length),match:e}}}function r(c,a,d){if(!/\\s|\\n|\n|\\W|\\D|\[\^/.test(a.source))return n(c,a,d);a=k(a,"gm");var b=1,
e=c.getLine(d.line).length-d.ch;d=d.line;for(var f=c.firstLine();d>=f;){for(var g=0;g<b&&d>=f;g++){var p=c.getLine(d--);var t=null==t?p:p+"\n"+t}b*=2;if(g=l(t,a,e))return a=t.slice(0,g.index).split("\n"),c=g[0].split("\n"),d+=a.length,a=a[a.length-1].length,{from:m(d,a),to:m(d+c.length-1,1==c.length?a+c[0].length:c[c.length-1].length),match:g}}}function q(c,a,d,b){if(c.length==a.length)return d;var e=0;for(a=d+Math.max(0,c.length-a.length);;){if(e==a)return e;var h=e+a>>1,f=b(c.slice(0,h)).length;
if(f==d)return h;f>d?a=h:e=h+1}}function x(c,a,d,b){if(!a.length)return null;b=b?u:v;a=b(a).split(/\r|\n\r?/);var e=d.line;d=d.ch;var h=c.lastLine()+1-a.length;a:for(;e<=h;e++,d=0){var f=c.getLine(e).slice(d),k=b(f);if(1==a.length){var g=k.indexOf(a[0]);if(-1==g)continue a;q(f,k,g,b);return{from:m(e,q(f,k,g,b)+d),to:m(e,q(f,k,g+a[0].length,b)+d)}}g=k.length-a[0].length;if(k.slice(g)!=a[0])continue a;for(var l=1;l<a.length-1;l++)if(b(c.getLine(e+l))!=a[l])continue a;l=c.getLine(e+a.length-1);var n=
b(l),r=a[a.length-1];if(n.slice(0,r.length)!=r)continue a;return{from:m(e,q(f,k,g,b)+d),to:m(e+a.length-1,q(l,n,r.length,b))}}}function y(c,a,b,f){if(!a.length)return null;f=f?u:v;a=f(a).split(/\r|\n\r?/);var e=b.line,d=b.ch,k=c.firstLine()-1+a.length;a:for(;e>=k;e--,d=-1){var g=c.getLine(e);-1<d&&(g=g.slice(0,d));d=f(g);if(1==a.length){b=d.lastIndexOf(a[0]);if(-1==b)continue a;return{from:m(e,q(g,d,b,f)),to:m(e,q(g,d,b+a[0].length,f))}}var l=a[a.length-1];if(d.slice(0,l.length)!=l)continue a;var h=
1;for(b=e-a.length+1;h<a.length-1;h++)if(f(c.getLine(b+h))!=a[h])continue a;b=c.getLine(e+1-a.length);h=f(b);if(h.slice(h.length-a[0].length)!=a[0])continue a;return{from:m(e+1-a.length,q(b,h,b.length-a[0].length,f)),to:m(e,q(g,d,l.length,f))}}}function w(b,a,d,h){this.atOccurrence=!1;this.doc=b;d=d?b.clipPos(d):m(0,0);this.pos={from:d,to:d};if("object"==typeof h)var c=h.caseFold;else c=h,h=null;"string"==typeof a?(null==c&&(c=!1),this.matches=function(d,e){return(d?y:x)(b,a,e,c)}):(a=k(a,"gm"),this.matches=
h&&!1===h.multiline?function(c,d){return(c?n:f)(b,a,d)}:function(c,d){return(c?r:g)(b,a,d)})}var m=b.Pos;if(String.prototype.normalize){var u=function(b){return b.normalize("NFD").toLowerCase()};var v=function(b){return b.normalize("NFD")}}else u=function(b){return b.toLowerCase()},v=function(b){return b};w.prototype={findNext:function(){return this.find(!1)},findPrevious:function(){return this.find(!0)},find:function(c){for(var a=this.matches(c,this.doc.clipPos(c?this.pos.from:this.pos.to));a&&0==
b.cmpPos(a.from,a.to);)c?a.from.ch?a.from=m(a.from.line,a.from.ch-1):a=a.from.line==this.doc.firstLine()?null:this.matches(c,this.doc.clipPos(m(a.from.line-1))):a.to.ch<this.doc.getLine(a.to.line).length?a.to=m(a.to.line,a.to.ch+1):a=a.to.line==this.doc.lastLine()?null:this.matches(c,m(a.to.line+1,0));if(a)return this.pos=a,this.atOccurrence=!0,this.pos.match||!0;c=m(c?this.doc.firstLine():this.doc.lastLine()+1,0);this.pos={from:c,to:c};return this.atOccurrence=!1},from:function(){if(this.atOccurrence)return this.pos.from},
to:function(){if(this.atOccurrence)return this.pos.to},replace:function(c,a){this.atOccurrence&&(c=b.splitLines(c),this.doc.replaceRange(c,this.pos.from,this.pos.to,a),this.pos.to=m(this.pos.from.line+c.length-1,c[c.length-1].length+(1==c.length?this.pos.from.ch:0)))}};b.defineExtension("getSearchCursor",function(b,a,d){return new w(this.doc,b,a,d)});b.defineDocExtension("getSearchCursor",function(b,a,d){return new w(this,b,a,d)});b.defineExtension("selectMatches",function(c,a){var d=[];for(c=this.getSearchCursor(c,
this.getCursor("from"),a);c.findNext()&&!(0<b.cmpPos(c.to(),this.getCursor("to")));)d.push({anchor:c.from(),head:c.to()});d.length&&this.setSelections(d,0)})});
