'use strict';(function(e){"object"==typeof exports&&"object"==typeof module?e(require("../../lib/codemirror"),require("./searchcursor"),require("../dialog/dialog")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","./searchcursor","../dialog/dialog"],e):e(CodeMirror)})(function(e){function y(a,b){"string"==typeof a?a=new RegExp(a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),b?"gi":"g"):a.global||(a=new RegExp(a.source,a.ignoreCase?"gi":"g"));return{token:function(b){a.lastIndex=
b.pos;var c=a.exec(b.string);if(c&&c.index==b.pos)return b.pos+=c[0].length||1,"searching";c?b.pos=c.index:b.skipToEnd()}}}function z(){this.overlay=this.posFrom=this.posTo=this.lastQuery=this.query=null}function k(a){return a.state.search||(a.state.search=new z)}function m(a){return"string"==typeof a&&a==a.toLowerCase()}function l(a,b,f){return a.getSearchCursor(b,f,m(b))}function A(a,b,f,c,d){a.openDialog(b,c,{value:f,selectValueOnOpen:!0,closeOnEnter:!1,onClose:function(){h(a)},onKeyDown:d})}function q(a,
b,f,c,d){a.openDialog?a.openDialog(b,d,{value:c,selectValueOnOpen:!0}):d(prompt(f,c))}function B(a,b,f,c){if(a.openConfirm)a.openConfirm(b,c);else if(confirm(f))c[0]()}function u(a){return a.replace(/\\(.)/g,function(a,f){return"n"==f?"\n":"r"==f?"\r":f})}function v(a){var b=a.match(/^\/(.*)\/([a-z]*)$/);if(b)try{a=new RegExp(b[1],-1==b[2].indexOf("i")?"":"i")}catch(f){}else a=u(a);if("string"==typeof a?""==a:a.test(""))a=/x^/;return a}function n(a,b,f){b.queryText=f;b.query=v(f);a.removeOverlay(b.overlay,
m(b.query));b.overlay=y(b.query,m(b.query));a.addOverlay(b.overlay);a.showMatchesOnScrollbar&&(b.annotate&&(b.annotate.clear(),b.annotate=null),b.annotate=a.showMatchesOnScrollbar(b.query,m(b.query)))}function g(a,b,f,c){var d=k(a);if(d.query)return p(a,b);var r=a.getSelection()||d.lastQuery;if(f&&a.openDialog){var t=null,g=function(b,c){e.e_stop(c);b&&(b!=d.queryText&&(n(a,d,b),d.posFrom=d.posTo=a.getCursor()),t&&(t.style.opacity=1),p(a,c.shiftKey,function(b,d){var c;3>d.line&&document.querySelector&&
(c=a.display.wrapper.querySelector(".CodeMirror-dialog"))&&c.getBoundingClientRect().bottom-4>a.cursorCoords(d,"window").top&&((t=c).style.opacity=.4)}))};A(a,'Search: <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',r,g,function(b,d){var c=e.keyMap[a.getOption("keyMap")][e.keyName(b)];if("findNext"==c||"findPrev"==c)e.e_stop(b),n(a,k(a),d),a.execCommand(c);else if("find"==
c||"findPersistent"==c)e.e_stop(b),g(d,b)});c&&(n(a,d,r),p(a,b))}else q(a,'Search: <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',"Search for:",r,function(c){c&&!d.query&&a.operation(function(){n(a,d,c);d.posFrom=d.posTo=a.getCursor();p(a,b)})})}function p(a,b,f){a.operation(function(){var c=k(a),d=l(a,c.query,b?c.posFrom:c.posTo);if(!d.find(b)&&(d=l(a,c.query,b?e.Pos(a.lastLine()):
e.Pos(a.firstLine(),0)),!d.find(b)))return;a.setSelection(d.from(),d.to());a.scrollIntoView({from:d.from(),to:d.to()},20);c.posFrom=d.from();c.posTo=d.to();f&&f(d.from(),d.to())})}function h(a){a.operation(function(){var b=k(a);if(b.lastQuery=b.query)b.query=b.queryText=null,a.removeOverlay(b.overlay),b.annotate&&(b.annotate.clear(),b.annotate=null)})}function w(a,b,f){a.operation(function(){for(var c=l(a,b);c.findNext();)if("string"!=typeof b){var d=a.getRange(c.from(),c.to()).match(b);c.replace(f.replace(/\$(\d)/g,
function(a,b){return d[b]}))}else c.replace(f)})}function x(a,b){if(!a.getOption("readOnly")){var f=a.getSelection()||k(a).lastQuery,c=b?"Replace all:":"Replace:";q(a,c+' <input type="text" style="width: 10em" class="CodeMirror-search-field"/> <span style="color: #888" class="CodeMirror-search-hint">(Use /re/ syntax for regexp search)</span>',c,f,function(c){c&&(c=v(c),q(a,'With: <input type="text" style="width: 10em" class="CodeMirror-search-field"/>',"Replace with:","",function(f){f=u(f);if(b)w(a,
c,f);else{h(a);var e=l(a,c,a.getCursor("from")),g=function(){var b=e.from(),h;if(!(h=e.findNext())&&(e=l(a,c),!(h=e.findNext())||b&&e.from().line==b.line&&e.from().ch==b.ch))return;a.setSelection(e.from(),e.to());a.scrollIntoView({from:e.from(),to:e.to()});B(a,"Replace? <button>Yes</button> <button>No</button> <button>All</button> <button>Stop</button>","Replace?",[function(){k(h)},g,function(){w(a,c,f)}])},k=function(a){e.replace("string"==typeof c?f:f.replace(/\$(\d)/g,function(b,c){return a[c]}));
g()};g()}}))})}}e.commands.find=function(a){h(a);g(a)};e.commands.findPersistent=function(a){h(a);g(a,!1,!0)};e.commands.findPersistentNext=function(a){g(a,!1,!0,!0)};e.commands.findPersistentPrev=function(a){g(a,!0,!0,!0)};e.commands.findNext=g;e.commands.findPrev=function(a){g(a,!0)};e.commands.clearSearch=h;e.commands.replace=x;e.commands.replaceAll=function(a){x(a,!0)}});
