'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,f,m){b instanceof String&&(b=String(b));for(var q=b.length,k=0;k<q;k++){var t=b[k];if(f.call(m,t,k,b))return{i:k,v:t}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,m){b!=Array.prototype&&b!=Object.prototype&&(b[f]=m.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,f,m,q){if(f){m=$jscomp.global;b=b.split(".");for(q=0;q<b.length-1;q++){var k=b[q];k in m||(m[k]={});m=m[k]}b=b[b.length-1];q=m[b];f=f(q);f!=q&&null!=f&&$jscomp.defineProperty(m,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,m){return $jscomp.findInternal(this,b,m).v}},"es6","es3");
(function(b){"object"==typeof exports&&"object"==typeof module?b(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],b):b(CodeMirror)})(function(b){function f(c){if(!c.global){var a=c.flags;c=new RegExp(c.source,(null!=a?a:(c.ignoreCase?"i":"")+(c.global?"g":"")+(c.multiline?"m":""))+"g")}return c}function m(c,a,d){a=f(a);var e=d.line,l=d.ch;for(d=c.lastLine();e<=d;e++,l=0)if(a.lastIndex=l,l=c.getLine(e),l=a.exec(l))return{from:g(e,l.index),to:g(e,
l.index+l[0].length),match:l}}function q(c,a,d){if(!/\\s|\\n|\n|\\W|\\D|\[\^/.test(a.source))return m(c,a,d);a=f(a);for(var e,l=1,b=d.line,n=c.lastLine();b<=n;){for(var h=0;h<l;h++){var p=c.getLine(b++);e=null==e?p:e+"\n"+p}l*=2;a.lastIndex=d.ch;if(h=a.exec(e))return a=e.slice(0,h.index).split("\n"),c=h[0].split("\n"),d=d.line+a.length-1,a=a[a.length-1].length,{from:g(d,a),to:g(d+c.length-1,1==c.length?a+c[0].length:c[c.length-1].length),match:h}}}function k(c,a){for(var d=0,e;;){a.lastIndex=d;d=
a.exec(c);if(!d)return e;e=d;d=e.index+(e[0].length||1);if(d==c.length)return e}}function t(c,a,d){a=f(a);var e=d.line,l=d.ch;for(d=c.firstLine();e>=d;e--,l=-1){var b=c.getLine(e);-1<l&&(b=b.slice(0,l));if(l=k(b,a))return{from:g(e,l.index),to:g(e,l.index+l[0].length),match:l}}}function y(c,a,d){a=f(a);for(var e,l=1,b=d.line,n=c.firstLine();b>=n;){for(var h=0;h<l;h++){var p=c.getLine(b--);e=null==e?p.slice(0,d.ch):p+"\n"+e}l*=2;if(h=k(e,a))return a=e.slice(0,h.index).split("\n"),c=h[0].split("\n"),
b+=a.length,a=a[a.length-1].length,{from:g(b,a),to:g(b+c.length-1,1==c.length?a+c[0].length:c[c.length-1].length),match:h}}}function r(c,a,d,e){if(c.length==a.length)return d;var b=0;for(a=d+Math.max(0,c.length-a.length);;){if(b==a)return b;var g=b+a>>1,n=e(c.slice(0,g)).length;if(n==d)return g;n>d?a=g:b=g+1}}function z(c,a,d,e){if(!a.length)return null;e=e?u:v;a=e(a).split(/\r|\n\r?/);var b=d.line;d=d.ch;var x=c.lastLine()+1-a.length;a:for(;b<=x;b++,d=0){var n=c.getLine(b).slice(d),h=e(n);if(1==
a.length){var p=h.indexOf(a[0]);if(-1==p)continue a;r(n,h,p,e);return{from:g(b,r(n,h,p,e)+d),to:g(b,r(n,h,p+a[0].length,e)+d)}}p=h.length-a[0].length;if(h.slice(p)!=a[0])continue a;for(var f=1;f<a.length-1;f++)if(e(c.getLine(b+f))!=a[f])continue a;f=c.getLine(b+a.length-1);var m=e(f),k=a[a.length-1];if(m.slice(0,k.length)!=k)continue a;return{from:g(b,r(n,h,p,e)+d),to:g(b+a.length-1,r(f,m,k.length,e))}}}function A(c,a,b,e){if(!a.length)return null;e=e?u:v;a=e(a).split(/\r|\n\r?/);var d=b.line,f=b.ch,
n=c.firstLine()-1+a.length;a:for(;d>=n;d--,f=-1){var h=c.getLine(d);-1<f&&(h=h.slice(0,f));f=e(h);if(1==a.length){b=f.lastIndexOf(a[0]);if(-1==b)continue a;return{from:g(d,r(h,f,b,e)),to:g(d,r(h,f,b+a[0].length,e))}}var m=a[a.length-1];if(f.slice(0,m.length)!=m)continue a;var k=1;for(b=d-a.length+1;k<a.length-1;k++)if(e(c.getLine(b+k))!=a[k])continue a;b=c.getLine(d+1-a.length);k=e(b);if(k.slice(k.length-a[0].length)!=a[0])continue a;return{from:g(d+1-a.length,r(b,k,b.length-a[0].length,e)),to:g(d,
r(h,f,m.length,e))}}}function w(c,a,b,e){this.atOccurrence=!1;this.doc=c;b=b?c.clipPos(b):g(0,0);this.pos={from:b,to:b};if("object"==typeof e)var d=e.caseFold;else d=e,e=null;"string"==typeof a?(null==d&&(d=!1),this.matches=function(b,e){return(b?A:z)(c,a,e,d)}):(a=f(a),this.matches=e&&!1===e.multiline?function(b,d){return(b?t:m)(c,a,d)}:function(b,d){return(b?y:q)(c,a,d)})}var g=b.Pos;if(String.prototype.normalize){var u=function(b){return b.normalize("NFD").toLowerCase()};var v=function(b){return b.normalize("NFD")}}else u=
function(b){return b.toLowerCase()},v=function(b){return b};w.prototype={findNext:function(){return this.find(!1)},findPrevious:function(){return this.find(!0)},find:function(c){for(var a=this.matches(c,this.doc.clipPos(c?this.pos.from:this.pos.to));a&&0==b.cmpPos(a.from,a.to);)c?a.from.ch?a.from=g(a.from.line,a.from.ch-1):a=a.from.line==this.doc.firstLine()?null:this.matches(c,this.doc.clipPos(g(a.from.line-1))):a.to.ch<this.doc.getLine(a.to.line).length?a.to=g(a.to.line,a.to.ch+1):a=a.to.line==
this.doc.lastLine()?null:this.matches(c,g(a.to.line+1,0));if(a)return this.pos=a,this.atOccurrence=!0,this.pos.match||!0;c=g(c?this.doc.firstLine():this.doc.lastLine()+1,0);this.pos={from:c,to:c};return this.atOccurrence=!1},from:function(){if(this.atOccurrence)return this.pos.from},to:function(){if(this.atOccurrence)return this.pos.to},replace:function(c,a){this.atOccurrence&&(c=b.splitLines(c),this.doc.replaceRange(c,this.pos.from,this.pos.to,a),this.pos.to=g(this.pos.from.line+c.length-1,c[c.length-
1].length+(1==c.length?this.pos.from.ch:0)))}};b.defineExtension("getSearchCursor",function(b,a,d){return new w(this.doc,b,a,d)});b.defineDocExtension("getSearchCursor",function(b,a,d){return new w(this,b,a,d)});b.defineExtension("selectMatches",function(c,a){var d=[];for(c=this.getSearchCursor(c,this.getCursor("from"),a);c.findNext()&&!(0<b.cmpPos(c.to(),this.getCursor("to")));)d.push({anchor:c.from(),head:c.to()});d.length&&this.setSelections(d,0)})});
