'use strict';(function(e){"object"==typeof exports&&"object"==typeof module?e(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed"),require("../ruby/ruby")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed","../ruby/ruby"],e):e(CodeMirror)})(function(e){e.defineMode("slim",function(m){function J(b,a,c){var d=function(d,e){e.tokenize=a;return d.pos<b?(d.pos=b,c):e.tokenize(d,e)};return function(b,c){c.tokenize=d;return a(b,c)}}function t(b,a){b.stack=
{parent:b.stack,style:"continuation",indented:a,tokenize:b.line};b.line=b.tokenize}function u(b){b.line==b.tokenize&&(b.line=b.stack.tokenize,b.stack=b.stack.parent)}function K(b,a){return function(c,d){u(d);if(c.match(/^\\$/))return t(d,b),"lineContinuation";var f=a(c,d);c.eol()&&c.current().match(/(?:^|[^\\])(?:\\\\)*\\$/)&&c.backUp(1);return f}}function L(b,a){return function(c,d){u(d);var f=a(c,d);c.eol()&&c.current().match(/,$/)&&t(d,b);return f}}function v(b,a){return function(c,d){return c.peek()==
b&&1==d.rubyState.tokenize.length?(c.next(),d.tokenize=a,"closeAttributeTag"):n(c,d)}}function g(b){var a,c=function(c,f){if(1==f.rubyState.tokenize.length&&!f.rubyState.context.prev){c.backUp(1);if(c.eatSpace())return f.rubyState=a,f.tokenize=b,b(c,f);c.next()}return n(c,f)};return function(b,f){a=f.rubyState;f.rubyState=p.startState();f.tokenize=c;return n(b,f)}}function n(b,a){return p.token(b,a.rubyState)}function z(b,a){if(b.match(/^#\{/))return a.tokenize=v("}",a.tokenize),null;var c=r.token(b,
a.htmlState),d=b.current(),f=d.search(/[^\\]#\{/);-1<f&&(a.tokenize=J(b.pos,a.tokenize,c),b.backUp(d.length-f-1));return c}function M(b){return function(a,c){var d;d=a.match(/^\\$/)?"lineContinuation":z(a,c);a.eol()&&(c.tokenize=b);return d}}function A(b,a,c){a.stack={parent:a.stack,style:"html",indented:b.column()+c,tokenize:a.line};a.line=a.tokenize=z;return null}function B(b,a){b.skipToEnd();return a.stack.style}function l(b,a){if(b.eat(a.stack.endQuote))return a.line=a.stack.line,a.tokenize=a.stack.tokenize,
a.stack=a.stack.parent,null;if(b.match(N))return a.tokenize=O,"slimAttribute";b.next();return null}function O(b,a){return b.match(/^==?/)?(a.tokenize=P,null):l(b,a)}function P(b,a){var c=b.peek();return'"'==c||"'"==c?(a.tokenize=C(c,"string",!0,!1,l),b.next(),a.tokenize(b,a)):"["==c?g(l)(b,a):b.match(/^(true|false|nil)\b/)?(a.tokenize=l,"keyword"):g(l)(b,a)}function Q(b,a){if(b.match(/^#\{/))return a.tokenize=v("}",a.tokenize),null;var c=new e.StringStream(b.string.slice(a.stack.indented),b.tabSize);
c.pos=b.pos-a.stack.indented;c.start=b.start-a.stack.indented;c.lastColumnPos=b.lastColumnPos-a.stack.indented;c.lastColumnValue=b.lastColumnValue-a.stack.indented;var d=a.subMode.token(c,a.subState);b.pos=c.pos+a.stack.indented;return d}function R(b,a){a.stack.indented=b.column();a.line=a.tokenize=Q;return a.tokenize(b,a)}function S(b,a){b.skipToEnd();return"slimDoctype"}function T(b,a){if("<"==b.peek())return(a.tokenize=M(a.tokenize))(b,a);if(b.match(/^[|']/))return A(b,a,1);if(b.match(/^\/(!|\[\w+])?/))return a.stack=
{parent:a.stack,style:"comment",indented:a.indented+1,tokenize:a.line},a.line=B,B(b,a);if(b.match(/^(-|==?[<>]?)/))return a.tokenize=K(b.column(),L(b.column(),n)),"slimSwitch";if(b.match(/^doctype\b/))return a.tokenize=S,"keyword";var c=b.match(U);if(c){c=c[1];if(w.hasOwnProperty(c))c=w[c];else{var d;d=D[c];var f=e.mimeModes[d];d=f?e.getMode(m,f):(f=e.modes[d])?f(m,{name:d}):e.getMode(m,"null");c=w[c]=d}d=c.startState&&c.startState();a.subMode=c;a.subState=d;a.stack={parent:a.stack,style:"sub",indented:a.indented+
1,tokenize:a.line};a.line=a.tokenize=R;return"slimSubmode"}return x(b,a)}function y(b,a){return a.startOfLine?T(b,a):x(b,a)}function x(b,a){return b.eat("*")?(a.tokenize=g(E),null):b.match(V)?(a.tokenize=E,"slimTag"):q(b,a)}function E(b,a){return b.match(/^(<>?|><?)/)?(a.tokenize=q,null):q(b,a)}function q(b,a){return b.match(W)?(a.tokenize=q,"slimId"):b.match(X)?(a.tokenize=q,"slimClass"):h(b,a)}function h(b,a){return b.match(/^([\[\{\(])/)?(a.stack={parent:a.stack,style:"wrapper",indented:a.indented+
1,tokenize:h,line:a.line,endQuote:Y[RegExp.$1]},a.line=a.tokenize=l,null):b.match(Z)?(a.tokenize=aa,"slimAttribute"):"*"==b.peek()?(b.next(),a.tokenize=g(F),null):F(b,a)}function aa(b,a){return b.match(/^==?/)?(a.tokenize=ba,null):h(b,a)}function ba(b,a){var c=b.peek();return'"'==c||"'"==c?(a.tokenize=C(c,"string",!0,!1,h),b.next(),a.tokenize(b,a)):"["==c?g(h)(b,a):":"==c?g(G)(b,a):b.match(/^(true|false|nil)\b/)?(a.tokenize=h,"keyword"):g(h)(b,a)}function G(b,a){b.backUp(1);if(b.match(/^[^\s],(?=:)/))return a.tokenize=
g(G),null;b.next();return h(b,a)}function C(b,a,c,d,f){return function(e,g){u(g);var k=0==e.current().length;if(e.match(/^\\$/,k)){if(!k)return a;t(g,g.indented);return"lineContinuation"}if(e.match(/^#\{/,k)){if(!k)return a;g.tokenize=v("}",g.tokenize);return null}for(var k=!1,h;null!=(h=e.next());){if(h==b&&(d||!k)){g.tokenize=f;break}if(c&&"#"==h&&!k&&e.eat("{")){e.backUp(2);break}k=!k&&"\\"==h}e.eol()&&k&&e.backUp(1);return a}}function F(b,a){if(b.match(/^==?/))return a.tokenize=n,"slimSwitch";
if(b.match(/^\/$/))return a.tokenize=y,null;if(b.match(/^:/))return a.tokenize=x,"slimSwitch";A(b,a,0);return a.tokenize(b,a)}var r=e.getMode(m,{name:"htmlmixed"}),p=e.getMode(m,"ruby"),w={html:r,ruby:p},D={ruby:"ruby",javascript:"javascript",css:"text/css",sass:"text/x-sass",scss:"text/x-scss",less:"text/x-less",styl:"text/x-styl",coffee:"coffeescript",asciidoc:"text/x-asciidoc",markdown:"text/x-markdown",textile:"text/x-textile",creole:"text/x-creole",wiki:"text/x-wiki",mediawiki:"text/x-mediawiki",
rdoc:"text/x-rdoc",builder:"text/x-builder",nokogiri:"text/x-nokogiri",erb:"application/x-erb"},U=function(b){var a=[],c;for(c in b)a.push(c);return new RegExp("^("+a.join("|")+"):")}(D),H={commentLine:"comment",slimSwitch:"operator special",slimTag:"tag",slimId:"attribute def",slimClass:"attribute qualifier",slimAttribute:"attribute",slimSubmode:"keyword special",closeAttributeTag:null,slimDoctype:null,lineContinuation:null},Y={"{":"}","[":"]","(":")"},V=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd](?::[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]|[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*)/,
Z=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*(?=\s*=)/,N=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*/,
X=/^\.-?[_a-zA-Z]+[\w\-]*/,W=/^#[_a-zA-Z]+[\w\-]*/,I={startState:function(){var b=r.startState(),a=p.startState();return{htmlState:b,rubyState:a,stack:null,last:null,tokenize:y,line:y,indented:0}},copyState:function(b){return{htmlState:e.copyState(r,b.htmlState),rubyState:e.copyState(p,b.rubyState),subMode:b.subMode,subState:b.subMode&&e.copyState(b.subMode,b.subState),stack:b.stack,last:b.last,tokenize:b.tokenize,line:b.line}},token:function(b,a){if(b.sol())for(a.indented=b.indentation(),a.startOfLine=
!0,a.tokenize=a.line;a.stack&&a.stack.indented>a.indented&&"slimSubmode"!=a.last;)a.line=a.tokenize=a.stack.tokenize,a.stack=a.stack.parent,a.subMode=null,a.subState=null;if(b.eatSpace())return null;var c=a.tokenize(b,a);a.startOfLine=!1;c&&(a.last=c);return H.hasOwnProperty(c)?H[c]:c},blankLine:function(b){if(b.subMode&&b.subMode.blankLine)return b.subMode.blankLine(b.subState)},innerMode:function(b){return b.subMode?{state:b.subState,mode:b.subMode}:{state:b,mode:I}}};return I},"htmlmixed","ruby");
e.defineMIME("text/x-slim","slim");e.defineMIME("application/x-slim","slim")});
