'use strict';(function(d){"object"==typeof exports&&"object"==typeof module?d(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed"),require("../ruby/ruby")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed","../ruby/ruby"],d):d(CodeMirror)})(function(d){d.defineMode("slim",function(m){function J(b,a,c){var e=function(e,d){d.tokenize=a;return e.pos<b?(e.pos=b,c):d.tokenize(e,d)};return function(b,c){c.tokenize=e;return a(b,c)}}function t(b,a){b.stack=
{parent:b.stack,style:"continuation",indented:a,tokenize:b.line};b.line=b.tokenize}function u(b){b.line==b.tokenize&&(b.line=b.stack.tokenize,b.stack=b.stack.parent)}function K(b,a){return function(c,e){u(e);if(c.match(/^\\$/))return t(e,b),"lineContinuation";var d=a(c,e);c.eol()&&c.current().match(/(?:^|[^\\])(?:\\\\)*\\$/)&&c.backUp(1);return d}}function L(b,a){return function(c,e){u(e);var d=a(c,e);c.eol()&&c.current().match(/,$/)&&t(e,b);return d}}function v(b,a){return function(c,e){return c.peek()==
b&&1==e.rubyState.tokenize.length?(c.next(),e.tokenize=a,"closeAttributeTag"):n(c,e)}}function f(b){var a,c=function(c,d){if(1==d.rubyState.tokenize.length&&!d.rubyState.context.prev){c.backUp(1);if(c.eatSpace())return d.rubyState=a,d.tokenize=b,b(c,d);c.next()}return n(c,d)};return function(b,h){a=h.rubyState;h.rubyState=d.startState(p);h.tokenize=c;return n(b,h)}}function n(b,a){return p.token(b,a.rubyState)}function z(b,a){if(b.match(/^#\{/))return a.tokenize=v("}",a.tokenize),null;var c=r.token(b,
a.htmlState),e=b.current(),d=e.search(/[^\\]#\{/);-1<d&&(a.tokenize=J(b.pos,a.tokenize,c),b.backUp(e.length-d-1));return c}function M(b){return function(a,c){var d;d=a.match(/^\\$/)?"lineContinuation":z(a,c);a.eol()&&(c.tokenize=b);return d}}function A(b,a,c){a.stack={parent:a.stack,style:"html",indented:b.column()+c,tokenize:a.line};a.line=a.tokenize=z;return null}function B(b,a){b.skipToEnd();return a.stack.style}function k(b,a){if(b.eat(a.stack.endQuote))return a.line=a.stack.line,a.tokenize=a.stack.tokenize,
a.stack=a.stack.parent,null;if(b.match(N))return a.tokenize=O,"slimAttribute";b.next();return null}function O(b,a){return b.match(/^==?/)?(a.tokenize=P,null):k(b,a)}function P(b,a){var c=b.peek();return'"'==c||"'"==c?(a.tokenize=C(c,"string",!0,!1,k),b.next(),a.tokenize(b,a)):"["==c?f(k)(b,a):b.match(/^(true|false|nil)\b/)?(a.tokenize=k,"keyword"):f(k)(b,a)}function Q(b,a){if(b.match(/^#\{/))return a.tokenize=v("}",a.tokenize),null;var c=new d.StringStream(b.string.slice(a.stack.indented),b.tabSize);
c.pos=b.pos-a.stack.indented;c.start=b.start-a.stack.indented;c.lastColumnPos=b.lastColumnPos-a.stack.indented;c.lastColumnValue=b.lastColumnValue-a.stack.indented;var e=a.subMode.token(c,a.subState);b.pos=c.pos+a.stack.indented;return e}function R(b,a){a.stack.indented=b.column();a.line=a.tokenize=Q;return a.tokenize(b,a)}function S(b,a){b.skipToEnd();return"slimDoctype"}function T(b,a){if("<"==b.peek())return(a.tokenize=M(a.tokenize))(b,a);if(b.match(/^[|']/))return A(b,a,1);if(b.match(/^\/(!|\[\w+])?/))return a.stack=
{parent:a.stack,style:"comment",indented:a.indented+1,tokenize:a.line},a.line=B,B(b,a);if(b.match(/^(-|==?[<>]?)/))return a.tokenize=K(b.column(),L(b.column(),n)),"slimSwitch";if(b.match(/^doctype\b/))return a.tokenize=S,"keyword";var c=b.match(U);if(c){c=c[1];if(w.hasOwnProperty(c))c=w[c];else{var e;e=D[c];var h=d.mimeModes[e];e=h?d.getMode(m,h):(h=d.modes[e])?h(m,{name:e}):d.getMode(m,"null");c=w[c]=e}e=d.startState(c);a.subMode=c;a.subState=e;a.stack={parent:a.stack,style:"sub",indented:a.indented+
1,tokenize:a.line};a.line=a.tokenize=R;return"slimSubmode"}return x(b,a)}function y(b,a){return a.startOfLine?T(b,a):x(b,a)}function x(b,a){return b.eat("*")?(a.tokenize=f(E),null):b.match(V)?(a.tokenize=E,"slimTag"):q(b,a)}function E(b,a){return b.match(/^(<>?|><?)/)?(a.tokenize=q,null):q(b,a)}function q(b,a){return b.match(W)?(a.tokenize=q,"slimId"):b.match(X)?(a.tokenize=q,"slimClass"):g(b,a)}function g(b,a){return b.match(/^([\[\{\(])/)?(a.stack={parent:a.stack,style:"wrapper",indented:a.indented+
1,tokenize:g,line:a.line,endQuote:Y[RegExp.$1]},a.line=a.tokenize=k,null):b.match(Z)?(a.tokenize=aa,"slimAttribute"):"*"==b.peek()?(b.next(),a.tokenize=f(F),null):F(b,a)}function aa(b,a){return b.match(/^==?/)?(a.tokenize=ba,null):g(b,a)}function ba(b,a){var c=b.peek();return'"'==c||"'"==c?(a.tokenize=C(c,"string",!0,!1,g),b.next(),a.tokenize(b,a)):"["==c?f(g)(b,a):":"==c?f(G)(b,a):b.match(/^(true|false|nil)\b/)?(a.tokenize=g,"keyword"):f(g)(b,a)}function G(b,a){b.backUp(1);if(b.match(/^[^\s],(?=:)/))return a.tokenize=
f(G),null;b.next();return g(b,a)}function C(b,a,c,d,h){return function(f,g){u(g);var l=0==f.current().length;if(f.match(/^\\$/,l)){if(!l)return a;t(g,g.indented);return"lineContinuation"}if(f.match(/^#\{/,l)){if(!l)return a;g.tokenize=v("}",g.tokenize);return null}for(var l=!1,k;null!=(k=f.next());){if(k==b&&(d||!l)){g.tokenize=h;break}if(c&&"#"==k&&!l&&f.eat("{")){f.backUp(2);break}l=!l&&"\\"==k}f.eol()&&l&&f.backUp(1);return a}}function F(b,a){if(b.match(/^==?/))return a.tokenize=n,"slimSwitch";
if(b.match(/^\/$/))return a.tokenize=y,null;if(b.match(/^:/))return a.tokenize=x,"slimSwitch";A(b,a,0);return a.tokenize(b,a)}var r=d.getMode(m,{name:"htmlmixed"}),p=d.getMode(m,"ruby"),w={html:r,ruby:p},D={ruby:"ruby",javascript:"javascript",css:"text/css",sass:"text/x-sass",scss:"text/x-scss",less:"text/x-less",styl:"text/x-styl",coffee:"coffeescript",asciidoc:"text/x-asciidoc",markdown:"text/x-markdown",textile:"text/x-textile",creole:"text/x-creole",wiki:"text/x-wiki",mediawiki:"text/x-mediawiki",
rdoc:"text/x-rdoc",builder:"text/x-builder",nokogiri:"text/x-nokogiri",erb:"application/x-erb"},U=function(b){var a=[],c;for(c in b)a.push(c);return new RegExp("^("+a.join("|")+"):")}(D),H={commentLine:"comment",slimSwitch:"operator special",slimTag:"tag",slimId:"attribute def",slimClass:"attribute qualifier",slimAttribute:"attribute",slimSubmode:"keyword special",closeAttributeTag:null,slimDoctype:null,lineContinuation:null},Y={"{":"}","[":"]","(":")"},V=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd](?::[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]|[_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*)/,
Z=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*(?=\s*=)/,N=/^[:_a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd][:\._a-zA-Z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\-0-9\u00b7\u0300-\u036f\u203f-\u2040]*/,
X=/^\.-?[_a-zA-Z]+[\w\-]*/,W=/^#[_a-zA-Z]+[\w\-]*/,I={startState:function(){var b=d.startState(r),a=d.startState(p);return{htmlState:b,rubyState:a,stack:null,last:null,tokenize:y,line:y,indented:0}},copyState:function(b){return{htmlState:d.copyState(r,b.htmlState),rubyState:d.copyState(p,b.rubyState),subMode:b.subMode,subState:b.subMode&&d.copyState(b.subMode,b.subState),stack:b.stack,last:b.last,tokenize:b.tokenize,line:b.line}},token:function(b,a){if(b.sol())for(a.indented=b.indentation(),a.startOfLine=
!0,a.tokenize=a.line;a.stack&&a.stack.indented>a.indented&&"slimSubmode"!=a.last;)a.line=a.tokenize=a.stack.tokenize,a.stack=a.stack.parent,a.subMode=null,a.subState=null;if(b.eatSpace())return null;var c=a.tokenize(b,a);a.startOfLine=!1;c&&(a.last=c);return H.hasOwnProperty(c)?H[c]:c},blankLine:function(b){if(b.subMode&&b.subMode.blankLine)return b.subMode.blankLine(b.subState)},innerMode:function(b){return b.subMode?{state:b.subState,mode:b.subMode}:{state:b,mode:I}}};return I},"htmlmixed","ruby");
d.defineMIME("text/x-slim","slim");d.defineMIME("application/x-slim","slim")});
