'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(e,n,m){e instanceof String&&(e=String(e));for(var w=e.length,u=0;u<w;u++){var x=e[u];if(n.call(m,x,u,e))return{i:u,v:x}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,n,m){e!=Array.prototype&&e!=Object.prototype&&(e[n]=m.value)};$jscomp.getGlobal=function(e){e=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,e];for(var n=0;n<e.length;++n){var m=e[n];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,n,m,w){if(n){m=$jscomp.global;e=e.split(".");for(w=0;w<e.length-1;w++){var u=e[w];u in m||(m[u]={});m=m[u]}e=e[e.length-1];w=m[e];n=n(w);n!=w&&null!=n&&$jscomp.defineProperty(m,e,{configurable:!0,writable:!0,value:n})}};$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,m){return $jscomp.findInternal(this,e,m).v}},"es6","es3");
(function(e){"object"==typeof exports&&"object"==typeof module?e(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","diff_match_patch"],e):e(CodeMirror)})(function(e){function n(a,b){this.mv=a;this.type=b;this.classes="left"==b?{chunk:"CodeMirror-merge-l-chunk",start:"CodeMirror-merge-l-chunk-start",end:"CodeMirror-merge-l-chunk-end",insert:"CodeMirror-merge-l-inserted",del:"CodeMirror-merge-l-deleted",connect:"CodeMirror-merge-l-connect"}:{chunk:"CodeMirror-merge-r-chunk",
start:"CodeMirror-merge-r-chunk-start",end:"CodeMirror-merge-r-chunk-end",insert:"CodeMirror-merge-r-inserted",del:"CodeMirror-merge-r-deleted",connect:"CodeMirror-merge-r-connect"}}function m(a){a.diffOutOfDate&&(a.diff=S(a.orig.getValue(),a.edit.getValue(),a.mv.options.ignoreWhitespace),a.chunks=T(a.diff),a.diffOutOfDate=!1,e.signal(a.edit,"updateDiff",a.diff))}function w(a){function b(b){F=!0;y=!1;"full"==b&&(a.svg&&G(a.svg),a.copyButtons&&G(a.copyButtons),K(a.edit,k.marked,a.classes),K(a.orig,
h.marked,a.classes),k.from=k.to=h.from=h.to=0);m(a);a.showDifferences&&(U(a.edit,a.diff,k,DIFF_INSERT,a.classes),U(a.orig,a.diff,h,DIFF_DELETE,a.classes));"align"==a.mv.options.connect&&L(a);A(a);null!=a.needsScrollSync&&x(a,a.needsScrollSync);F=!1}function c(b){F||(a.dealigned=!0,d(b))}function d(a){F||y||(clearTimeout(l),!0===a&&(y=!0),l=setTimeout(b,!0===a?20:250))}function f(b,d){a.diffOutOfDate||(a.diffOutOfDate=!0,k.from=k.to=h.from=h.to=0);c(d.text.length-1!=d.to.line-d.from.line)}function g(){a.diffOutOfDate=
!0;a.dealigned=!0;b("full")}var k={from:0,to:0,marked:[]},h={from:0,to:0,marked:[]},l,y=!1;a.edit.on("change",f);a.orig.on("change",f);a.edit.on("swapDoc",g);a.orig.on("swapDoc",g);"align"==a.mv.options.connect&&(e.on(a.edit.state.trackAlignable,"realign",c),e.on(a.orig.state.trackAlignable,"realign",c));a.edit.on("viewportChange",function(){d(!1)});a.orig.on("viewportChange",function(){d(!1)});b();return b}function u(a,b){a.edit.on("scroll",function(){x(a,!0)&&A(a)});a.orig.on("scroll",function(){x(a,
!1)&&A(a);b&&x(b,!0)&&A(b)})}function x(a,b){if(a.diffOutOfDate)return a.lockScroll&&null==a.needsScrollSync&&(a.needsScrollSync=b),!1;a.needsScrollSync=null;if(!a.lockScroll)return!0;var c=+new Date;if(b){var d=a.edit;var f=a.orig}else d=a.orig,f=a.edit;if(d.state.scrollSetBy==a&&(d.state.scrollSetAt||0)+250>c)return!1;var g=d.getScrollInfo();if("align"==a.mv.options.connect)v=g.top;else{var k=.5*g.clientHeight;v=g.top+k;var h=d.lineAtHeight(v,"local");for(var l=a.chunks,y,e,E,m=0;m<l.length;m++){var q=
l[m],n=b?q.editFrom:q.origFrom,r=b?q.editTo:q.origTo;null==e&&(n>h?(e=q.editFrom,E=q.origFrom):r>h&&(e=q.editTo,E=q.origTo));if(r<=h){y=q.editTo;var t=q.origTo}else n<=h&&(y=q.editFrom,t=q.origFrom)}h={before:y,after:e};t={before:t,after:E};d=V(d,b?h:t);b=V(f,b?t:h);var v=b.top-k+(v-d.top)/(d.bot-d.top)*(b.bot-b.top),D;v>g.top&&1>(D=g.top/k)?v=v*D+g.top*(1-D):(b=g.height-g.clientHeight-g.top)<k&&(d=f.getScrollInfo(),d.height-d.clientHeight-v>b&&1>(D=b/k)&&(v=v*D+(d.height-d.clientHeight-b)*(1-D)))}f.scrollTo(g.left,
v);f.state.scrollSetAt=c;f.state.scrollSetBy=a;return!0}function V(a,b){var c=b.after;null==c&&(c=a.lastLine()+1);return{top:a.heightAtLine(b.before||0,"local"),bot:a.heightAtLine(c,"local")}}function W(a,b,c){(a.lockScroll=b)&&0!=c&&x(a,DIFF_INSERT)&&A(a);(b?e.addClass:e.rmClass)(a.lockButton,"CodeMirror-merge-scrolllock-enabled")}function K(a,b,c){for(var d=0;d<b.length;++d){var f=b[d];if(f instanceof e.TextMarker)f.clear();else if(f.parent)for(var g=a,k=c,h=k.classLocation,l=0;l<h.length;l++)g.removeLineClass(f,
h[l],k.chunk),g.removeLineClass(f,h[l],k.start),g.removeLineClass(f,h[l],k.end)}b.length=0}function U(a,b,c,d,f){var g=a.getViewport();a.operation(function(){c.from==c.to||20<g.from-c.to||20<c.from-g.to?(K(a,c.marked,f),M(a,b,d,c.marked,g.from,g.to,f),c.from=g.from,c.to=g.to):(g.from<c.from&&(M(a,b,d,c.marked,g.from,c.from,f),c.from=g.from),g.to>c.to&&(M(a,b,d,c.marked,c.to,g.to,f),c.to=g.to))})}function N(a,b,c,d,f,g){var k=c.classLocation;b=a.getLineHandle(b);for(var h=0;h<k.length;h++)d&&a.addLineClass(b,
k[h],c.chunk),f&&a.addLineClass(b,k[h],c.start),g&&a.addLineClass(b,k[h],c.end);return b}function M(a,b,c,d,f,g,k){function h(b,c){for(var h=Math.max(f,b),l=Math.min(g,c),e=h;e<l;++e)d.push(N(a,e,k,!0,e==b,e==c-1));b==c&&h==c&&l==c&&(h?d.push(N(a,h-1,k,!1,!1,!0)):d.push(N(a,h,k,!1,!0,!1)))}for(var l=p(0,0),y=p(f,0),e=a.clipPos(p(g-1)),E=c==DIFF_DELETE?k.del:k.insert,m=0,q=!1,n=0;n<b.length;++n){var r=b[n],t=r[0];r=r[1];t==DIFF_EQUAL?(t=l.line+(X(b,n)?0:1),H(l,r),r=l.line+(Y(b,n)?1:0),r>t&&(q&&(h(m,
t),q=!1),m=r)):(q=!0,t==c&&(t=H(l,r,!0),l=0<(y.line-l.line||y.ch-l.ch)?y:l,r=0>(e.line-t.line||e.ch-t.ch)?e:t,l.line==r.line&&l.ch==r.ch||d.push(a.markText(l,r,{className:E})),l=t))}q&&h(m,l.line+1)}function A(a){if(a.showDifferences){if(a.svg){G(a.svg);var b=a.gap.offsetWidth;Z(a.svg,"width",b,"height",a.gap.offsetHeight)}a.copyButtons&&G(a.copyButtons);var c=a.edit.getViewport(),d=a.orig.getViewport(),f=a.mv.wrap.getBoundingClientRect().top,g=f-a.edit.getScrollerElement().getBoundingClientRect().top+
a.edit.getScrollInfo().top;f=f-a.orig.getScrollerElement().getBoundingClientRect().top+a.orig.getScrollInfo().top;for(var k=0;k<a.chunks.length;k++){var h=a.chunks[k];if(h.editFrom<=c.to&&h.editTo>=c.from&&h.origFrom<=d.to&&h.origTo>=d.from){var l=a,e=f,C=g,m=b,n="left"==l.type,q=l.orig.heightAtLine(h.origFrom,"local",!0)-e;if(l.svg){var p=q,r=l.edit.heightAtLine(h.editFrom,"local",!0)-C;if(n){var t=p;p=r;r=t}e=l.orig.heightAtLine(h.origTo,"local",!0)-e;var v=l.edit.heightAtLine(h.editTo,"local",
!0)-C;n&&(t=e,e=v,v=t);n=" C "+m/2+" "+r+" "+m/2+" "+p+" "+(m+2)+" "+p;p=" C "+m/2+" "+e+" "+m/2+" "+v+" -1 "+v;Z(l.svg.appendChild(document.createElementNS("http://www.w3.org/2000/svg","path")),"d","M -1 "+r+n+" L "+(m+2)+" "+e+p+" z","class",l.classes.connect)}l.copyButtons&&(m=l.copyButtons.appendChild(z("div","left"==l.type?"\u21dd":"\u21dc","CodeMirror-merge-copy")),r=l.mv.options.allowEditingOriginals,m.title=l.edit.phrase(r?"Push to left":"Revert chunk"),m.chunk=h,m.style.top=(h.origTo>h.origFrom?
q:l.edit.heightAtLine(h.editFrom,"local")-C)+"px",r&&(C=l.edit.heightAtLine(h.editFrom,"local")-C,q=l.copyButtons.appendChild(z("div","right"==l.type?"\u21dd":"\u21dc","CodeMirror-merge-copy-reverse")),q.title="Push to right",q.chunk={editFrom:h.origFrom,editTo:h.origTo,origFrom:h.editFrom,origTo:h.editTo},q.style.top=C+"px","right"==l.type?q.style.left="2px":q.style.right="2px"))}}}}function aa(a,b){for(var c=0,d=0,f=0;f<b.length;f++){var g=b[f];if(g.editTo>a&&g.editFrom<=a)return null;if(g.editFrom>
a)break;c=g.editTo;d=g.origTo}return d+(a-c)}function O(a,b,c){var d=a.state.trackAlignable;a=a.firstLine();for(var f=0,g=[],k=0;;k++){for(var h=b[k],l=h?c?h.origFrom:h.editFrom:1E9;f<d.alignable.length;f+=2){var e=d.alignable[f]+1;if(!(e<=a))if(e<=l)g.push(e);else break}if(!h)break;g.push(a=c?h.origTo:h.editTo)}return g}function ba(a,b,c,d){var f=0,g=0,k=0,h=0;a:for(;;f++){var l=a[f],e=b[g];if(!l&&null==e)break;var m=l?l[0]:1E9;for(e=null==e?1E9:e;k<c.length;){var n=c[k];if(n.origFrom<=e&&n.origTo>
e){g++;f--;continue a}if(n.editTo>m){if(n.editFrom<=m)continue a;break}h+=n.origTo-n.origFrom-(n.editTo-n.editFrom);k++}m==e-h?(l[d]=e,g++):m<e-h?l[d]=m+h:(l=[e-h,null,null],l[d]=e,a.splice(f,0,l),g++)}}function ka(a,b){var c=O(a.edit,a.chunks,!1),d=[];if(b)for(var f=0,g=0;f<b.chunks.length;f++){for(var k=b.chunks[f].editTo;g<c.length&&c[g]<k;)g++;g!=c.length&&c[g]==k||c.splice(g++,0,k)}for(f=0;f<c.length;f++)d.push([c[f],null,null]);ba(d,O(a.orig,a.chunks,!0),a.chunks,1);b&&ba(d,O(b.orig,b.chunks,
!0),b.chunks,2);return d}function L(a,b){if(a.dealigned||b){if(!a.orig.curOp)return a.orig.operation(function(){L(a,b)});a.dealigned=!1;var c=a.mv.left==a?a.mv.right:a.mv.left;c&&(m(c),c.dealigned=!1);for(var d=ka(a,c),f=a.mv.aligners,g=0;g<f.length;g++)f[g].clear();f.length=0;var k=[a.edit,a.orig],h=[],e=[];c&&k.push(c.orig);for(g=0;g<k.length;g++)h.push(k[g].getScrollInfo().top),e.push(-k[g].getScrollerElement().getBoundingClientRect().top);(e[0]!=e[1]||3==k.length&&e[1]!=e[2])&&ca(k,e,[0,0,0],
f);for(c=0;c<d.length;c++)ca(k,e,d[c],f);for(g=0;g<k.length;g++)k[g].scrollTo(null,h[g])}}function ca(a,b,c,d){for(var f=-1E8,g=[],k=0;k<a.length;k++)if(null!=c[k]){var h=a[k].heightAtLine(c[k],"local")-b[k];g[k]=h;f=Math.max(f,h)}for(k=0;k<a.length;k++)null!=c[k]&&(b=f-g[k],1<b&&d.push(la(a[k],c[k],b)))}function la(a,b,c){var d=!0;b>a.lastLine()&&(b--,d=!1);var f=document.createElement("div");f.className="CodeMirror-merge-spacer";f.style.height=c+"px";f.style.minWidth="1px";return a.addLineWidget(b,
f,{height:c,above:d,mergeSpacer:!0,handleMouseEvents:!0})}function da(a,b,c,d){if(!a.diffOutOfDate){var f=d.origTo>c.lastLine()?p(d.origFrom-1):p(d.origFrom,0),g=p(d.origTo,0),k=d.editTo>b.lastLine()?p(d.editFrom-1):p(d.editFrom,0);d=p(d.editTo,0);var h=a.mv.options.revertChunk;h?h(a.mv,c,f,g,b,k,d):b.replaceRange(c.getRange(f,g),k,d)}}function ea(a){var b=a.lockButton=z("div",null,"CodeMirror-merge-scrolllock"),c=z("div",[b],"CodeMirror-merge-scrolllock-wrap");e.on(b,"click",function(){W(a,!a.lockScroll)});
b=[c];!1!==a.mv.options.revertButtons&&(a.copyButtons=z("div",null,"CodeMirror-merge-copybuttons-"+a.type),e.on(a.copyButtons,"click",function(b){b=b.target||b.srcElement;b.chunk&&("CodeMirror-merge-copy-reverse"==b.className?da(a,a.orig,a.edit,b.chunk):da(a,a.edit,a.orig,b.chunk))}),b.unshift(a.copyButtons));"align"!=a.mv.options.connect&&((c=document.createElementNS&&document.createElementNS("http://www.w3.org/2000/svg","svg"))&&!c.createSVGRect&&(c=null),(a.svg=c)&&b.push(c));return a.gap=z("div",
b,"CodeMirror-merge-gap")}function fa(a){return"string"==typeof a?a:a.getValue()}function S(a,b,c){P||(P=new diff_match_patch);a=P.diff_main(a,b);for(b=0;b<a.length;++b){var d=a[b];(c?/[^ \t]/.test(d[1]):d[1])?b&&a[b-1][0]==d[0]&&(a.splice(b--,1),a[b][1]+=d[1]):a.splice(b--,1)}return a}function T(a){var b=[];if(!a.length)return b;for(var c=0,d=0,f=p(0,0),g=p(0,0),k=0;k<a.length;++k){var h=a[k],e=h[0];if(e==DIFF_EQUAL){var m=!X(a,k)||f.line<c||g.line<d?1:0;e=f.line+m;m=g.line+m;H(f,h[1],null,g);var n=
Y(a,k)?1:0;h=f.line+n;n=g.line+n;h>e&&(k&&b.push({origFrom:d,origTo:m,editFrom:c,editTo:e}),c=h,d=n)}else H(e==DIFF_INSERT?f:g,h[1])}(c<=f.line||d<=g.line)&&b.push({origFrom:d,origTo:g.line+1,editFrom:c,editTo:f.line+1});return b}function Y(a,b){if(b==a.length-1)return!0;var c=a[b+1][1];if(1==c.length&&b<a.length-2||10!=c.charCodeAt(0))return!1;if(b==a.length-2)return!0;c=a[b+2][1];return(1<c.length||b==a.length-3)&&10==c.charCodeAt(0)}function X(a,b){if(0==b)return!0;var c=a[b-1][1];if(10!=c.charCodeAt(c.length-
1))return!1;if(1==b)return!0;c=a[b-2][1];return 10==c.charCodeAt(c.length-1)}function ma(a,b,c){function d(){g.clear();a.removeLineClass(b,"wrap","CodeMirror-merge-collapsed-line")}a.addLineClass(b,"wrap","CodeMirror-merge-collapsed-line");var f=document.createElement("span");f.className="CodeMirror-merge-collapsed-widget";f.title=a.phrase("Identical text collapsed. Click to expand.");var g=a.markText(p(b,0),p(c-1),{inclusiveLeft:!0,inclusiveRight:!0,replacedWith:f,clearOnEnter:!0});g.explicitlyCleared&&
d();e.on(f,"click",d);g.on("clear",d);e.on(f,"click",d);return{mark:g,clear:d}}function na(a,b){function c(){for(var a=0;a<d.length;a++)d[a].clear()}for(var d=[],f=0;f<b.length;f++){var g=b[f];g=ma(g.cm,g.line,g.line+a);d.push(g);g.mark.on("clear",c)}return d[0].mark}function ha(a,b,c,d){for(var f=0;f<a.chunks.length;f++)for(var g=a.chunks[f],e=g.editFrom-b;e<g.editTo+b;e++){var h=e+c;0<=h&&h<d.length&&(d[h]=!1)}}function z(a,b,c,d){a=document.createElement(a);c&&(a.className=c);d&&(a.style.cssText=
d);if("string"==typeof b)a.appendChild(document.createTextNode(b));else if(b)for(c=0;c<b.length;++c)a.appendChild(b[c]);return a}function G(a){for(var b=a.childNodes.length;0<b;--b)a.removeChild(a.firstChild)}function Z(a){for(var b=1;b<arguments.length;b+=2)a.setAttribute(arguments[b],arguments[b+1])}function Q(a,b){b||(b={});for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function H(a,b,c,d){a=c?p(a.line,a.ch):a;for(c=0;;){var f=b.indexOf("\n",c);if(-1==f)break;++a.line;d&&++d.line;c=f+
1}a.ch=(c?0:a.ch)+(b.length-c);d&&(d.ch=(c?0:d.ch)+(b.length-c));return a}function R(a){this.cm=a;this.alignable=[];this.height=a.doc.height;var b=this;a.on("markerAdded",function(a,d){d.collapsed&&(a=d.find(1),null!=a&&b.set(a.line,I))});a.on("markerCleared",function(a,d,f,g){null!=g&&d.collapsed&&b.check(g,I,b.hasMarker)});a.on("markerChanged",this.signal.bind(this));a.on("lineWidgetAdded",function(a,d,f){d.mergeSpacer||(d.above?b.set(f-1,B):b.set(f,ia))});a.on("lineWidgetCleared",function(a,d,
f){d.mergeSpacer||(d.above?b.check(f-1,B,b.hasWidgetBelow):b.check(f,ia,b.hasWidget))});a.on("lineWidgetChanged",this.signal.bind(this));a.on("change",function(a,d){a=d.from.line;var c=d.to.line-d.from.line,g=d.text.length-1,e=a+g;(c||g)&&b.map(a,c,g);b.check(e,I,b.hasMarker);(c||g)&&b.check(d.from.line,I,b.hasMarker)});a.on("viewportChange",function(){b.cm.doc.height!=b.height&&b.signal()})}function ja(a,b){var c=null,d=a.state.diffViews,f=a.getCursor().line;if(d)for(var g=0;g<d.length;g++){var k=
d[g],h=a==k.orig;m(k);if(0>b)a:{k=k.chunks;for(var l=k.length-1;0<=l;l--){var n=k[l];n=(h?n.origTo:n.editTo)-1;if(n<f){h=n;break a}}h=void 0}else a:{k=k.chunks;for(l=0;l<k.length;l++)if(n=k[l],n=h?n.origFrom:n.editFrom,n>f){h=n;break a}h=void 0}null!=h&&(null==c||(0>b?h>c:h<c))&&(c=h)}if(null!=c)a.setCursor(c,0);else return e.Pass}var p=e.Pos;n.prototype={constructor:n,init:function(a,b,c){this.edit=this.mv.edit;(this.edit.state.diffViews||(this.edit.state.diffViews=[])).push(this);this.orig=e(a,
Q({value:b,readOnly:!this.mv.options.allowEditingOriginals},Q(c)));"align"==this.mv.options.connect&&(this.edit.state.trackAlignable||(this.edit.state.trackAlignable=new R(this.edit)),this.orig.state.trackAlignable=new R(this.orig));this.lockButton.title=this.edit.phrase("Toggle locked scrolling");this.orig.state.diffViews=[this];a=c.chunkClassLocation||"background";"[object Array]"!=Object.prototype.toString.call(a)&&(a=[a]);this.classes.classLocation=a;this.diff=S(fa(b),fa(c.value),this.mv.options.ignoreWhitespace);
this.chunks=T(this.diff);this.diffOutOfDate=this.dealigned=!1;this.needsScrollSync=null;this.showDifferences=!1!==c.showDifferences},registerEvents:function(a){this.forceUpdate=w(this);W(this,!0,!1);u(this,a)},setShowDifferences:function(a){a=!1!==a;a!=this.showDifferences&&(this.showDifferences=a,this.forceUpdate("full"))}};var F=!1,J=e.MergeView=function(a,b){if(!(this instanceof J))return new J(a,b);this.options=b;var c=b.origLeft,d=null==b.origRight?b.orig:b.origRight,f=null!=c,g=null!=d,k=1+
(f?1:0)+(g?1:0),h=[],l=this.left=null,m=this.right=null,p=this;if(f){l=this.left=new n(this,"left");var w=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-left");h.push(w);h.push(ea(l))}f=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-editor");h.push(f);if(g){m=this.right=new n(this,"right");h.push(ea(m));var u=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-right");h.push(u)}(g?u:f).className+=" CodeMirror-merge-pane-rightmost";h.push(z("div",null,null,"height: 0; clear: both;"));
var q=this.wrap=a.appendChild(z("div",h,"CodeMirror-merge CodeMirror-merge-"+k+"pane"));this.edit=e(f,Q(b));l&&l.init(w,c,b);m&&m.init(u,d,b);b.collapseIdentical&&this.editor().operation(function(){var a=b.collapseIdentical;"number"!=typeof a&&(a=2);for(var c=[],d=p.editor(),g=d.firstLine(),f=g,e=d.lastLine();f<=e;f++)c.push(!0);p.left&&ha(p.left,a,g,c);p.right&&ha(p.right,a,g,c);for(f=0;f<c.length;f++)if(c[f]){e=f+g;for(var h=1;f<c.length-1&&c[f+1];f++,h++);if(h>a){var k=[{line:e,cm:d}];p.left&&
k.push({line:aa(e,p.left.chunks),cm:p.left.orig});p.right&&k.push({line:aa(e,p.right.chunks),cm:p.right.orig});k=na(h,k);if(p.options.onCollapse)p.options.onCollapse(p,e,h,k)}}});"align"==b.connect&&(this.aligners=[],L(this.left||this.right,!0));l&&l.registerEvents(m);m&&m.registerEvents(l);var x=function(){l&&A(l);m&&A(m)};e.on(window,"resize",x);var r=setInterval(function(){for(var a=q.parentNode;a&&a!=document.body;a=a.parentNode);a||(clearInterval(r),e.off(window,"resize",x))},5E3)};J.prototype=
{constructor:J,editor:function(){return this.edit},rightOriginal:function(){return this.right&&this.right.orig},leftOriginal:function(){return this.left&&this.left.orig},setShowDifferences:function(a){this.right&&this.right.setShowDifferences(a);this.left&&this.left.setShowDifferences(a)},rightChunks:function(){if(this.right)return m(this.right),this.right.chunks},leftChunks:function(){if(this.left)return m(this.left),this.left.chunks}};var P,ia=1,B=2,I=4;R.prototype={signal:function(){e.signal(this,
"realign");this.height=this.cm.doc.height},set:function(a,b){for(var c=-1;c<this.alignable.length;c+=2){var d=this.alignable[c]-a;if(0==d){if((this.alignable[c+1]&b)==b)return;this.alignable[c+1]|=b;this.signal();return}if(0<d)break}this.signal();this.alignable.splice(c,0,a,b)},find:function(a){for(var b=0;b<this.alignable.length;b+=2)if(this.alignable[b]==a)return b;return-1},check:function(a,b,c){var d=this.find(a);-1!=d&&this.alignable[d+1]&b&&!c.call(this,a)&&(this.signal(),(a=this.alignable[d+
1]&~b)?this.alignable[d+1]=a:this.alignable.splice(d,2))},hasMarker:function(a){a=this.cm.getLineHandle(a);if(a.markedSpans)for(var b=0;b<a.markedSpans.length;b++)if(a.markedSpans[b].marker.collapsed&&null!=a.markedSpans[b].to)return!0;return!1},hasWidget:function(a){a=this.cm.getLineHandle(a);if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(!a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},hasWidgetBelow:function(a){if(a==this.cm.lastLine())return!1;a=this.cm.getLineHandle(a+1);
if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},map:function(a,b,c){for(var d=c-b,f=a+b,g=b=-1,e=0;e<this.alignable.length;e+=2){var h=this.alignable[e];h==a&&this.alignable[e+1]&B&&(b=e);h==f&&this.alignable[e+1]&B&&(g=e);h<=a||(h<f?this.alignable.splice(e--,2):this.alignable[e]+=d)}-1<b&&(d=this.alignable[b+1],d==B?this.alignable.splice(b,2):this.alignable[b+1]=d&~B);-1<g&&c&&this.set(a+c,B)}};e.commands.goNextDiff=function(a){return ja(a,
1)};e.commands.goPrevDiff=function(a){return ja(a,-1)}});
