'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,m,l){d instanceof String&&(d=String(d));for(var q=d.length,n=0;n<q;n++){var u=d[n];if(m.call(l,u,n,d))return{i:n,v:u}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,m,l){if(d==Array.prototype||d==Object.prototype)return d;d[m]=l.value;return d};$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var m=0;m<d.length;++m){var l=d[m];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,m){var l=$jscomp.propertyToPolyfillSymbol[m];if(null==l)return d[m];l=d[l];return void 0!==l?l:d[m]};
$jscomp.polyfill=function(d,m,l,q){m&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,m,l,q):$jscomp.polyfillUnisolated(d,m,l,q))};$jscomp.polyfillUnisolated=function(d,m,l,q){l=$jscomp.global;d=d.split(".");for(q=0;q<d.length-1;q++){var n=d[q];n in l||(l[n]={});l=l[n]}d=d[d.length-1];q=l[d];m=m(q);m!=q&&null!=m&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:m})};
$jscomp.polyfillIsolated=function(d,m,l,q){var n=d.split(".");d=1===n.length;q=n[0];q=!d&&q in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var u=0;u<n.length-1;u++){var C=n[u];C in q||(q[C]={});q=q[C]}n=n[n.length-1];l=$jscomp.IS_SYMBOL_NATIVE&&"es6"===l?q[n]:null;m=m(l);null!=m&&(d?$jscomp.defineProperty($jscomp.polyfills,n,{configurable:!0,writable:!0,value:m}):m!==l&&($jscomp.propertyToPolyfillSymbol[n]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(n):$jscomp.POLYFILL_PREFIX+n,n=$jscomp.propertyToPolyfillSymbol[n],
$jscomp.defineProperty(q,n,{configurable:!0,writable:!0,value:m})))};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,l){return $jscomp.findInternal(this,d,l).v}},"es6","es3");
(function(d){"object"==typeof exports&&"object"==typeof module?d(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","diff_match_patch"],d):d(CodeMirror)})(function(d){function m(a,b){this.mv=a;this.type=b;this.classes="left"==b?{chunk:"CodeMirror-merge-l-chunk",start:"CodeMirror-merge-l-chunk-start",end:"CodeMirror-merge-l-chunk-end",insert:"CodeMirror-merge-l-inserted",del:"CodeMirror-merge-l-deleted",connect:"CodeMirror-merge-l-connect"}:{chunk:"CodeMirror-merge-r-chunk",
start:"CodeMirror-merge-r-chunk-start",end:"CodeMirror-merge-r-chunk-end",insert:"CodeMirror-merge-r-inserted",del:"CodeMirror-merge-r-deleted",connect:"CodeMirror-merge-r-connect"}}function l(a){a.diffOutOfDate&&(a.diff=S(a.orig.getValue(),a.edit.getValue(),a.mv.options.ignoreWhitespace),a.chunks=T(a.diff),a.diffOutOfDate=!1,d.signal(a.edit,"updateDiff",a.diff))}function q(a){function b(b){E=!0;J=!1;"full"==b&&(a.svg&&F(a.svg),a.copyButtons&&F(a.copyButtons),K(a.edit,h.marked,a.classes),K(a.orig,
g.marked,a.classes),h.from=h.to=g.from=g.to=0);l(a);a.showDifferences&&(U(a.edit,a.diff,h,DIFF_INSERT,a.classes),U(a.orig,a.diff,g,DIFF_DELETE,a.classes));"align"==a.mv.options.connect&&L(a);A(a);null!=a.needsScrollSync&&u(a,a.needsScrollSync);E=!1}function c(b){E||(a.dealigned=!0,e(b))}function e(a){E||J||(clearTimeout(p),!0===a&&(J=!0),p=setTimeout(b,!0===a?20:250))}function k(b,e){a.diffOutOfDate||(a.diffOutOfDate=!0,h.from=h.to=g.from=g.to=0);c(e.text.length-1!=e.to.line-e.from.line)}function f(){a.diffOutOfDate=
!0;a.dealigned=!0;b("full")}var h={from:0,to:0,marked:[]},g={from:0,to:0,marked:[]},p,J=!1;a.edit.on("change",k);a.orig.on("change",k);a.edit.on("swapDoc",f);a.orig.on("swapDoc",f);"align"==a.mv.options.connect&&(d.on(a.edit.state.trackAlignable,"realign",c),d.on(a.orig.state.trackAlignable,"realign",c));a.edit.on("viewportChange",function(){e(!1)});a.orig.on("viewportChange",function(){e(!1)});b();return b}function n(a,b){a.edit.on("scroll",function(){u(a,!0)&&A(a)});a.orig.on("scroll",function(){u(a,
!1)&&A(a);b&&u(b,!0)&&A(b)})}function u(a,b){if(a.diffOutOfDate)return a.lockScroll&&null==a.needsScrollSync&&(a.needsScrollSync=b),!1;a.needsScrollSync=null;if(!a.lockScroll)return!0;var c=+new Date;if(b){var e=a.edit;var k=a.orig}else e=a.orig,k=a.edit;if(e.state.scrollSetBy==a&&(e.state.scrollSetAt||0)+250>c)return!1;var f=e.getScrollInfo();if("align"==a.mv.options.connect)w=f.top;else{var h=.5*f.clientHeight;w=f.top+h;var g=e.lineAtHeight(w,"local");for(var p=a.chunks,d,D,l,m=0;m<p.length;m++){var y=
p[m],n=b?y.editFrom:y.origFrom,r=b?y.editTo:y.origTo;null==D&&(n>g?(D=y.editFrom,l=y.origFrom):r>g&&(D=y.editTo,l=y.origTo));if(r<=g){d=y.editTo;var t=y.origTo}else n<=g&&(d=y.editFrom,t=y.origFrom)}g={before:d,after:D};t={before:t,after:l};e=C(e,b?g:t);b=C(k,b?t:g);var w=b.top-h+(w-e.top)/(e.bot-e.top)*(b.bot-b.top),q;w>f.top&&1>(q=f.top/h)?w=w*q+f.top*(1-q):(b=f.height-f.clientHeight-f.top)<h&&(e=k.getScrollInfo(),e.height-e.clientHeight-w>b&&1>(q=b/h)&&(w=w*q+(e.height-e.clientHeight-b)*(1-q)))}k.scrollTo(f.left,
w);k.state.scrollSetAt=c;k.state.scrollSetBy=a;return!0}function C(a,b){var c=b.after;null==c&&(c=a.lastLine()+1);return{top:a.heightAtLine(b.before||0,"local"),bot:a.heightAtLine(c,"local")}}function V(a,b,c){(a.lockScroll=b)&&0!=c&&u(a,DIFF_INSERT)&&A(a);(b?d.addClass:d.rmClass)(a.lockButton,"CodeMirror-merge-scrolllock-enabled")}function K(a,b,c){for(var e=0;e<b.length;++e){var k=b[e];if(k instanceof d.TextMarker)k.clear();else if(k.parent)for(var f=a,h=c,g=h.classLocation,p=0;p<g.length;p++)f.removeLineClass(k,
g[p],h.chunk),f.removeLineClass(k,g[p],h.start),f.removeLineClass(k,g[p],h.end)}b.length=0}function U(a,b,c,e,k){var f=a.getViewport();a.operation(function(){c.from==c.to||20<f.from-c.to||20<c.from-f.to?(K(a,c.marked,k),M(a,b,e,c.marked,f.from,f.to,k),c.from=f.from,c.to=f.to):(f.from<c.from&&(M(a,b,e,c.marked,f.from,c.from,k),c.from=f.from),f.to>c.to&&(M(a,b,e,c.marked,c.to,f.to,k),c.to=f.to))})}function N(a,b,c,e,k,f){var h=c.classLocation;b=a.getLineHandle(b);for(var g=0;g<h.length;g++)e&&a.addLineClass(b,
h[g],c.chunk),k&&a.addLineClass(b,h[g],c.start),f&&a.addLineClass(b,h[g],c.end);return b}function M(a,b,c,e,k,f,h){function g(b,c){for(var g=Math.max(k,b),p=Math.min(f,c),d=g;d<p;++d)e.push(N(a,d,h,!0,d==b,d==c-1));b==c&&g==c&&p==c&&(g?e.push(N(a,g-1,h,!1,!1,!0)):e.push(N(a,g,h,!1,!0,!1)))}for(var p=v(0,0),d=v(k,0),l=a.clipPos(v(f-1)),m=c==DIFF_DELETE?h.del:h.insert,q=0,n=!1,x=0;x<b.length;++x){var r=b[x],t=r[0];r=r[1];t==DIFF_EQUAL?(t=p.line+(W(b,x)?0:1),G(p,r),r=p.line+(X(b,x)?1:0),r>t&&(n&&(g(q,
t),n=!1),q=r)):(n=!0,t==c&&(t=G(p,r,!0),p=0<(d.line-p.line||d.ch-p.ch)?d:p,r=0>(l.line-t.line||l.ch-t.ch)?l:t,p.line==r.line&&p.ch==r.ch||e.push(a.markText(p,r,{className:m})),p=t))}n&&g(q,p.line+1)}function A(a){if(a.showDifferences){if(a.svg){F(a.svg);var b=a.gap.offsetWidth;Y(a.svg,"width",b,"height",a.gap.offsetHeight)}a.copyButtons&&F(a.copyButtons);var c=a.edit.getViewport(),e=a.orig.getViewport(),k=a.mv.wrap.getBoundingClientRect().top,f=k-a.edit.getScrollerElement().getBoundingClientRect().top+
a.edit.getScrollInfo().top;k=k-a.orig.getScrollerElement().getBoundingClientRect().top+a.orig.getScrollInfo().top;for(var h=0;h<a.chunks.length;h++){var g=a.chunks[h];if(g.editFrom<=c.to&&g.editTo>=c.from&&g.origFrom<=e.to&&g.origTo>=e.from){var p=a,d=k,l=f,m=b,q="left"==p.type,n=p.orig.heightAtLine(g.origFrom,"local",!0)-d;if(p.svg){var x=n,r=p.edit.heightAtLine(g.editFrom,"local",!0)-l;if(q){var t=x;x=r;r=t}d=p.orig.heightAtLine(g.origTo,"local",!0)-d;var w=p.edit.heightAtLine(g.editTo,"local",
!0)-l;q&&(t=d,d=w,w=t);q=" C "+m/2+" "+r+" "+m/2+" "+x+" "+(m+2)+" "+x;x=" C "+m/2+" "+d+" "+m/2+" "+w+" -1 "+w;Y(p.svg.appendChild(document.createElementNS("http://www.w3.org/2000/svg","path")),"d","M -1 "+r+q+" L "+(m+2)+" "+d+x+" z","class",p.classes.connect)}p.copyButtons&&(m=p.copyButtons.appendChild(z("div","left"==p.type?"\u21dd":"\u21dc","CodeMirror-merge-copy")),r=p.mv.options.allowEditingOriginals,m.title=p.edit.phrase(r?"Push to left":"Revert chunk"),m.chunk=g,m.style.top=(g.origTo>g.origFrom?
n:p.edit.heightAtLine(g.editFrom,"local")-l)+"px",r&&(l=p.edit.heightAtLine(g.editFrom,"local")-l,n=p.copyButtons.appendChild(z("div","right"==p.type?"\u21dd":"\u21dc","CodeMirror-merge-copy-reverse")),n.title="Push to right",n.chunk={editFrom:g.origFrom,editTo:g.origTo,origFrom:g.editFrom,origTo:g.editTo},n.style.top=l+"px","right"==p.type?n.style.left="2px":n.style.right="2px"))}}}}function Z(a,b){for(var c=0,e=0,k=0;k<b.length;k++){var f=b[k];if(f.editTo>a&&f.editFrom<=a)return null;if(f.editFrom>
a)break;c=f.editTo;e=f.origTo}return e+(a-c)}function O(a,b,c){var e=a.state.trackAlignable;a=a.firstLine();for(var k=0,f=[],h=0;;h++){for(var g=b[h],d=g?c?g.origFrom:g.editFrom:1E9;k<e.alignable.length;k+=2){var l=e.alignable[k]+1;if(!(l<=a))if(l<=d)f.push(l);else break}if(!g)break;f.push(a=c?g.origTo:g.editTo)}return f}function aa(a,b,c,e){var k=0,f=0,h=0,g=0;a:for(;;k++){var d=a[k],l=b[f];if(!d&&null==l)break;var m=d?d[0]:1E9;for(l=null==l?1E9:l;h<c.length;){var n=c[h];if(n.origFrom<=l&&n.origTo>
l){f++;k--;continue a}if(n.editTo>m){if(n.editFrom<=m)continue a;break}g+=n.origTo-n.origFrom-(n.editTo-n.editFrom);h++}m==l-g?(d[e]=l,f++):m<l-g?d[e]=m+g:(d=[l-g,null,null],d[e]=l,a.splice(k,0,d),f++)}}function ja(a,b){var c=O(a.edit,a.chunks,!1),e=[];if(b)for(var k=0,f=0;k<b.chunks.length;k++){for(var h=b.chunks[k].editTo;f<c.length&&c[f]<h;)f++;f!=c.length&&c[f]==h||c.splice(f++,0,h)}for(k=0;k<c.length;k++)e.push([c[k],null,null]);aa(e,O(a.orig,a.chunks,!0),a.chunks,1);b&&aa(e,O(b.orig,b.chunks,
!0),b.chunks,2);return e}function L(a,b){if(a.dealigned||b){if(!a.orig.curOp)return a.orig.operation(function(){L(a,b)});a.dealigned=!1;var c=a.mv.left==a?a.mv.right:a.mv.left;c&&(l(c),c.dealigned=!1);for(var e=ja(a,c),k=a.mv.aligners,f=0;f<k.length;f++)k[f].clear();k.length=0;var h=[a.edit,a.orig],g=[],d=[];c&&h.push(c.orig);for(f=0;f<h.length;f++)g.push(h[f].getScrollInfo().top),d.push(-h[f].getScrollerElement().getBoundingClientRect().top);(d[0]!=d[1]||3==h.length&&d[1]!=d[2])&&ba(h,d,[0,0,0],
k);for(c=0;c<e.length;c++)ba(h,d,e[c],k);for(f=0;f<h.length;f++)h[f].scrollTo(null,g[f])}}function ba(a,b,c,e){for(var k=-1E8,f=[],h=0;h<a.length;h++)if(null!=c[h]){var d=a[h].heightAtLine(c[h],"local")-b[h];f[h]=d;k=Math.max(k,d)}for(h=0;h<a.length;h++)null!=c[h]&&(b=k-f[h],1<b&&e.push(ka(a[h],c[h],b)))}function ka(a,b,c){var e=!0;b>a.lastLine()&&(b--,e=!1);var k=document.createElement("div");k.className="CodeMirror-merge-spacer";k.style.height=c+"px";k.style.minWidth="1px";return a.addLineWidget(b,
k,{height:c,above:e,mergeSpacer:!0,handleMouseEvents:!0})}function ca(a,b,c,e){if(!a.diffOutOfDate){var k=e.origTo>c.lastLine()?v(e.origFrom-1):v(e.origFrom,0),f=v(e.origTo,0),d=e.editTo>b.lastLine()?v(e.editFrom-1):v(e.editFrom,0);e=v(e.editTo,0);var g=a.mv.options.revertChunk;g?g(a.mv,c,k,f,b,d,e):b.replaceRange(c.getRange(k,f),d,e)}}function da(a){var b=a.lockButton=z("div",null,"CodeMirror-merge-scrolllock"),c=z("div",[b],"CodeMirror-merge-scrolllock-wrap");d.on(b,"click",function(){V(a,!a.lockScroll)});
b=[c];!1!==a.mv.options.revertButtons&&(a.copyButtons=z("div",null,"CodeMirror-merge-copybuttons-"+a.type),d.on(a.copyButtons,"click",function(b){b=b.target||b.srcElement;b.chunk&&("CodeMirror-merge-copy-reverse"==b.className?ca(a,a.orig,a.edit,b.chunk):ca(a,a.edit,a.orig,b.chunk))}),b.unshift(a.copyButtons));"align"!=a.mv.options.connect&&((c=document.createElementNS&&document.createElementNS("http://www.w3.org/2000/svg","svg"))&&!c.createSVGRect&&(c=null),(a.svg=c)&&b.push(c));return a.gap=z("div",
b,"CodeMirror-merge-gap")}function ea(a){return"string"==typeof a?a:a.getValue()}function S(a,b,c){P||(P=new diff_match_patch);a=P.diff_main(a,b);for(b=0;b<a.length;++b){var e=a[b];(c?/[^ \t]/.test(e[1]):e[1])?b&&a[b-1][0]==e[0]&&(a.splice(b--,1),a[b][1]+=e[1]):a.splice(b--,1)}return a}function T(a){var b=[];if(!a.length)return b;for(var c=0,e=0,k=v(0,0),f=v(0,0),d=0;d<a.length;++d){var g=a[d],p=g[0];if(p==DIFF_EQUAL){var l=!W(a,d)||k.line<c||f.line<e?1:0;p=k.line+l;l=f.line+l;G(k,g[1],null,f);var m=
X(a,d)?1:0;g=k.line+m;m=f.line+m;g>p&&(d&&b.push({origFrom:e,origTo:l,editFrom:c,editTo:p}),c=g,e=m)}else G(p==DIFF_INSERT?k:f,g[1])}(c<=k.line||e<=f.line)&&b.push({origFrom:e,origTo:f.line+1,editFrom:c,editTo:k.line+1});return b}function X(a,b){if(b==a.length-1)return!0;var c=a[b+1][1];if(1==c.length&&b<a.length-2||10!=c.charCodeAt(0))return!1;if(b==a.length-2)return!0;c=a[b+2][1];return(1<c.length||b==a.length-3)&&10==c.charCodeAt(0)}function W(a,b){if(0==b)return!0;var c=a[b-1][1];if(10!=c.charCodeAt(c.length-
1))return!1;if(1==b)return!0;c=a[b-2][1];return 10==c.charCodeAt(c.length-1)}function la(a,b,c){function e(){f.clear();a.removeLineClass(b,"wrap","CodeMirror-merge-collapsed-line")}a.addLineClass(b,"wrap","CodeMirror-merge-collapsed-line");var k=document.createElement("span");k.className="CodeMirror-merge-collapsed-widget";k.title=a.phrase("Identical text collapsed. Click to expand.");var f=a.markText(v(b,0),v(c-1),{inclusiveLeft:!0,inclusiveRight:!0,replacedWith:k,clearOnEnter:!0});f.explicitlyCleared&&
e();d.on(k,"click",e);f.on("clear",e);d.on(k,"click",e);return{mark:f,clear:e}}function ma(a,b){function c(){for(var a=0;a<e.length;a++)e[a].clear()}for(var e=[],d=0;d<b.length;d++){var f=b[d];f=la(f.cm,f.line,f.line+a);e.push(f);f.mark.on("clear",c)}return e[0].mark}function fa(a,b,c,e){for(var d=0;d<a.chunks.length;d++)for(var f=a.chunks[d],h=f.editFrom-b;h<f.editTo+b;h++){var g=h+c;0<=g&&g<e.length&&(e[g]=!1)}}function z(a,b,c,e){a=document.createElement(a);c&&(a.className=c);e&&(a.style.cssText=
e);if("string"==typeof b)a.appendChild(document.createTextNode(b));else if(b)for(c=0;c<b.length;++c)a.appendChild(b[c]);return a}function F(a){for(var b=a.childNodes.length;0<b;--b)a.removeChild(a.firstChild)}function Y(a){for(var b=1;b<arguments.length;b+=2)a.setAttribute(arguments[b],arguments[b+1])}function Q(a,b){b||(b={});for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function G(a,b,c,e){a=c?v(a.line,a.ch):a;for(c=0;;){var d=b.indexOf("\n",c);if(-1==d)break;++a.line;e&&++e.line;c=d+
1}a.ch=(c?0:a.ch)+(b.length-c);e&&(e.ch=(c?0:e.ch)+(b.length-c));return a}function R(a){this.cm=a;this.alignable=[];this.height=a.doc.height;var b=this;a.on("markerAdded",function(a,e){e.collapsed&&(a=e.find(1),null!=a&&b.set(a.line,H))});a.on("markerCleared",function(a,e,d,f){null!=f&&e.collapsed&&b.check(f,H,b.hasMarker)});a.on("markerChanged",this.signal.bind(this));a.on("lineWidgetAdded",function(a,e,d){e.mergeSpacer||(e.above?b.set(d-1,B):b.set(d,ha))});a.on("lineWidgetCleared",function(a,e,
d){e.mergeSpacer||(e.above?b.check(d-1,B,b.hasWidgetBelow):b.check(d,ha,b.hasWidget))});a.on("lineWidgetChanged",this.signal.bind(this));a.on("change",function(a,e){a=e.from.line;var c=e.to.line-e.from.line,d=e.text.length-1,h=a+d;(c||d)&&b.map(a,c,d);b.check(h,H,b.hasMarker);(c||d)&&b.check(e.from.line,H,b.hasMarker)});a.on("viewportChange",function(){b.cm.doc.height!=b.height&&b.signal()})}function ia(a,b){var c=null,e=a.state.diffViews,k=a.getCursor().line;if(e)for(var f=0;f<e.length;f++){var h=
e[f],g=a==h.orig;l(h);if(0>b)a:{h=h.chunks;for(var p=h.length-1;0<=p;p--){var m=h[p];m=(g?m.origTo:m.editTo)-1;if(m<k){g=m;break a}}g=void 0}else a:{h=h.chunks;for(p=0;p<h.length;p++)if(m=h[p],m=g?m.origFrom:m.editFrom,m>k){g=m;break a}g=void 0}null!=g&&(null==c||(0>b?g>c:g<c))&&(c=g)}if(null!=c)a.setCursor(c,0);else return d.Pass}var v=d.Pos;m.prototype={constructor:m,init:function(a,b,c){this.edit=this.mv.edit;(this.edit.state.diffViews||(this.edit.state.diffViews=[])).push(this);this.orig=d(a,
Q({value:b,readOnly:!this.mv.options.allowEditingOriginals},Q(c)));"align"==this.mv.options.connect&&(this.edit.state.trackAlignable||(this.edit.state.trackAlignable=new R(this.edit)),this.orig.state.trackAlignable=new R(this.orig));this.lockButton.title=this.edit.phrase("Toggle locked scrolling");this.orig.state.diffViews=[this];a=c.chunkClassLocation||"background";"[object Array]"!=Object.prototype.toString.call(a)&&(a=[a]);this.classes.classLocation=a;this.diff=S(ea(b),ea(c.value),this.mv.options.ignoreWhitespace);
this.chunks=T(this.diff);this.diffOutOfDate=this.dealigned=!1;this.needsScrollSync=null;this.showDifferences=!1!==c.showDifferences},registerEvents:function(a){this.forceUpdate=q(this);V(this,!0,!1);n(this,a)},setShowDifferences:function(a){a=!1!==a;a!=this.showDifferences&&(this.showDifferences=a,this.forceUpdate("full"))}};var E=!1,I=d.MergeView=function(a,b){if(!(this instanceof I))return new I(a,b);this.options=b;var c=b.origLeft,e=null==b.origRight?b.orig:b.origRight,k=null!=c,f=null!=e,h=1+
(k?1:0)+(f?1:0),g=[],l=this.left=null,n=this.right=null,q=this;if(k){l=this.left=new m(this,"left");var v=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-left");g.push(v);g.push(da(l))}k=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-editor");g.push(k);if(f){n=this.right=new m(this,"right");g.push(da(n));var u=z("div",null,"CodeMirror-merge-pane CodeMirror-merge-right");g.push(u)}(f?u:k).className+=" CodeMirror-merge-pane-rightmost";g.push(z("div",null,null,"height: 0; clear: both;"));
var y=this.wrap=a.appendChild(z("div",g,"CodeMirror-merge CodeMirror-merge-"+h+"pane"));this.edit=d(k,Q(b));l&&l.init(v,c,b);n&&n.init(u,e,b);b.collapseIdentical&&this.editor().operation(function(){var a=b.collapseIdentical;"number"!=typeof a&&(a=2);for(var c=[],e=q.editor(),d=e.firstLine(),f=d,g=e.lastLine();f<=g;f++)c.push(!0);q.left&&fa(q.left,a,d,c);q.right&&fa(q.right,a,d,c);for(f=0;f<c.length;f++)if(c[f]){g=f+d;for(var h=1;f<c.length-1&&c[f+1];f++,h++);if(h>a){var k=[{line:g,cm:e}];q.left&&
k.push({line:Z(g,q.left.chunks),cm:q.left.orig});q.right&&k.push({line:Z(g,q.right.chunks),cm:q.right.orig});k=ma(h,k);if(q.options.onCollapse)q.options.onCollapse(q,g,h,k)}}});"align"==b.connect&&(this.aligners=[],L(this.left||this.right,!0));l&&l.registerEvents(n);n&&n.registerEvents(l);var x=function(){l&&A(l);n&&A(n)};d.on(window,"resize",x);var r=setInterval(function(){for(var a=y.parentNode;a&&a!=document.body;a=a.parentNode);a||(clearInterval(r),d.off(window,"resize",x))},5E3)};I.prototype=
{constructor:I,editor:function(){return this.edit},rightOriginal:function(){return this.right&&this.right.orig},leftOriginal:function(){return this.left&&this.left.orig},setShowDifferences:function(a){this.right&&this.right.setShowDifferences(a);this.left&&this.left.setShowDifferences(a)},rightChunks:function(){if(this.right)return l(this.right),this.right.chunks},leftChunks:function(){if(this.left)return l(this.left),this.left.chunks}};var P,ha=1,B=2,H=4;R.prototype={signal:function(){d.signal(this,
"realign");this.height=this.cm.doc.height},set:function(a,b){for(var c=-1;c<this.alignable.length;c+=2){var e=this.alignable[c]-a;if(0==e){if((this.alignable[c+1]&b)==b)return;this.alignable[c+1]|=b;this.signal();return}if(0<e)break}this.signal();this.alignable.splice(c,0,a,b)},find:function(a){for(var b=0;b<this.alignable.length;b+=2)if(this.alignable[b]==a)return b;return-1},check:function(a,b,c){var e=this.find(a);-1!=e&&this.alignable[e+1]&b&&!c.call(this,a)&&(this.signal(),(a=this.alignable[e+
1]&~b)?this.alignable[e+1]=a:this.alignable.splice(e,2))},hasMarker:function(a){a=this.cm.getLineHandle(a);if(a.markedSpans)for(var b=0;b<a.markedSpans.length;b++)if(a.markedSpans[b].marker.collapsed&&null!=a.markedSpans[b].to)return!0;return!1},hasWidget:function(a){a=this.cm.getLineHandle(a);if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(!a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},hasWidgetBelow:function(a){if(a==this.cm.lastLine())return!1;a=this.cm.getLineHandle(a+1);
if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},map:function(a,b,c){for(var e=c-b,d=a+b,f=b=-1,h=0;h<this.alignable.length;h+=2){var g=this.alignable[h];g==a&&this.alignable[h+1]&B&&(b=h);g==d&&this.alignable[h+1]&B&&(f=h);g<=a||(g<d?this.alignable.splice(h--,2):this.alignable[h]+=e)}-1<b&&(e=this.alignable[b+1],e==B?this.alignable.splice(b,2):this.alignable[b+1]=e&~B);-1<f&&c&&this.set(a+c,B)}};d.commands.goNextDiff=function(a){return ia(a,
1)};d.commands.goPrevDiff=function(a){return ia(a,-1)}});
