'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,l,n){d instanceof String&&(d=String(d));for(var p=d.length,m=0;m<p;m++){var v=d[m];if(l.call(n,v,m,d))return{i:m,v:v}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,l,n){if(d==Array.prototype||d==Object.prototype)return d;d[l]=n.value;return d};$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var l=0;l<d.length;++l){var n=d[l];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,l){var n=$jscomp.propertyToPolyfillSymbol[l];if(null==n)return d[l];n=d[n];return void 0!==n?n:d[l]};
$jscomp.polyfill=function(d,l,n,p){l&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,l,n,p):$jscomp.polyfillUnisolated(d,l,n,p))};$jscomp.polyfillUnisolated=function(d,l,n,p){n=$jscomp.global;d=d.split(".");for(p=0;p<d.length-1;p++){var m=d[p];if(!(m in n))return;n=n[m]}d=d[d.length-1];p=n[d];l=l(p);l!=p&&null!=l&&$jscomp.defineProperty(n,d,{configurable:!0,writable:!0,value:l})};
$jscomp.polyfillIsolated=function(d,l,n,p){var m=d.split(".");d=1===m.length;p=m[0];p=!d&&p in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var v=0;v<m.length-1;v++){var C=m[v];if(!(C in p))return;p=p[C]}m=m[m.length-1];n=$jscomp.IS_SYMBOL_NATIVE&&"es6"===n?p[m]:null;l=l(n);null!=l&&(d?$jscomp.defineProperty($jscomp.polyfills,m,{configurable:!0,writable:!0,value:l}):l!==n&&($jscomp.propertyToPolyfillSymbol[m]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(m):$jscomp.POLYFILL_PREFIX+m,m=
$jscomp.propertyToPolyfillSymbol[m],$jscomp.defineProperty(p,m,{configurable:!0,writable:!0,value:l})))};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,n){return $jscomp.findInternal(this,d,n).v}},"es6","es3");
(function(d){"object"==typeof exports&&"object"==typeof module?d(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","diff_match_patch"],d):d(CodeMirror)})(function(d){function l(a,b){this.mv=a;this.type=b;this.classes="left"==b?{chunk:"CodeMirror-merge-l-chunk",start:"CodeMirror-merge-l-chunk-start",end:"CodeMirror-merge-l-chunk-end",insert:"CodeMirror-merge-l-inserted",del:"CodeMirror-merge-l-deleted",connect:"CodeMirror-merge-l-connect"}:{chunk:"CodeMirror-merge-r-chunk",
start:"CodeMirror-merge-r-chunk-start",end:"CodeMirror-merge-r-chunk-end",insert:"CodeMirror-merge-r-inserted",del:"CodeMirror-merge-r-deleted",connect:"CodeMirror-merge-r-connect"}}function n(a){a.diffOutOfDate&&(a.diff=R(a.orig.getValue(),a.edit.getValue(),a.mv.options.ignoreWhitespace),a.chunks=S(a.diff),a.diffOutOfDate=!1,d.signal(a.edit,"updateDiff",a.diff))}function p(a){function b(b){D=!0;I=!1;"full"==b&&(a.svg&&E(a.svg),a.copyButtons&&E(a.copyButtons),J(a.edit,h.marked,a.classes),J(a.orig,
g.marked,a.classes),h.from=h.to=g.from=g.to=0);n(a);a.showDifferences&&(T(a.edit,a.diff,h,DIFF_INSERT,a.classes),T(a.orig,a.diff,g,DIFF_DELETE,a.classes));"align"==a.mv.options.connect&&K(a);B(a);null!=a.needsScrollSync&&v(a,a.needsScrollSync);D=!1}function c(b){D||(a.dealigned=!0,e(b))}function e(a){D||I||(clearTimeout(q),!0===a&&(I=!0),q=setTimeout(b,!0===a?20:250))}function k(b,e){a.diffOutOfDate||(a.diffOutOfDate=!0,h.from=h.to=g.from=g.to=0);c(e.text.length-1!=e.to.line-e.from.line)}function f(){a.diffOutOfDate=
!0;a.dealigned=!0;b("full")}var h={from:0,to:0,marked:[]},g={from:0,to:0,marked:[]},q,I=!1;a.edit.on("change",k);a.orig.on("change",k);a.edit.on("swapDoc",f);a.orig.on("swapDoc",f);"align"==a.mv.options.connect&&(d.on(a.edit.state.trackAlignable,"realign",c),d.on(a.orig.state.trackAlignable,"realign",c));a.edit.on("viewportChange",function(){e(!1)});a.orig.on("viewportChange",function(){e(!1)});b();return b}function m(a,b){a.edit.on("scroll",function(){v(a,!0)&&B(a)});a.orig.on("scroll",function(){v(a,
!1)&&B(a);b&&v(b,!0)&&B(b)})}function v(a,b){if(a.diffOutOfDate)return a.lockScroll&&null==a.needsScrollSync&&(a.needsScrollSync=b),!1;a.needsScrollSync=null;if(!a.lockScroll)return!0;var c=+new Date;if(b){var e=a.edit;var k=a.orig}else e=a.orig,k=a.edit;if(e.state.scrollSetBy==a&&(e.state.scrollSetAt||0)+250>c)return!1;var f=e.getScrollInfo();if("align"==a.mv.options.connect)w=f.top;else{var h=.5*f.clientHeight;w=f.top+h;var g=e.lineAtHeight(w,"local");for(var q=a.chunks,d,A,n,l=0;l<q.length;l++){var x=
q[l],m=b?x.editFrom:x.origFrom,r=b?x.editTo:x.origTo;null==A&&(m>g?(A=x.editFrom,n=x.origFrom):r>g&&(A=x.editTo,n=x.origTo));if(r<=g){d=x.editTo;var u=x.origTo}else m<=g&&(d=x.editFrom,u=x.origFrom)}g={before:d,after:A};u={before:u,after:n};e=C(e,b?g:u);b=C(k,b?u:g);var w=b.top-h+(w-e.top)/(e.bot-e.top)*(b.bot-b.top),p;w>f.top&&1>(p=f.top/h)?w=w*p+f.top*(1-p):(b=f.height-f.clientHeight-f.top)<h&&(e=k.getScrollInfo(),e.height-e.clientHeight-w>b&&1>(p=b/h)&&(w=w*p+(e.height-e.clientHeight-b)*(1-p)))}k.scrollTo(f.left,
w);k.state.scrollSetAt=c;k.state.scrollSetBy=a;return!0}function C(a,b){var c=b.after;null==c&&(c=a.lastLine()+1);return{top:a.heightAtLine(b.before||0,"local"),bot:a.heightAtLine(c,"local")}}function U(a,b,c){(a.lockScroll=b)&&0!=c&&v(a,DIFF_INSERT)&&B(a);(b?d.addClass:d.rmClass)(a.lockButton,"CodeMirror-merge-scrolllock-enabled")}function J(a,b,c){for(var e=0;e<b.length;++e){var k=b[e];if(k instanceof d.TextMarker)k.clear();else if(k.parent)for(var f=a,h=c,g=h.classLocation,q=0;q<g.length;q++)f.removeLineClass(k,
g[q],h.chunk),f.removeLineClass(k,g[q],h.start),f.removeLineClass(k,g[q],h.end)}b.length=0}function T(a,b,c,e,k){var f=a.getViewport();a.operation(function(){c.from==c.to||20<f.from-c.to||20<c.from-f.to?(J(a,c.marked,k),L(a,b,e,c.marked,f.from,f.to,k),c.from=f.from,c.to=f.to):(f.from<c.from&&(L(a,b,e,c.marked,f.from,c.from,k),c.from=f.from),f.to>c.to&&(L(a,b,e,c.marked,c.to,f.to,k),c.to=f.to))})}function M(a,b,c,e,k,f){var h=c.classLocation;b=a.getLineHandle(b);for(var g=0;g<h.length;g++)e&&a.addLineClass(b,
h[g],c.chunk),k&&a.addLineClass(b,h[g],c.start),f&&a.addLineClass(b,h[g],c.end);return b}function L(a,b,c,e,k,f,h){function g(b,c){for(var g=Math.max(k,b),q=Math.min(f,c),d=g;d<q;++d)e.push(M(a,d,h,!0,d==b,d==c-1));b==c&&g==c&&q==c&&(g?e.push(M(a,g-1,h,!1,!1,!0)):e.push(M(a,g,h,!1,!0,!1)))}for(var q=t(0,0),d=t(k,0),A=a.clipPos(t(f-1)),n=c==DIFF_DELETE?h.del:h.insert,l=0,p=!1,m=0;m<b.length;++m){var r=b[m],u=r[0];r=r[1];u==DIFF_EQUAL?(u=q.line+(V(b,m)?0:1),F(q,r),r=q.line+(W(b,m)?1:0),r>u&&(p&&(g(l,
u),p=!1),l=r)):(p=!0,u==c&&(u=F(q,r,!0),q=0<(d.line-q.line||d.ch-q.ch)?d:q,r=0>(A.line-u.line||A.ch-u.ch)?A:u,q.line==r.line&&q.ch==r.ch||e.push(a.markText(q,r,{className:n})),q=u))}p&&g(l,q.line+1)}function B(a){if(a.showDifferences){if(a.svg){E(a.svg);var b=a.gap.offsetWidth;X(a.svg,"width",b,"height",a.gap.offsetHeight)}a.copyButtons&&E(a.copyButtons);var c=a.edit.getViewport(),e=a.orig.getViewport(),k=a.mv.wrap.getBoundingClientRect().top,f=k-a.edit.getScrollerElement().getBoundingClientRect().top+
a.edit.getScrollInfo().top;k=k-a.orig.getScrollerElement().getBoundingClientRect().top+a.orig.getScrollInfo().top;for(var h=0;h<a.chunks.length;h++){var g=a.chunks[h];if(g.editFrom<=c.to&&g.editTo>=c.from&&g.origFrom<=e.to&&g.origTo>=e.from){var q=a,d=k,n=f,l=b,p="left"==q.type,m=q.orig.heightAtLine(g.origFrom,"local",!0)-d;if(q.svg){var t=m,r=q.edit.heightAtLine(g.editFrom,"local",!0)-n;if(p){var u=t;t=r;r=u}d=q.orig.heightAtLine(g.origTo,"local",!0)-d;var w=q.edit.heightAtLine(g.editTo,"local",
!0)-n;p&&(u=d,d=w,w=u);p=" C "+l/2+" "+r+" "+l/2+" "+t+" "+(l+2)+" "+t;t=" C "+l/2+" "+d+" "+l/2+" "+w+" -1 "+w;X(q.svg.appendChild(document.createElementNS("http://www.w3.org/2000/svg","path")),"d","M -1 "+r+p+" L "+(l+2)+" "+d+t+" z","class",q.classes.connect)}q.copyButtons&&(l=q.copyButtons.appendChild(y("div","left"==q.type?"\u21dd":"\u21dc","CodeMirror-merge-copy")),r=q.mv.options.allowEditingOriginals,l.title=q.edit.phrase(r?"Push to left":"Revert chunk"),l.chunk=g,l.style.top=(g.origTo>g.origFrom?
m:q.edit.heightAtLine(g.editFrom,"local")-n)+"px",r&&(n=q.edit.heightAtLine(g.editFrom,"local")-n,m=q.copyButtons.appendChild(y("div","right"==q.type?"\u21dd":"\u21dc","CodeMirror-merge-copy-reverse")),m.title="Push to right",m.chunk={editFrom:g.origFrom,editTo:g.origTo,origFrom:g.editFrom,origTo:g.editTo},m.style.top=n+"px","right"==q.type?m.style.left="2px":m.style.right="2px"))}}}}function Y(a,b){for(var c=0,e=0,k=0;k<b.length;k++){var f=b[k];if(f.editTo>a&&f.editFrom<=a)return null;if(f.editFrom>
a)break;c=f.editTo;e=f.origTo}return e+(a-c)}function N(a,b,c){var e=a.state.trackAlignable;a=a.firstLine();for(var k=0,f=[],h=0;;h++){for(var g=b[h],d=g?c?g.origFrom:g.editFrom:1E9;k<e.alignable.length;k+=2){var l=e.alignable[k]+1;if(!(l<=a))if(l<=d)f.push(l);else break}if(!g)break;f.push(a=c?g.origTo:g.editTo)}return f}function Z(a,b,c,e){var k=0,f=0,h=0,g=0;a:for(;;k++){var d=a[k],l=b[f];if(!d&&null==l)break;var n=d?d[0]:1E9;for(l=null==l?1E9:l;h<c.length;){var m=c[h];if(m.origFrom<=l&&m.origTo>
l){f++;k--;continue a}if(m.editTo>n){if(m.editFrom<=n)continue a;break}g+=m.origTo-m.origFrom-(m.editTo-m.editFrom);h++}n==l-g?(d[e]=l,f++):n<l-g?d[e]=n+g:(d=[l-g,null,null],d[e]=l,a.splice(k,0,d),f++)}}function ia(a,b){var c=N(a.edit,a.chunks,!1),e=[];if(b)for(var k=0,f=0;k<b.chunks.length;k++){for(var h=b.chunks[k].editTo;f<c.length&&c[f]<h;)f++;f!=c.length&&c[f]==h||c.splice(f++,0,h)}for(k=0;k<c.length;k++)e.push([c[k],null,null]);Z(e,N(a.orig,a.chunks,!0),a.chunks,1);b&&Z(e,N(b.orig,b.chunks,
!0),b.chunks,2);return e}function K(a,b){if(a.dealigned||b){if(!a.orig.curOp)return a.orig.operation(function(){K(a,b)});a.dealigned=!1;var c=a.mv.left==a?a.mv.right:a.mv.left;c&&(n(c),c.dealigned=!1);for(var e=ia(a,c),k=a.mv.aligners,f=0;f<k.length;f++)k[f].clear();k.length=0;var h=[a.edit,a.orig],g=[],d=[];c&&h.push(c.orig);for(f=0;f<h.length;f++)g.push(h[f].getScrollInfo().top),d.push(-h[f].getScrollerElement().getBoundingClientRect().top);(d[0]!=d[1]||3==h.length&&d[1]!=d[2])&&aa(h,d,[0,0,0],
k);for(c=0;c<e.length;c++)aa(h,d,e[c],k);for(f=0;f<h.length;f++)h[f].scrollTo(null,g[f])}}function aa(a,b,c,e){for(var k=-1E8,f=[],h=0;h<a.length;h++)if(null!=c[h]){var d=a[h].heightAtLine(c[h],"local")-b[h];f[h]=d;k=Math.max(k,d)}for(h=0;h<a.length;h++)null!=c[h]&&(b=k-f[h],1<b&&e.push(ja(a[h],c[h],b)))}function ja(a,b,c){var e=!0;b>a.lastLine()&&(b--,e=!1);var k=document.createElement("div");k.className="CodeMirror-merge-spacer";k.style.height=c+"px";k.style.minWidth="1px";return a.addLineWidget(b,
k,{height:c,above:e,mergeSpacer:!0,handleMouseEvents:!0})}function ba(a,b,c,e){if(!a.diffOutOfDate){var k=e.origTo>c.lastLine()?t(e.origFrom-1):t(e.origFrom,0),f=t(e.origTo,0),d=e.editTo>b.lastLine()?t(e.editFrom-1):t(e.editFrom,0);e=t(e.editTo,0);var g=a.mv.options.revertChunk;g?g(a.mv,c,k,f,b,d,e):b.replaceRange(c.getRange(k,f),d,e)}}function ca(a){var b=a.lockButton=y("div",null,"CodeMirror-merge-scrolllock"),c=y("div",[b],"CodeMirror-merge-scrolllock-wrap");d.on(b,"click",function(){U(a,!a.lockScroll)});
b=[c];!1!==a.mv.options.revertButtons&&(a.copyButtons=y("div",null,"CodeMirror-merge-copybuttons-"+a.type),d.on(a.copyButtons,"click",function(b){b=b.target||b.srcElement;b.chunk&&("CodeMirror-merge-copy-reverse"==b.className?ba(a,a.orig,a.edit,b.chunk):ba(a,a.edit,a.orig,b.chunk))}),b.unshift(a.copyButtons));"align"!=a.mv.options.connect&&((c=document.createElementNS&&document.createElementNS("http://www.w3.org/2000/svg","svg"))&&!c.createSVGRect&&(c=null),(a.svg=c)&&b.push(c));return a.gap=y("div",
b,"CodeMirror-merge-gap")}function da(a){return"string"==typeof a?a:a.getValue()}function R(a,b,c){O||(O=new diff_match_patch);a=O.diff_main(a,b);for(b=0;b<a.length;++b){var e=a[b];(c?/[^ \t]/.test(e[1]):e[1])?b&&a[b-1][0]==e[0]&&(a.splice(b--,1),a[b][1]+=e[1]):a.splice(b--,1)}return a}function S(a){var b=[];if(!a.length)return b;for(var c=0,e=0,k=t(0,0),f=t(0,0),d=0;d<a.length;++d){var g=a[d],q=g[0];if(q==DIFF_EQUAL){var l=!V(a,d)||k.line<c||f.line<e?1:0;q=k.line+l;l=f.line+l;F(k,g[1],null,f);var n=
W(a,d)?1:0;g=k.line+n;n=f.line+n;g>q&&(d&&b.push({origFrom:e,origTo:l,editFrom:c,editTo:q}),c=g,e=n)}else F(q==DIFF_INSERT?k:f,g[1])}(c<=k.line||e<=f.line)&&b.push({origFrom:e,origTo:f.line+1,editFrom:c,editTo:k.line+1});return b}function W(a,b){if(b==a.length-1)return!0;var c=a[b+1][1];if(1==c.length&&b<a.length-2||10!=c.charCodeAt(0))return!1;if(b==a.length-2)return!0;c=a[b+2][1];return(1<c.length||b==a.length-3)&&10==c.charCodeAt(0)}function V(a,b){if(0==b)return!0;var c=a[b-1][1];if(10!=c.charCodeAt(c.length-
1))return!1;if(1==b)return!0;c=a[b-2][1];return 10==c.charCodeAt(c.length-1)}function ka(a,b,c){function e(){f.clear();a.removeLineClass(b,"wrap","CodeMirror-merge-collapsed-line")}a.addLineClass(b,"wrap","CodeMirror-merge-collapsed-line");var k=document.createElement("span");k.className="CodeMirror-merge-collapsed-widget";k.title=a.phrase("Identical text collapsed. Click to expand.");var f=a.markText(t(b,0),t(c-1),{inclusiveLeft:!0,inclusiveRight:!0,replacedWith:k,clearOnEnter:!0});f.explicitlyCleared&&
e();d.on(k,"click",e);f.on("clear",e);d.on(k,"click",e);return{mark:f,clear:e}}function la(a,b){function c(){for(var a=0;a<e.length;a++)e[a].clear()}for(var e=[],d=0;d<b.length;d++){var f=b[d];f=ka(f.cm,f.line,f.line+a);e.push(f);f.mark.on("clear",c)}return e[0].mark}function ea(a,b,c,e){for(var d=0;d<a.chunks.length;d++)for(var f=a.chunks[d],h=f.editFrom-b;h<f.editTo+b;h++){var g=h+c;0<=g&&g<e.length&&(e[g]=!1)}}function y(a,b,c,e){a=document.createElement(a);c&&(a.className=c);e&&(a.style.cssText=
e);if("string"==typeof b)a.appendChild(document.createTextNode(b));else if(b)for(c=0;c<b.length;++c)a.appendChild(b[c]);return a}function E(a){for(var b=a.childNodes.length;0<b;--b)a.removeChild(a.firstChild)}function X(a){for(var b=1;b<arguments.length;b+=2)a.setAttribute(arguments[b],arguments[b+1])}function P(a,b){b||(b={});for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function F(a,b,c,e){a=c?t(a.line,a.ch):a;for(c=0;;){var d=b.indexOf("\n",c);if(-1==d)break;++a.line;e&&++e.line;c=d+
1}a.ch=(c?0:a.ch)+(b.length-c);e&&(e.ch=(c?0:e.ch)+(b.length-c));return a}function Q(a){this.cm=a;this.alignable=[];this.height=a.doc.height;var b=this;a.on("markerAdded",function(a,e){e.collapsed&&(a=e.find(1),null!=a&&b.set(a.line,G))});a.on("markerCleared",function(a,e,d,f){null!=f&&e.collapsed&&b.check(f,G,b.hasMarker)});a.on("markerChanged",this.signal.bind(this));a.on("lineWidgetAdded",function(a,e,d){e.mergeSpacer||(e.above?b.set(d-1,z):b.set(d,fa))});a.on("lineWidgetCleared",function(a,e,
d){e.mergeSpacer||(e.above?b.check(d-1,z,b.hasWidgetBelow):b.check(d,fa,b.hasWidget))});a.on("lineWidgetChanged",this.signal.bind(this));a.on("change",function(a,e){a=e.from.line;var c=e.to.line-e.from.line,d=e.text.length-1,h=a+d;(c||d)&&b.map(a,c,d);b.check(h,G,b.hasMarker);(c||d)&&b.check(e.from.line,G,b.hasMarker)});a.on("viewportChange",function(){b.cm.doc.height!=b.height&&b.signal()})}function ha(a,b){var c=null,e=a.state.diffViews,k=a.getCursor().line;if(e)for(var f=0;f<e.length;f++){var h=
e[f],g=a==h.orig;n(h);if(0>b)a:{h=h.chunks;for(var l=h.length-1;0<=l;l--){var m=h[l];m=(g?m.origTo:m.editTo)-1;if(m<k){g=m;break a}}g=void 0}else a:{h=h.chunks;for(l=0;l<h.length;l++)if(m=h[l],m=g?m.origFrom:m.editFrom,m>k){g=m;break a}g=void 0}null!=g&&(null==c||(0>b?g>c:g<c))&&(c=g)}if(null!=c)a.setCursor(c,0);else return d.Pass}var t=d.Pos;l.prototype={constructor:l,init:function(a,b,c){this.edit=this.mv.edit;(this.edit.state.diffViews||(this.edit.state.diffViews=[])).push(this);this.orig=d(a,
P({value:b,readOnly:!this.mv.options.allowEditingOriginals},P(c)));"align"==this.mv.options.connect&&(this.edit.state.trackAlignable||(this.edit.state.trackAlignable=new Q(this.edit)),this.orig.state.trackAlignable=new Q(this.orig));this.lockButton.title=this.edit.phrase("Toggle locked scrolling");this.orig.state.diffViews=[this];a=c.chunkClassLocation||"background";"[object Array]"!=Object.prototype.toString.call(a)&&(a=[a]);this.classes.classLocation=a;this.diff=R(da(b),da(c.value),this.mv.options.ignoreWhitespace);
this.chunks=S(this.diff);this.diffOutOfDate=this.dealigned=!1;this.needsScrollSync=null;this.showDifferences=!1!==c.showDifferences},registerEvents:function(a){this.forceUpdate=p(this);U(this,!0,!1);m(this,a)},setShowDifferences:function(a){a=!1!==a;a!=this.showDifferences&&(this.showDifferences=a,this.forceUpdate("full"))}};var D=!1,H=d.MergeView=function(a,b){if(!(this instanceof H))return new H(a,b);this.options=b;var c=b.origLeft,e=null==b.origRight?b.orig:b.origRight,k=null!=c,f=null!=e,h=1+
(k?1:0)+(f?1:0),g=[],m=this.left=null,n=this.right=null,p=this;if(k){m=this.left=new l(this,"left");var t=y("div",null,"CodeMirror-merge-pane CodeMirror-merge-left");g.push(t);g.push(ca(m))}k=y("div",null,"CodeMirror-merge-pane CodeMirror-merge-editor");g.push(k);if(f){n=this.right=new l(this,"right");g.push(ca(n));var v=y("div",null,"CodeMirror-merge-pane CodeMirror-merge-right");g.push(v)}(f?v:k).className+=" CodeMirror-merge-pane-rightmost";g.push(y("div",null,null,"height: 0; clear: both;"));
var x=this.wrap=a.appendChild(y("div",g,"CodeMirror-merge CodeMirror-merge-"+h+"pane"));this.edit=d(k,P(b));m&&m.init(t,c,b);n&&n.init(v,e,b);b.collapseIdentical&&this.editor().operation(function(){var a=b.collapseIdentical;"number"!=typeof a&&(a=2);for(var c=[],e=p.editor(),d=e.firstLine(),f=d,g=e.lastLine();f<=g;f++)c.push(!0);p.left&&ea(p.left,a,d,c);p.right&&ea(p.right,a,d,c);for(f=0;f<c.length;f++)if(c[f]){g=f+d;for(var h=1;f<c.length-1&&c[f+1];f++,h++);if(h>a){var k=[{line:g,cm:e}];p.left&&
k.push({line:Y(g,p.left.chunks),cm:p.left.orig});p.right&&k.push({line:Y(g,p.right.chunks),cm:p.right.orig});k=la(h,k);if(p.options.onCollapse)p.options.onCollapse(p,g,h,k)}}});"align"==b.connect&&(this.aligners=[],K(this.left||this.right,!0));m&&m.registerEvents(n);n&&n.registerEvents(m);var z=function(){m&&B(m);n&&B(n)};d.on(window,"resize",z);var r=setInterval(function(){for(var a=x.parentNode;a&&a!=document.body;a=a.parentNode);a||(clearInterval(r),d.off(window,"resize",z))},5E3)};H.prototype=
{constructor:H,editor:function(){return this.edit},rightOriginal:function(){return this.right&&this.right.orig},leftOriginal:function(){return this.left&&this.left.orig},setShowDifferences:function(a){this.right&&this.right.setShowDifferences(a);this.left&&this.left.setShowDifferences(a)},rightChunks:function(){if(this.right)return n(this.right),this.right.chunks},leftChunks:function(){if(this.left)return n(this.left),this.left.chunks}};var O,fa=1,z=2,G=4;Q.prototype={signal:function(){d.signal(this,
"realign");this.height=this.cm.doc.height},set:function(a,b){for(var c=-1;c<this.alignable.length;c+=2){var e=this.alignable[c]-a;if(0==e){if((this.alignable[c+1]&b)==b)return;this.alignable[c+1]|=b;this.signal();return}if(0<e)break}this.signal();this.alignable.splice(c,0,a,b)},find:function(a){for(var b=0;b<this.alignable.length;b+=2)if(this.alignable[b]==a)return b;return-1},check:function(a,b,c){var e=this.find(a);-1!=e&&this.alignable[e+1]&b&&!c.call(this,a)&&(this.signal(),(a=this.alignable[e+
1]&~b)?this.alignable[e+1]=a:this.alignable.splice(e,2))},hasMarker:function(a){a=this.cm.getLineHandle(a);if(a.markedSpans)for(var b=0;b<a.markedSpans.length;b++)if(a.markedSpans[b].marker.collapsed&&null!=a.markedSpans[b].to)return!0;return!1},hasWidget:function(a){a=this.cm.getLineHandle(a);if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(!a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},hasWidgetBelow:function(a){if(a==this.cm.lastLine())return!1;a=this.cm.getLineHandle(a+1);
if(a.widgets)for(var b=0;b<a.widgets.length;b++)if(a.widgets[b].above&&!a.widgets[b].mergeSpacer)return!0;return!1},map:function(a,b,c){for(var e=c-b,d=a+b,f=b=-1,h=0;h<this.alignable.length;h+=2){var g=this.alignable[h];g==a&&this.alignable[h+1]&z&&(b=h);g==d&&this.alignable[h+1]&z&&(f=h);g<=a||(g<d?this.alignable.splice(h--,2):this.alignable[h]+=e)}-1<b&&(e=this.alignable[b+1],e==z?this.alignable.splice(b,2):this.alignable[b+1]=e&~z);-1<f&&c&&this.set(a+c,z)}};d.commands.goNextDiff=function(a){return ha(a,
1)};d.commands.goPrevDiff=function(a){return ha(a,-1)}});
