'use strict';(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],f):f(CodeMirror)})(function(f){f.defineMode("julia",function(n,g){function h(b,a){"undefined"===typeof a&&(a="\\b");return new RegExp("^(("+b.join(")|(")+"))"+a)}function k(b,a){"undefined"===typeof a&&(a=0);return b.scopes.length<=a?null:b.scopes[b.scopes.length-(a+1)]}function e(b,a){if(b.match("#=",!1))return a.tokenize=
p,a.tokenize(b,a);var d=a.leavingExpr;b.sol()&&(d=!1);a.leavingExpr=!1;if(d&&b.match(/^'+/))return"operator";if(b.match(/\.{4,}/))return"error";if(b.match(/\.{1,3}/))return"operator";if(b.eatSpace())return null;var c=b.peek();if("#"===c)return b.skipToEnd(),"comment";"["===c&&(a.scopes.push("["),a.nestedArrays++);"("===c&&(a.scopes.push("("),a.nestedGenerators++);if(0<a.nestedArrays&&"]"===c){for(;a.scopes.length&&"["!==k(a);)a.scopes.pop();a.scopes.pop();a.nestedArrays--;a.leavingExpr=!0}if(0<a.nestedGenerators&&
")"===c){for(;a.scopes.length&&"("!==k(a);)a.scopes.pop();a.scopes.pop();a.nestedGenerators--;a.leavingExpr=!0}if(0<a.nestedArrays){if("end"==a.lastToken&&b.match(":"))return"operator";if(b.match("end"))return"number"}var l;(l=b.match(q,!1))&&a.scopes.push(l[0]);b.match(r,!1)&&a.scopes.pop();if(b.match(/^::(?![:\$])/))return a.tokenize=t,a.tokenize(b,a);if(!d&&b.match(u)||b.match(/:([<>]:|<<=?|>>>?=?|->|\/\/|\.{2,3}|[\.\\%*+\-<>!\/^|&]=?|[~\?\$])/))return"builtin";if(b.match(v))return"operator";if(b.match(/^\.?\d/,
!1)&&(d=RegExp(/^im\b/),c=!1,b.match(/^0x\.[0-9a-f_]+p[\+\-]?[_\d]+/i)&&(c=!0),b.match(/^0x[0-9a-f_]+/i)&&(c=!0),b.match(/^0b[01_]+/i)&&(c=!0),b.match(/^0o[0-7_]+/i)&&(c=!0),b.match(/^(?:(?:\d[_\d]*)?\.(?!\.)(?:\d[_\d]*)?|\d[_\d]*\.(?!\.)(?:\d[_\d]*))?([Eef][\+\-]?[_\d]+)?/i)&&(c=!0),b.match(/^\d[_\d]*(e[\+\-]?\d+)?/i)&&(c=!0),c))return b.match(d),a.leavingExpr=!0,"number";if(b.match("'"))return a.tokenize=w,a.tokenize(b,a);if(b.match(x))return a.tokenize=y(b.current()),a.tokenize(b,a);if(b.match(z))return"meta";
if(b.match(A))return null;if(b.match(B))return"keyword";if(b.match(C))return"builtin";d=a.isDefinition||"function"==a.lastToken||"macro"==a.lastToken||"type"==a.lastToken||"struct"==a.lastToken||"immutable"==a.lastToken;if(b.match(D)){if(d){if("."===b.peek())return a.isDefinition=!0,"variable";a.isDefinition=!1;return"def"}if(b.match(/^({[^}]*})*\(/,!1))return a.tokenize=E,a.tokenize(b,a);a.leavingExpr=!0;return"variable"}b.next();return"error"}function E(b,a){for(;;){var d=b.match(/^(\(\s*)/),c=
0;d&&(0>a.firstParenPos&&(a.firstParenPos=a.scopes.length),a.scopes.push("("),c+=d[1].length);if("("==k(a)&&b.match(")")&&(a.scopes.pop(),c+=1,a.scopes.length<=a.firstParenPos))return d=b.match(/^(\s*where\s+[^\s=]+)*\s*?=(?!=)/,!1),b.backUp(c),a.firstParenPos=-1,a.tokenize=e,d?"def":"builtin";if(b.match(/^$/g,!1)){for(b.backUp(c);a.scopes.length>a.firstParenPos;)a.scopes.pop();a.firstParenPos=-1;a.tokenize=e;return"builtin"}if(!b.match(/^[^()]+/))return b.next(),null}}function t(b,a){b.match(/.*?(?=[,;{}()=\s]|$)/);
b.match("{")?a.nestedParameters++:b.match("}")&&0<a.nestedParameters&&a.nestedParameters--;0<a.nestedParameters?b.match(/.*?(?={|})/)||b.next():0==a.nestedParameters&&(a.tokenize=e);return"builtin"}function p(b,a){b.match("#=")&&a.nestedComments++;b.match(/.*?(?=(#=|=#))/)||b.skipToEnd();b.match("=#")&&(a.nestedComments--,0==a.nestedComments&&(a.tokenize=e));return"comment"}function w(b,a){var d=!1,c;if(b.match(F))d=!0;else if(c=b.match(/\\u([a-f0-9]{1,4})(?=')/i)){if(c=parseInt(c[1],16),55295>=c||
57344<=c)d=!0,b.next()}else if(c=b.match(/\\U([A-Fa-f0-9]{5,8})(?=')/))c=parseInt(c[1],16),1114111>=c&&(d=!0,b.next());if(d)return a.leavingExpr=!0,a.tokenize=e,"string";b.match(/^[^']+(?=')/)||b.skipToEnd();b.match("'")&&(a.tokenize=e);return"error"}function y(b){'"""'===b.substr(-3)?b='"""':'"'===b.substr(-1)&&(b='"');return function(a,d){if(a.eat("\\"))a.next();else{if(a.match(b))return d.tokenize=e,d.leavingExpr=!0,"string";a.eat(/[`"]/)}a.eatWhile(/[^\\`"]/);return"string"}}var v=g.operators||
h("[<>]: [<>=]= <<=? >>>?=? => -> \\/\\/ [\\\\%*+\\-<>!=\\/^|&\\u00F7\\u22BB]=? \\? \\$ ~ : \\u00D7 \\u2208 \\u2209 \\u220B \\u220C \\u2218 \\u221A \\u221B \\u2229 \\u222A \\u2260 \\u2264 \\u2265 \\u2286 \\u2288 \\u228A \\u22C5 \\b(in|isa)\\b(?!.?\\()".split(" "),""),A=g.delimiters||/^[;,()[\]{}]/,D=g.identifiers||/^[_A-Za-z\u00A1-\u2217\u2219-\uFFFF][\w\u00A1-\u2217\u2219-\uFFFF]*!*/,F=h(["\\\\[0-7]{1,3}","\\\\x[A-Fa-f0-9]{1,2}","\\\\[abefnrtv0%?'\"\\\\]","([^\\u0027\\u005C\\uD800-\\uDFFF]|[\\uD800-\\uDFFF][\\uDC00-\\uDFFF])"],
"'");g="if else elseif while for begin let end do try catch finally return break continue global local const export import importall using function where macro module baremodule struct type mutable immutable quote typealias abstract primitive bitstype".split(" ");var m=["true","false","nothing","NaN","Inf"];f.registerHelper("hintWords","julia",g.concat(m));var q=h("begin function type struct immutable let macro for while quote if else elseif try finally catch do".split(" ")),r=h(["end","else","elseif",
"catch","finally"]),B=h(g),C=h(m),z=/^@[_A-Za-z][\w]*/,u=/^:[_A-Za-z\u00A1-\uFFFF][\w\u00A1-\uFFFF]*!*/,x=/^(`|([_A-Za-z\u00A1-\uFFFF]*"("")?))/;return{startState:function(){return{tokenize:e,scopes:[],lastToken:null,leavingExpr:!1,isDefinition:!1,nestedArrays:0,nestedComments:0,nestedGenerators:0,nestedParameters:0,firstParenPos:-1}},token:function(b,a){var d=a.tokenize(b,a);(b=b.current())&&d&&(a.lastToken=b);return d},indent:function(b,a){var d=0;if("]"===a||")"===a||/^end\b/.test(a)||/^else/.test(a)||
/^catch\b/.test(a)||/^elseif\b/.test(a)||/^finally/.test(a))d=-1;return(b.scopes.length+d)*n.indentUnit},electricInput:/\b(end|else|catch|finally)\b/,blockCommentStart:"#=",blockCommentEnd:"=#",lineComment:"#",closeBrackets:'()[]{}""',fold:"indent"}});f.defineMIME("text/x-julia","julia")});
