'use strict';function copyObj(a,b,d){b||(b={});for(var c in a)!a.hasOwnProperty(c)||!1===d&&b.hasOwnProperty(c)||(b[c]=a[c]);return b}function countColumn(a,b,d,c,e){null==b&&(b=a.search(/[^\s\u00a0]/),-1==b&&(b=a.length));c=c||0;for(e=e||0;;){var g=a.indexOf("\t",c);if(0>g||g>=b)return e+(b-c);e+=g-c;e+=d-e%d;c=g+1}}function nothing(){}function createObj(a,b){Object.create?a=Object.create(a):(nothing.prototype=a,a=new nothing);b&&copyObj(b,a);return a}
var StringStream=function(a,b,d){this.pos=this.start=0;this.string=a;this.tabSize=b||8;this.lineStart=this.lastColumnPos=this.lastColumnValue=0;this.lineOracle=d};StringStream.prototype.eol=function(){return this.pos>=this.string.length};StringStream.prototype.sol=function(){return this.pos==this.lineStart};StringStream.prototype.peek=function(){return this.string.charAt(this.pos)||void 0};StringStream.prototype.next=function(){if(this.pos<this.string.length)return this.string.charAt(this.pos++)};
StringStream.prototype.eat=function(a){var b=this.string.charAt(this.pos);if("string"==typeof a?b==a:b&&(a.test?a.test(b):a(b)))return++this.pos,b};StringStream.prototype.eatWhile=function(a){for(var b=this.pos;this.eat(a););return this.pos>b};StringStream.prototype.eatSpace=function(){for(var a=this.pos;/[\s\u00a0]/.test(this.string.charAt(this.pos));)++this.pos;return this.pos>a};StringStream.prototype.skipToEnd=function(){this.pos=this.string.length};
StringStream.prototype.skipTo=function(a){a=this.string.indexOf(a,this.pos);if(-1<a)return this.pos=a,!0};StringStream.prototype.backUp=function(a){this.pos-=a};StringStream.prototype.column=function(){this.lastColumnPos<this.start&&(this.lastColumnValue=countColumn(this.string,this.start,this.tabSize,this.lastColumnPos,this.lastColumnValue),this.lastColumnPos=this.start);return this.lastColumnValue-(this.lineStart?countColumn(this.string,this.lineStart,this.tabSize):0)};
StringStream.prototype.indentation=function(){return countColumn(this.string,null,this.tabSize)-(this.lineStart?countColumn(this.string,this.lineStart,this.tabSize):0)};StringStream.prototype.match=function(a,b,d){if("string"==typeof a){var c=function(a){return d?a.toLowerCase():a},e=this.string.substr(this.pos,a.length);if(c(e)==c(a))return!1!==b&&(this.pos+=a.length),!0}else{if((a=this.string.slice(this.pos).match(a))&&0<a.index)return null;a&&!1!==b&&(this.pos+=a[0].length);return a}};
StringStream.prototype.current=function(){return this.string.slice(this.start,this.pos)};StringStream.prototype.hideFirstChars=function(a,b){this.lineStart+=a;try{return b()}finally{this.lineStart-=a}};StringStream.prototype.lookAhead=function(a){var b=this.lineOracle;return b&&b.lookAhead(a)};StringStream.prototype.baseToken=function(){var a=this.lineOracle;return a&&a.baseToken(this.pos)};var modes={},mimeModes={};
function defineMode(a,b){2<arguments.length&&(b.dependencies=Array.prototype.slice.call(arguments,2));modes[a]=b}function defineMIME(a,b){mimeModes[a]=b}
function resolveMode(a){if("string"==typeof a&&mimeModes.hasOwnProperty(a))a=mimeModes[a];else if(a&&"string"==typeof a.name&&mimeModes.hasOwnProperty(a.name)){var b=mimeModes[a.name];"string"==typeof b&&(b={name:b});a=createObj(b,a);a.name=b.name}else{if("string"==typeof a&&/^[\w\-]+\/[\w\-]+\+xml$/.test(a))return resolveMode("application/xml");if("string"==typeof a&&/^[\w\-]+\/[\w\-]+\+json$/.test(a))return resolveMode("application/json")}return"string"==typeof a?{name:a}:a||{name:"null"}}
function getMode(a,b){b=resolveMode(b);var d=modes[b.name];if(!d)return getMode(a,"text/plain");a=d(a,b);if(modeExtensions.hasOwnProperty(b.name)){d=modeExtensions[b.name];for(var c in d)d.hasOwnProperty(c)&&(a.hasOwnProperty(c)&&(a["_"+c]=a[c]),a[c]=d[c])}a.name=b.name;b.helperType&&(a.helperType=b.helperType);if(b.modeProps)for(var e in b.modeProps)a[e]=b.modeProps[e];return a}var modeExtensions={};
function extendMode(a,b){a=modeExtensions.hasOwnProperty(a)?modeExtensions[a]:modeExtensions[a]={};copyObj(b,a)}function copyState(a,b){if(!0===b)return b;if(a.copyState)return a.copyState(b);a={};for(var d in b){var c=b[d];c instanceof Array&&(c=c.concat([]));a[d]=c}return a}function innerMode(a,b){for(var d;a.innerMode;){d=a.innerMode(b);if(!d||d.mode==a)break;b=d.state;a=d.mode}return d||{mode:a,state:b}}function startState(a,b,d){return a.startState?a.startState(b,d):!0}
var modeMethods={__proto__:null,modes:modes,mimeModes:mimeModes,defineMode:defineMode,defineMIME:defineMIME,resolveMode:resolveMode,getMode:getMode,modeExtensions:modeExtensions,extendMode:extendMode,copyState:copyState,innerMode:innerMode,startState:startState};exports.StringStream=StringStream;exports.countColumn=countColumn;for(var exported in modeMethods)exports[exported]=modeMethods[exported];require.cache[require.resolve("../../lib/codemirror")]=require.cache[require.resolve("./runmode.node")];
require.cache[require.resolve("../../addon/runmode/runmode")]=require.cache[require.resolve("./runmode.node")];exports.defineMode("null",function(){return{token:function(a){return a.skipToEnd()}}});exports.defineMIME("text/plain","null");exports.registerHelper=exports.registerGlobalHelper=Math.min;exports.splitLines=function(a){return a.split(/\r?\n|\r/)};exports.defaults={indentUnit:2};
(function(a){"object"==typeof exports&&"object"==typeof module?a(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],a):a(CodeMirror)})(function(a){a.runMode=function(b,d,c,e){d=a.getMode(a.defaults,d);var g=e&&e.tabSize||a.defaults.tabSize;if(c.appendChild){var n=/MSIE \d/.test(navigator.userAgent)&&(null==document.documentMode||9>document.documentMode),l=c,k=0;l.innerHTML="";c=function(a,b){if("\n"==a)l.appendChild(document.createTextNode(n?"\r":
a)),k=0;else{for(var d="",c=0;;){var e=a.indexOf("\t",c);if(-1==e){d+=a.slice(c);k+=a.length-c;break}else{k+=e-c;d+=a.slice(c,e);c=g-k%g;k+=c;for(var f=0;f<c;++f)d+=" ";c=e+1}}b?(a=l.appendChild(document.createElement("span")),a.className="cm-"+b.replace(/ +/g," cm-"),a.appendChild(document.createTextNode(d))):l.appendChild(document.createTextNode(d))}}}var m=a.splitLines(b);b=e&&e.state||a.startState(d);var h=0;for(e=m.length;h<e;++h){h&&c("\n");var f=new a.StringStream(m[h],null,{lookAhead:function(a){return m[h+
a]},baseToken:function(){}});for(!f.string&&d.blankLine&&d.blankLine(b);!f.eol();){var p=d.token(f,b);c(f.current(),p,h,f.start,b);f.start=f.pos}}}});
