'use strict';function splitLines(a){return a.split(/\r\n?|\n/)}var countColumn=function(a,b,d,e,c){null==b&&(b=a.search(/[^\s\u00a0]/),-1==b&&(b=a.length));e=e||0;for(c=c||0;;){var g=a.indexOf("\t",e);if(0>g||g>=b)return c+(b-e);c+=g-e;c+=d-c%d;e=g+1}};function StringStream(a,b){this.pos=this.start=0;this.string=a;this.tabSize=b||8;this.lineStart=this.lastColumnPos=this.lastColumnValue=0}
StringStream.prototype={eol:function(){return this.pos>=this.string.length},sol:function(){return this.pos==this.lineStart},peek:function(){return this.string.charAt(this.pos)||void 0},next:function(){if(this.pos<this.string.length)return this.string.charAt(this.pos++)},eat:function(a){var b=this.string.charAt(this.pos);if("string"==typeof a?b==a:b&&(a.test?a.test(b):a(b)))return++this.pos,b},eatWhile:function(a){for(var b=this.pos;this.eat(a););return this.pos>b},eatSpace:function(){for(var a=this.pos;/[\s\u00a0]/.test(this.string.charAt(this.pos));)++this.pos;
return this.pos>a},skipToEnd:function(){this.pos=this.string.length},skipTo:function(a){a=this.string.indexOf(a,this.pos);if(-1<a)return this.pos=a,!0},backUp:function(a){this.pos-=a},column:function(){this.lastColumnPos<this.start&&(this.lastColumnValue=countColumn(this.string,this.start,this.tabSize,this.lastColumnPos,this.lastColumnValue),this.lastColumnPos=this.start);return this.lastColumnValue-(this.lineStart?countColumn(this.string,this.lineStart,this.tabSize):0)},indentation:function(){return countColumn(this.string,
null,this.tabSize)-(this.lineStart?countColumn(this.string,this.lineStart,this.tabSize):0)},match:function(a,b,d){if("string"==typeof a){var e=function(a){return d?a.toLowerCase():a},c=this.string.substr(this.pos,a.length);if(e(c)==e(a))return!1!==b&&(this.pos+=a.length),!0}else{if((a=this.string.slice(this.pos).match(a))&&0<a.index)return null;a&&!1!==b&&(this.pos+=a[0].length);return a}},current:function(){return this.string.slice(this.start,this.pos)},hideFirstChars:function(a,b){this.lineStart+=
a;try{return b()}finally{this.lineStart-=a}}};exports.StringStream=StringStream;exports.startState=function(a,b,d){return a.startState?a.startState(b,d):!0};var modes=exports.modes={},mimeModes=exports.mimeModes={};exports.defineMode=function(a,b){2<arguments.length&&(b.dependencies=Array.prototype.slice.call(arguments,2));modes[a]=b};exports.defineMIME=function(a,b){mimeModes[a]=b};exports.defineMode("null",function(){return{token:function(a){a.skipToEnd()}}});exports.defineMIME("text/plain","null");
exports.resolveMode=function(a){"string"==typeof a&&mimeModes.hasOwnProperty(a)?a=mimeModes[a]:a&&"string"==typeof a.name&&mimeModes.hasOwnProperty(a.name)&&(a=mimeModes[a.name]);return"string"==typeof a?{name:a}:a||{name:"null"}};function copyObj(a,b,d){b||(b={});for(var e in a)!a.hasOwnProperty(e)||!1===d&&b.hasOwnProperty(e)||(b[e]=a[e]);return b}var modeExtensions=exports.modeExtensions={};
exports.extendMode=function(a,b){var d=modeExtensions.hasOwnProperty(a)?modeExtensions[a]:modeExtensions[a]={};copyObj(b,d)};
exports.getMode=function(a,b){b=exports.resolveMode(b);var d=modes[b.name];if(!d)return exports.getMode(a,"text/plain");d=d(a,b);if(modeExtensions.hasOwnProperty(b.name)){var e=modeExtensions[b.name],c;for(c in e)e.hasOwnProperty(c)&&(d.hasOwnProperty(c)&&(d["_"+c]=d[c]),d[c]=e[c])}d.name=b.name;b.helperType&&(d.helperType=b.helperType);if(b.modeProps)for(c in b.modeProps)d[c]=b.modeProps[c];return d};exports.registerHelper=exports.registerGlobalHelper=Math.min;
exports.runMode=function(a,b,d,e){b=exports.getMode({indentUnit:2},b);a=splitLines(a);e=e&&e.state||exports.startState(b);for(var c=0,g=a.length;c<g;++c){c&&d("\n");var f=new exports.StringStream(a[c]);for(!f.string&&b.blankLine&&b.blankLine(e);!f.eol();){var h=b.token(f,e);d(f.current(),h,c,f.start,e);f.start=f.pos}}};require.cache[require.resolve("../../lib/codemirror")]=require.cache[require.resolve("./runmode.node")];require.cache[require.resolve("../../addon/runmode/runmode")]=require.cache[require.resolve("./runmode.node")];
