'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.ENABLE_UNHANDLED_REJECTION_POLYFILL=!0;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,e){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,e):$jscomp.polyfillUnisolated(a,c,b,e))};
$jscomp.polyfillUnisolated=function(a,c,b,e){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];if(!(f in b))return;b=b[f]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,e){var f=a.split(".");a=1===f.length;e=f[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<f.length-1;q++){var d=f[q];if(!(d in e))return;e=e[d]}f=f[f.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?e[f]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:c}):c!==b&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(e,f,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(c){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var e="";c;)if(c&1&&(e+=b),c>>>=1)b+=b;return e}},"es6","es3");
(function(a){"object"==typeof exports&&"object"==typeof module?a(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],a):a(CodeMirror)})(function(a){function c(d){if(d.getOption("disableInput"))return a.Pass;for(var l=d.listSelections(),k,w=[],t=0;t<l.length;t++){var m=l[t].head;if(!/\bcomment\b/.test(d.getTokenTypeAt(m)))return a.Pass;var p=d.getModeAt(m);if(!k)k=p;else if(k!=p)return a.Pass;var g=null,h,u=k.blockCommentStart;p=k.lineComment;if(u&&
k.blockCommentContinue){var n=d.getLine(m.line);var v=n.lastIndexOf(k.blockCommentEnd,m.ch-k.blockCommentEnd.length);if(!(-1!=v&&v==m.ch-k.blockCommentEnd.length||p&&-1<(h=n.lastIndexOf(p,m.ch-1))&&/\bcomment\b/.test(d.getTokenTypeAt({line:m.line,ch:h+1}))))if(m.ch>=u.length&&-1<(h=n.lastIndexOf(u,m.ch-u.length))&&h>v)if(b(0,n)>=h)g=n.slice(0,h);else{g=d.options.tabSize;var x;h=a.countColumn(n,h,g);g=d.options.indentWithTabs?q.call("\t",x=Math.floor(h/g))+q.call(" ",h-g*x):q.call(" ",h)}else-1<(h=
n.indexOf(k.blockCommentContinue))&&h<=m.ch&&h<=b(0,n)&&(g=n.slice(0,h));null!=g&&(g+=k.blockCommentContinue)}null==g&&p&&e(d)&&((null==n&&(n=d.getLine(m.line)),h=n.indexOf(p),m.ch||h)?-1<h&&b(0,n)>=h&&(g=-1<b(m.ch,n),g||(m=d.getLine(m.line+1)||"",g=m.indexOf(p),g=-1<g&&b(0,m)>=g||null),g&&(g=n.slice(0,h)+p+n.slice(h+p.length).match(/^\s*/)[0])):g="");if(null==g)return a.Pass;w[t]="\n"+g}d.operation(function(){for(var r=l.length-1;0<=r;r--)d.replaceRange(w[r],l[r].from(),l[r].to(),"+insert")})}function b(d,
l){f.lastIndex=d;return(d=f.exec(l))?d.index:-1}function e(d){return(d=d.getOption("continueComments"))&&"object"==typeof d?!1!==d.continueLineComment:!0}var f=/\S/g,q=String.prototype.repeat||function(d){return Array(d+1).join(this)};a.defineOption("continueComments",null,function(d,l,k){k&&k!=a.Init&&d.removeKeyMap("continueComment");l&&(k="Enter","string"==typeof l?k=l:"object"==typeof l&&l.key&&(k=l.key),l={name:"continueComment"},l[k]=c,d.addKeyMap(l))})});
