'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,d){a instanceof String&&(a=String(a));for(var f=a.length,e=0;e<f;e++){var g=a[e];if(c.call(d,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var d=$jscomp.propertyToPolyfillSymbol[c];if(null==d)return a[c];d=a[d];return void 0!==d?d:a[c]};
$jscomp.polyfill=function(a,c,d,f){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,d,f):$jscomp.polyfillUnisolated(a,c,d,f))};$jscomp.polyfillUnisolated=function(a,c,d,f){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in d))return;d=d[e]}a=a[a.length-1];f=d[a];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,d,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var l=e[g];if(!(l in f))return;f=f[l]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?f[e]:null;c=c(d);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(f,e,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");
(function(a){"object"==typeof exports&&"object"==typeof module?a(require("../../lib/codemirror"),require("./foldcode")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","./foldcode"],a):a(CodeMirror)})(function(a){function c(b){this.options=b;this.from=this.to=0}function d(b,h){b=b.findMarks(p(h,0),p(h+1,0));for(var a=0;a<b.length;++a)if(b[a].__isFold){var d=b[a].find(-1);if(d&&d.line===h)return b[a]}}function f(b){if("string"==typeof b){var a=document.createElement("div");a.className=
b+" CodeMirror-guttermarker-subtle";return a}return b.cloneNode(!0)}function e(a,h,c){var b=a.state.foldGutter.options,e=h-1,r=a.foldOption(b,"minFoldSize"),g=a.foldOption(b,"rangeFinder"),l="string"==typeof b.indicatorFolded&&new RegExp("(^|\\s)"+b.indicatorFolded+"(?:$|\\s)\\s*"),n="string"==typeof b.indicatorOpen&&new RegExp("(^|\\s)"+b.indicatorOpen+"(?:$|\\s)\\s*");a.eachLine(h,c,function(h){++e;var c=null,m=h.gutterMarkers;m&&(m=m[b.gutter]);if(d(a,e)){if(l&&m&&l.test(m.className))return;c=
f(b.indicatorFolded)}else{var k=p(e,0);if((k=g&&g(a,k))&&k.to.line-k.from.line>=r){if(n&&m&&n.test(m.className))return;c=f(b.indicatorOpen)}}(c||m)&&a.setGutterMarker(h,b.gutter,c)})}function g(a){var b=a.getViewport(),c=a.state.foldGutter;c&&(a.operation(function(){e(a,b.from,b.to)}),c.from=b.from,c.to=b.to)}function l(a,h,c){var b=a.state.foldGutter;b&&(b=b.options,c==b.gutter&&((c=d(a,h))?c.clear():a.foldCode(p(h,0),b)))}function n(a){var b=a.state.foldGutter;if(b){var c=b.options;b.from=b.to=
0;clearTimeout(b.changeUpdate);b.changeUpdate=setTimeout(function(){g(a)},c.foldOnChangeTimeSpan||600)}}function q(a){var b=a.state.foldGutter;if(b){var c=b.options;clearTimeout(b.changeUpdate);b.changeUpdate=setTimeout(function(){var c=a.getViewport();b.from==b.to||20<c.from-b.to||20<b.from-c.to?g(a):a.operation(function(){c.from<b.from&&(e(a,c.from,b.from),b.from=c.from);c.to>b.to&&(e(a,b.to,c.to),b.to=c.to)})},c.updateViewportTimeSpan||400)}}function k(a,c){var b=a.state.foldGutter;b&&(c=c.line,
c>=b.from&&c<b.to&&e(a,c,c+1))}a.defineOption("foldGutter",!1,function(b,d,e){e&&e!=a.Init&&(b.clearGutter(b.state.foldGutter.options.gutter),b.state.foldGutter=null,b.off("gutterClick",l),b.off("changes",n),b.off("viewportChange",q),b.off("fold",k),b.off("unfold",k),b.off("swapDoc",n));d&&(e=b.state,!0===d&&(d={}),null==d.gutter&&(d.gutter="CodeMirror-foldgutter"),null==d.indicatorOpen&&(d.indicatorOpen="CodeMirror-foldgutter-open"),null==d.indicatorFolded&&(d.indicatorFolded="CodeMirror-foldgutter-folded"),
e.foldGutter=new c(d),g(b),b.on("gutterClick",l),b.on("changes",n),b.on("viewportChange",q),b.on("fold",k),b.on("unfold",k),b.on("swapDoc",n))});var p=a.Pos});
