'use strict';(function(h){"object"==typeof exports&&"object"==typeof module?h(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],h):h(CodeMirror)})(function(h){function A(a,b){this.cm=a;this.options=b;this.widget=null;this.tick=this.debounce=0;this.startPos=this.cm.getCursor("start");this.startLen=this.cm.getLine(this.startPos.line).length-this.cm.getSelection().length;var c=this;a.on("cursorActivity",this.activityFunc=function(){c.cursorActivity()})}
function J(a,b){function c(r,g){var p="string"!=typeof g?function(k){return g(k,b)}:d.hasOwnProperty(g)?d[g]:g;n[r]=p}var d={Up:function(){b.moveFocus(-1)},Down:function(){b.moveFocus(1)},PageUp:function(){b.moveFocus(-b.menuSize()+1,!0)},PageDown:function(){b.moveFocus(b.menuSize()-1,!0)},Home:function(){b.setFocus(0)},End:function(){b.setFocus(b.length-1)},Enter:b.pick,Tab:b.pick,Esc:b.close};/Mac/.test(navigator.platform)&&(d["Ctrl-P"]=function(){b.moveFocus(-1)},d["Ctrl-N"]=function(){b.moveFocus(1)});
var e=a.options.customKeys,n=e?{}:d;if(e)for(var f in e)e.hasOwnProperty(f)&&c(f,e[f]);if(a=a.options.extraKeys)for(f in a)a.hasOwnProperty(f)&&c(f,a[f]);return n}function B(a,b){for(;b&&b!=a;){if("LI"===b.nodeName.toUpperCase()&&b.parentNode==a)return b;b=b.parentNode}}function C(a,b){this.completion=a;this.data=b;this.picked=!1;var c=this,d=a.cm,e=d.getInputField().ownerDocument,n=e.defaultView||e.parentWindow,f=this.hints=e.createElement("ul");f.className="CodeMirror-hints "+a.cm.options.theme;
this.selectedHint=b.selectedHint||0;for(var r=b.list,g=0;g<r.length;++g){var p=f.appendChild(e.createElement("li")),k=r[g],l="CodeMirror-hint"+(g!=this.selectedHint?"":" CodeMirror-hint-active");null!=k.className&&(l=k.className+" "+l);p.className=l;k.render?k.render(p,b,k):p.appendChild(e.createTextNode(k.displayText||("string"==typeof k?k:k.text)));p.hintId=g}l=a.options.container||e.body;g=d.cursorCoords(a.options.alignWithWord?b.from:null);var u=g.left,v=g.bottom,D=!0,q=p=0;if(l!==e.body){k=-1!==
["absolute","relative","fixed"].indexOf(n.getComputedStyle(l).position)?l:l.offsetParent;var w=k.getBoundingClientRect();q=e.body.getBoundingClientRect();p=w.left-q.left-k.scrollLeft;q=w.top-q.top-k.scrollTop}f.style.left=u-p+"px";f.style.top=v-q+"px";k=n.innerWidth||Math.max(e.body.offsetWidth,e.documentElement.offsetWidth);var y=n.innerHeight||Math.max(e.body.offsetHeight,e.documentElement.offsetHeight);l.appendChild(f);l=f.getBoundingClientRect();var t=l.bottom-y;w=f.scrollHeight>f.clientHeight+
1;var E=d.getScrollInfo();0<t&&(t=l.bottom-l.top,0<g.top-(g.bottom-l.top)-t?(f.style.top=(v=g.top-t-q)+"px",D=!1):t>y&&(f.style.height=y-5+"px",f.style.top=(v=g.bottom-l.top-q)+"px",q=d.getCursor(),b.from.ch!=q.ch&&(g=d.cursorCoords(q),f.style.left=(u=g.left-p)+"px",l=f.getBoundingClientRect())));q=l.right-k;0<q&&(l.right-l.left>k&&(f.style.width=k-5+"px",q-=l.right-l.left-k),f.style.left=(u=g.left-q-p)+"px");if(w)for(g=f.firstChild;g;g=g.nextSibling)g.style.paddingRight=d.display.nativeBarWidth+
"px";d.addKeyMap(this.keyMap=J(a,{moveFocus:function(m,x){c.changeActive(c.selectedHint+m,x)},setFocus:function(m){c.changeActive(m)},menuSize:function(){return c.screenAmount()},length:r.length,close:function(){a.close()},pick:function(){c.pick()},data:b}));if(a.options.closeOnUnfocus){var F;d.on("blur",this.onBlur=function(){F=setTimeout(function(){a.close()},100)});d.on("focus",this.onFocus=function(){clearTimeout(F)})}d.on("scroll",this.onScroll=function(){var m=d.getScrollInfo(),x=d.getWrapperElement().getBoundingClientRect(),
G=v+E.top-m.top,z=G-(n.pageYOffset||(e.documentElement||e.body).scrollTop);D||(z+=f.offsetHeight);if(z<=x.top||z>=x.bottom)return a.close();f.style.top=G+"px";f.style.left=u+E.left-m.left+"px"});h.on(f,"dblclick",function(m){(m=B(f,m.target||m.srcElement))&&null!=m.hintId&&(c.changeActive(m.hintId),c.pick())});h.on(f,"click",function(m){(m=B(f,m.target||m.srcElement))&&null!=m.hintId&&(c.changeActive(m.hintId),a.options.completeOnSingleClick&&c.pick())});h.on(f,"mousedown",function(){setTimeout(function(){d.focus()},
20)});this.scrollToActive();h.signal(b,"select",r[this.selectedHint],f.childNodes[this.selectedHint]);return!0}function K(a,b){if(!a.somethingSelected())return b;a=[];for(var c=0;c<b.length;c++)b[c].supportsSelection&&a.push(b[c]);return a}function H(a,b,c,d){a.async?a(b,d,c):(a=a(b,c))&&a.then?a.then(d):d(a)}h.showHint=function(a,b,c){if(!b)return a.showHint(c);c&&c.async&&(b.async=!0);b={hint:b};if(c)for(var d in c)b[d]=c[d];return a.showHint(b)};h.defineExtension("showHint",function(a){var b=this.getCursor("start"),
c=this.options.hintOptions,d={},e;for(e in I)d[e]=I[e];if(c)for(e in c)void 0!==c[e]&&(d[e]=c[e]);if(a)for(e in a)void 0!==a[e]&&(d[e]=a[e]);d.hint.resolve&&(d.hint=d.hint.resolve(this,b));a=d;b=this.listSelections();if(!(1<b.length)){if(this.somethingSelected()){if(!a.hint.supportsSelection)return;for(e=0;e<b.length;e++)if(b[e].head.line!=b[e].anchor.line)return}this.state.completionActive&&this.state.completionActive.close();b=this.state.completionActive=new A(this,a);b.options.hint&&(h.signal(this,
"startCompletion",this),b.update(!0))}});h.defineExtension("closeHint",function(){this.state.completionActive&&this.state.completionActive.close()});var L=window.requestAnimationFrame||function(a){return setTimeout(a,1E3/60)},M=window.cancelAnimationFrame||clearTimeout;A.prototype={close:function(){this.active()&&(this.tick=this.cm.state.completionActive=null,this.cm.off("cursorActivity",this.activityFunc),this.widget&&this.data&&h.signal(this.data,"close"),this.widget&&this.widget.close(),h.signal(this.cm,
"endCompletion",this.cm))},active:function(){return this.cm.state.completionActive==this},pick:function(a,b){var c=a.list[b],d=this;this.cm.operation(function(){c.hint?c.hint(d.cm,a,c):d.cm.replaceRange("string"==typeof c?c:c.text,c.from||a.from,c.to||a.to,"complete");h.signal(a,"pick",c);d.cm.scrollIntoView()});this.close()},cursorActivity:function(){this.debounce&&(M(this.debounce),this.debounce=0);var a=this.startPos;this.data&&(a=this.data.from);var b=this.cm.getCursor(),c=this.cm.getLine(b.line);
if(b.line!=this.startPos.line||c.length-b.ch!=this.startLen-this.startPos.ch||b.ch<a.ch||this.cm.somethingSelected()||!b.ch||this.options.closeCharacters.test(c.charAt(b.ch-1)))this.close();else{var d=this;this.debounce=L(function(){d.update()});this.widget&&this.widget.disable()}},update:function(a){if(null!=this.tick){var b=this,c=++this.tick;H(this.options.hint,this.cm,this.options,function(d){b.tick==c&&b.finishUpdate(d,a)})}},finishUpdate:function(a,b){this.data&&h.signal(this.data,"update");
b=this.widget&&this.widget.picked||b&&this.options.completeSingle;this.widget&&this.widget.close();(this.data=a)&&a.list.length&&(b&&1==a.list.length?this.pick(a,0):(this.widget=new C(this,a),h.signal(a,"shown")))}};C.prototype={close:function(){if(this.completion.widget==this){this.completion.widget=null;this.hints.parentNode.removeChild(this.hints);this.completion.cm.removeKeyMap(this.keyMap);var a=this.completion.cm;this.completion.options.closeOnUnfocus&&(a.off("blur",this.onBlur),a.off("focus",
this.onFocus));a.off("scroll",this.onScroll)}},disable:function(){this.completion.cm.removeKeyMap(this.keyMap);var a=this;this.keyMap={Enter:function(){a.picked=!0}};this.completion.cm.addKeyMap(this.keyMap)},pick:function(){this.completion.pick(this.data,this.selectedHint)},changeActive:function(a,b){a>=this.data.list.length?a=b?this.data.list.length-1:0:0>a&&(a=b?0:this.data.list.length-1);if(this.selectedHint!=a){if(b=this.hints.childNodes[this.selectedHint])b.className=b.className.replace(" CodeMirror-hint-active",
"");b=this.hints.childNodes[this.selectedHint=a];b.className+=" CodeMirror-hint-active";this.scrollToActive();h.signal(this.data,"select",this.data.list[this.selectedHint],b)}},scrollToActive:function(){var a=this.completion.options.scrollMargin||0,b=this.hints.childNodes[Math.max(0,this.selectedHint-a)];a=this.hints.childNodes[Math.min(this.data.list.length-1,this.selectedHint+a)];var c=this.hints.firstChild;b.offsetTop<this.hints.scrollTop?this.hints.scrollTop=b.offsetTop-c.offsetTop:a.offsetTop+
a.offsetHeight>this.hints.scrollTop+this.hints.clientHeight&&(this.hints.scrollTop=a.offsetTop+a.offsetHeight-this.hints.clientHeight+c.offsetTop)},screenAmount:function(){return Math.floor(this.hints.clientHeight/this.hints.firstChild.offsetHeight)||1}};h.registerHelper("hint","auto",{resolve:function(a,b){var c=a.getHelpers(b,"hint"),d;return c.length?(a=function(e,n,f){function r(p){if(p==g.length)return n(null);H(g[p],e,f,function(k){k&&0<k.list.length?n(k):r(p+1)})}var g=K(e,c);r(0)},a.async=
!0,a.supportsSelection=!0,a):(d=a.getHelper(a.getCursor(),"hintWords"))?function(e){return h.hint.fromList(e,{words:d})}:h.hint.anyword?function(e,n){return h.hint.anyword(e,n)}:function(){}}});h.registerHelper("hint","fromList",function(a,b){var c=a.getCursor(),d=a.getTokenAt(c);a=h.Pos(c.line,d.start);d.start<c.ch&&/\w/.test(d.string.charAt(c.ch-d.start-1))?d=d.string.substr(0,c.ch-d.start):(d="",a=c);for(var e=[],n=0;n<b.words.length;n++){var f=b.words[n];f.slice(0,d.length)==d&&e.push(f)}if(e.length)return{list:e,
from:a,to:c}});h.commands.autocomplete=h.showHint;var I={hint:h.hint.auto,completeSingle:!0,alignWithWord:!0,closeCharacters:/[\s()\[\]{};:>,]/,closeOnUnfocus:!0,completeOnSingleClick:!0,container:null,customKeys:null,extraKeys:null};h.defineOption("hintOptions",null)});
