'use strict';(function(m){"object"==typeof exports&&"object"==typeof module?m(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],m):m(CodeMirror)})(function(m){function t(n){return new RegExp("^(("+n.join(")|(")+"))\\b")}function k(n){return n.scopes[n.scopes.length-1]}var F=t(["and","or","not","is"]),x="as assert break class continue def del elif else except finally for from global if import lambda pass raise return try while with yield in".split(" "),
y="abs all any bin bool bytearray callable chr classmethod compile complex delattr dict dir divmod enumerate eval filter float format frozenset getattr globals hasattr hash help hex id input int isinstance issubclass iter len list locals map max memoryview min next object oct open ord pow property range repr reversed round set setattr slice sorted staticmethod str sum super tuple type vars zip __import__ NotImplemented Ellipsis __debug__".split(" ");m.registerHelper("hintWords","python",x.concat(y));
m.defineMode("python",function(n,g){function z(a,b){var f=a.sol()&&"\\"!=b.lastToken;f&&(b.indent=a.indentation());if(f&&"py"==k(b).type){f=k(b).offset;if(a.eatSpace()){var c=a.indentation();c>f?A(b):c<f&&B(a,b)&&"#"!=a.peek()&&(b.errorToken=!0);return null}c=u(a,b);0<f&&B(a,b)&&(c+=" error");return c}return u(a,b)}function u(a,b,f){if(a.eatSpace())return null;if(!f&&a.match(/^#.*/))return"comment";if(a.match(/^[0-9\.]/,!1)){var c=!1;a.match(/^[\d_]*\.\d+(e[\+\-]?\d+)?/i)&&(c=!0);a.match(/^[\d_]+\.\d*/)&&
(c=!0);a.match(/^\.\d+/)&&(c=!0);if(c)return a.eat(/J/i),"number";c=!1;a.match(/^0x[0-9a-f_]+/i)&&(c=!0);a.match(/^0b[01_]+/i)&&(c=!0);a.match(/^0o[0-7_]+/i)&&(c=!0);a.match(/^[1-9][\d_]*(e[\+\-]?[\d_]+)?/)&&(a.eat(/J/i),c=!0);a.match(/^0(?![\dx])/i)&&(c=!0);if(c)return a.eat(/L/i),"number"}if(a.match(C))return-1===a.current().toLowerCase().indexOf("f")?b.tokenize=G(a.current(),b.tokenize):b.tokenize=H(a.current(),b.tokenize),b.tokenize(a,b);for(c=0;c<q.length;c++)if(a.match(q[c]))return"operator";
if(a.match(I))return"punctuation";if("."==b.lastToken&&a.match(r))return"property";if(a.match(J)||a.match(F))return"keyword";if(a.match(K))return"builtin";if(a.match(/^(self|cls)\b/))return"variable-2";if(a.match(r))return"def"==b.lastToken||"class"==b.lastToken?"def":"variable";a.next();return f?null:"error"}function H(a,b){function f(d){return function(l,v){var D=u(l,v,!0);"punctuation"==D&&("{"==l.current()?v.tokenize=f(d+1):"}"==l.current()&&(v.tokenize=1<d?f(d-1):c));return D}}function c(d,l){for(;!d.eol();)if(d.eatWhile(/[^'"\{\}\\]/),
d.eat("\\")){if(d.next(),e&&d.eol())return"string"}else{if(d.match(a))return l.tokenize=b,"string";if(d.match("{{"))return"string";if(d.match("{",!1))return l.tokenize=f(0),d.current()?"string":l.tokenize(d,l);if(d.match("}}"))return"string";if(d.match("}"))return"error";d.eat(/['"]/)}if(e){if(g.singleLineStringErrors)return"error";l.tokenize=b}return"string"}for(;0<="rubf".indexOf(a.charAt(0).toLowerCase());)a=a.substr(1);var e=1==a.length;c.isString=!0;return c}function G(a,b){function f(e,d){for(;!e.eol();)if(e.eatWhile(/[^'"\\]/),
e.eat("\\")){if(e.next(),c&&e.eol())return"string"}else{if(e.match(a))return d.tokenize=b,"string";e.eat(/['"]/)}if(c){if(g.singleLineStringErrors)return"error";d.tokenize=b}return"string"}for(;0<="rubf".indexOf(a.charAt(0).toLowerCase());)a=a.substr(1);var c=1==a.length;f.isString=!0;return f}function A(a){for(;"py"!=k(a).type;)a.scopes.pop();a.scopes.push({offset:k(a).offset+n.indentUnit,type:"py",align:null})}function B(a,b){for(a=a.indentation();1<b.scopes.length&&k(b).offset>a;){if("py"!=k(b).type)return!0;
b.scopes.pop()}return k(b).offset!=a}for(var I=g.delimiters||g.singleDelimiters||/^[\(\)\[\]\{\}@,:`=;\.\\]/,q=[g.singleOperators,g.doubleOperators,g.doubleDelimiters,g.tripleDelimiters,g.operators||/^([-+*/%\/&|^]=?|[<>=]+|\/\/=?|\*\*=?|!=|[~!@]|\.\.\.)/],h=0;h<q.length;h++)q[h]||q.splice(h--,1);var w=g.hangingIndent||n.indentUnit;h=x;var p=y;void 0!=g.extra_keywords&&(h=h.concat(g.extra_keywords));void 0!=g.extra_builtins&&(p=p.concat(g.extra_builtins));var E=!(g.version&&3>Number(g.version));if(E){var r=
g.identifiers||/^[_A-Za-z\u00A1-\uFFFF][_A-Za-z0-9\u00A1-\uFFFF]*/;h=h.concat("nonlocal False True None async await".split(" "));p=p.concat(["ascii","bytes","exec","print"]);var C=/^(([rbuf]|(br)|(fr))?('{3}|"{3}|['"]))/i}else r=g.identifiers||/^[_A-Za-z][_A-Za-z0-9]*/,h=h.concat(["exec","print"]),p=p.concat("apply basestring buffer cmp coerce execfile file intern long raw_input reduce reload unichr unicode xrange False True None".split(" ")),C=/^(([rubf]|(ur)|(br))?('{3}|"{3}|['"]))/i;var J=t(h),
K=t(p);return{startState:function(a){return{tokenize:z,scopes:[{offset:a||0,type:"py",align:null}],indent:a||0,lastToken:null,lambda:!1,dedent:0}},token:function(a,b){var f=b.errorToken;f&&(b.errorToken=!1);a:{a.sol()&&(b.beginningOfLine=!0);var c=b.tokenize(a,b);var e=a.current();if(b.beginningOfLine&&"@"==e)c=a.match(r,!1)?"meta":E?"operator":"error";else{/\S/.test(e)&&(b.beginningOfLine=!1);"variable"!=c&&"builtin"!=c||"meta"!=b.lastToken||(c="meta");if("pass"==e||"return"==e)b.dedent+=1;"lambda"==
e&&(b.lambda=!0);":"!=e||b.lambda||"py"!=k(b).type||A(b);if(1==e.length&&!/string|comment/.test(c)){var d="[({".indexOf(e);if(-1!=d){d="])}".slice(d,d+1);var l=a.match(/^([\s\[\{\(]|#.*)*$/,!1)?null:a.column()+1;b.scopes.push({offset:b.indent+w,type:d,align:l})}d="])}".indexOf(e);if(-1!=d)if(k(b).type==e)b.indent=b.scopes.pop().offset-w;else{c="error";break a}}0<b.dedent&&a.eol()&&"py"==k(b).type&&(1<b.scopes.length&&b.scopes.pop(),--b.dedent)}}c&&"comment"!=c&&(b.lastToken="keyword"==c||"punctuation"==
c?a.current():c);"punctuation"==c&&(c=null);a.eol()&&b.lambda&&(b.lambda=!1);return f?c+" error":c},indent:function(a,b){if(a.tokenize!=z)return a.tokenize.isString?m.Pass:0;a=k(a);b=a.type==b.charAt(0);return null!=a.align?a.align-(b?1:0):a.offset-(b?w:0)},electricInput:/^\s*[\}\]\)]$/,closeBrackets:{triples:"'\""},lineComment:"#",fold:"indent"}});m.defineMIME("text/x-python","python");m.defineMIME("text/x-cython",{name:"python",extra_keywords:"by cdef cimport cpdef ctypedef enum except extern gil include nogil property public readonly struct union DEF IF ELIF ELSE".split(" ")})});
