'use strict';(function(p){"object"==typeof exports&&"object"==typeof module?p(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],p):p(CodeMirror)})(function(p){function ja(p,q,n){return/^(?:operator|sof|keyword c|case|new|export|default|[\[{}\(,;:]|=>)$/.test(q.lastType)||"quasi"==q.lastType&&/\{\s*$/.test(p.string.slice(0,p.pos-(n||0)))}p.defineMode("javascript",function(wa,q){function n(a,c,b){G=a;P=b;return c}function B(a,c){var b=a.next();if('"'==
b||"'"==b)return c.tokenize=xa(b),c.tokenize(a,c);if("."==b&&a.match(/^\d+(?:[eE][+\-]?\d+)?/))return n("number","number");if("."==b&&a.match(".."))return n("spread","meta");if(/[\[\]{}\(\),;\:\.]/.test(b))return n(b);if("="==b&&a.eat(">"))return n("=>","operator");if("0"==b&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if("0"==b&&a.eat(/o/i))return a.eatWhile(/[0-7]/i),n("number","number");if("0"==b&&a.eat(/b/i))return a.eatWhile(/[01]/i),n("number","number");if(/\d/.test(b))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),
n("number","number");if("/"==b){if(a.eat("*"))return c.tokenize=Q,Q(a,c);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");if(ja(a,c,1)){a:for(var f=c=!1;null!=(b=a.next());){if(!c){if("/"==b&&!f)break a;"["==b?f=!0:f&&"]"==b&&(f=!1)}c=!c&&"\\"==b}a.match(/^\b(([gimyu])(?![gimyu]*\2))+\b/);return n("regexp","string-2")}a.eatWhile(R);return n("operator","operator",a.current())}if("`"==b)return c.tokenize=Z,Z(a,c);if("#"==b)return a.skipToEnd(),n("error","error");if(R.test(b))return">"==b&&
c.lexical&&">"==c.lexical.type||a.eatWhile(R),n("operator","operator",a.current());if(aa.test(b))return a.eatWhile(aa),a=a.current(),(b=ka.propertyIsEnumerable(a)&&ka[a])&&"."!=c.lastType?n(b.type,b.style,a):n("variable","variable",a)}function xa(a){return function(c,b){var f=!1,l;if(S&&"@"==c.peek()&&c.match(ya))return b.tokenize=B,n("jsonld-keyword","meta");for(;null!=(l=c.next())&&(l!=a||f);)f=!f&&"\\"==l;f||(b.tokenize=B);return n("string","string")}}function Q(a,c){for(var b=!1,f;f=a.next();){if("/"==
f&&b){c.tokenize=B;break}b="*"==f}return n("comment","comment")}function Z(a,c){for(var b=!1,f;null!=(f=a.next());){if(!b&&("`"==f||"$"==f&&a.eat("{"))){c.tokenize=B;break}b=!b&&"\\"==f}return n("quasi","string-2",a.current())}function ba(a,c){c.fatArrowAt&&(c.fatArrowAt=null);var b=a.string.indexOf("=>",a.start);if(!(0>b)){if(v){var f=/:\s*(?:\w+(?:<[^>]*>|\[\])?|\{[^}]*\})\s*$/.exec(a.string.slice(a.start,b));f&&(b=f.index)}for(var f=0,d=!1,b=b-1;0<=b;--b){var z=a.string.charAt(b),e="([{}])".indexOf(z);
if(0<=e&&3>e){if(!f){++b;break}if(0==--f){"("==z&&(d=!0);break}}else if(3<=e&&6>e)++f;else if(aa.test(z))d=!0;else{if(/["'\/]/.test(z))return;if(d&&!f){++b;break}}}d&&!f&&(c.fatArrowAt=b)}}function la(a,b,d,f,e,z){this.indented=a;this.column=b;this.type=d;this.prev=e;this.info=z;null!=f&&(this.align=f)}function g(){for(var a=arguments.length-1;0<=a;a--)d.cc.push(arguments[a])}function b(){g.apply(null,arguments);return!0}function H(a){function b(b){for(;b;b=b.next)if(b.name==a)return!0;return!1}var l=
d.state;d.marked="def";l.context?b(l.localVars)||(l.localVars={name:a,next:l.localVars}):!b(l.globalVars)&&q.globalVars&&(l.globalVars={name:a,next:l.globalVars})}function I(){d.state.context={prev:d.state.context,vars:d.state.localVars};d.state.localVars=za}function J(){d.state.localVars=d.state.context.vars;d.state.context=d.state.context.prev}function h(a,b){var c=function(){var c=d.state,l=c.indented;if("stat"==c.lexical.type)l=c.lexical.indented;else for(var e=c.lexical;e&&")"==e.type&&e.align;e=
e.prev)l=e.indented;c.lexical=new la(l,d.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}function e(){var a=d.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function k(a){function c(d){return d==a?b():";"==a?g():b(c)}return c}function r(a,c){return"var"==a?b(h("vardef",c.length),ca,k(";"),e):"keyword a"==a?b(h("form"),da,r,e):"keyword b"==a?b(h("form"),r,e):"{"==a?b(h("}"),T,e):";"==a?b():"if"==a?("else"==d.state.lexical.info&&d.state.cc[d.state.cc.length-
1]==e&&d.state.cc.pop()(),b(h("form"),da,r,e,ma)):"function"==a?b(w):"for"==a?b(h("form"),Aa,r,e):"variable"==a?v&&"type"==c?(d.marked="keyword",b(t,k("operator"),t,k(";"))):b(h("stat"),Ba):"switch"==a?b(h("form"),da,k("{"),h("}","switch"),T,e,e):"case"==a?b(m,k(":")):"default"==a?b(k(":")):"catch"==a?b(h("form"),I,k("("),ea,k(")"),r,e,J):"class"==a?b(h("form"),na,e):"export"==a?b(h("stat"),Ca,e):"import"==a?b(h("stat"),Da,e):"module"==a?b(h("form"),x,k("{"),h("}"),T,e,e):"async"==a?b(r):"@"==c?b(m,
r):g(h("stat"),m,k(";"),e)}function m(a){return oa(a,!1)}function u(a){return oa(a,!0)}function da(a){return"("!=a?g():b(h(")"),m,k(")"),e)}function oa(a,c){if(d.state.fatArrowAt==d.stream.start){var l=c?pa:qa;if("("==a)return b(I,h(")"),y(x,")"),e,k("=>"),l,J);if("variable"==a)return g(I,x,k("=>"),l,J)}l=c?K:C;return Ea.hasOwnProperty(a)?b(l):"function"==a?b(w,l):"class"==a?b(h("form"),Fa,e):"keyword c"==a||"async"==a?b(c?Ga:fa):"("==a?b(h(")"),fa,k(")"),e,l):"operator"==a||"spread"==a?b(c?u:m):
"["==a?b(h("]"),Ha,e,l):"{"==a?L(ga,"}",null,l):"quasi"==a?g(U,l):"new"==a?b(Ia(c)):b()}function fa(a){return a.match(/[;\}\)\],]/)?g():g(m)}function Ga(a){return a.match(/[;\}\)\],]/)?g():g(u)}function C(a,c){return","==a?b(m):K(a,c,!1)}function K(a,c,d){var f=0==d?C:K,l=0==d?m:u;if("=>"==a)return b(I,d?pa:qa,J);if("operator"==a)return/\+\+|--/.test(c)?b(f):"?"==c?b(m,k(":"),l):b(l);if("quasi"==a)return g(U,f);if(";"!=a){if("("==a)return L(u,")","call",f);if("."==a)return b(Ja,f);if("["==a)return b(h("]"),
fa,k("]"),e,f)}}function U(a,c){return"quasi"!=a?g():"${"!=c.slice(c.length-2)?b(U):b(m,Ka)}function Ka(a){if("}"==a)return d.marked="string-2",d.state.tokenize=Z,b(U)}function qa(a){ba(d.stream,d.state);return g("{"==a?r:m)}function pa(a){ba(d.stream,d.state);return g("{"==a?r:u)}function Ia(a){return function(c){return"."==c?b(a?La:Ma):g(a?u:m)}}function Ma(a,c){if("target"==c)return d.marked="keyword",b(C)}function La(a,c){if("target"==c)return d.marked="keyword",b(K)}function Ba(a){return":"==
a?b(e,r):g(C,k(";"),e)}function Ja(a){if("variable"==a)return d.marked="property",b()}function ga(a,c){if("async"==a)return d.marked="property",b(ga);if("variable"==a||"keyword"==d.style)return d.marked="property","get"==c||"set"==c?b(Na):b(D);if("number"==a||"string"==a)return d.marked=S?"property":d.style+" property",b(D);if("jsonld-keyword"==a)return b(D);if("modifier"==a)return b(ga);if("["==a)return b(m,k("]"),D);if("spread"==a)return b(m);if(":"==a)return g(D)}function Na(a){if("variable"!=
a)return g(D);d.marked="property";return b(w)}function D(a){if(":"==a)return b(u);if("("==a)return g(w)}function y(a,c,l){function f(e,z){return(l?-1<l.indexOf(e):","==e)?(e=d.state.lexical,"call"==e.info&&(e.pos=(e.pos||0)+1),b(function(b,f){return b==c||f==c?g():g(a)},f)):e==c||z==c?b():b(k(c))}return function(d,e){return d==c||e==c?b():g(a,f)}}function L(a,c,l){for(var f=3;f<arguments.length;f++)d.cc.push(arguments[f]);return b(h(c,l),y(a,c),e)}function T(a){return"}"==a?b():g(r,T)}function M(a,
c){if(v){if(":"==a)return b(t);if("?"==c)return b(M)}}function t(a){if("variable"==a)return d.marked="variable-3",b(N);if("string"==a||"number"==a||"atom"==a)return b(N);if("{"==a)return b(h("}"),y(V,"}",",;"),e,N);if("("==a)return b(y(ra,")"),Oa)}function Oa(a){if("=>"==a)return b(t)}function V(a,c){if("variable"==a||"keyword"==d.style)return d.marked="property",b(V);if("?"==c)return b(V);if(":"==a)return b(t);if("["==a)return b(m,M,k("]"),V)}function ra(a){if("variable"==a)return b(ra);if(":"==
a)return b(t)}function N(a,c){if("<"==c)return b(h(">"),y(t,">"),e,N);if("|"==c||"."==a)return b(t);if("["==a)return b(k("]"),N);if("extends"==c)return b(t)}function ca(){return g(x,M,O,Pa)}function x(a,c){if("modifier"==a)return b(x);if("variable"==a)return H(c),b();if("spread"==a)return b(x);if("["==a)return L(x,"]");if("{"==a)return L(Qa,"}")}function Qa(a,c){if("variable"==a&&!d.stream.match(/^\s*:/,!1))return H(c),b(O);"variable"==a&&(d.marked="property");return"spread"==a?b(x):"}"==a?g():b(k(":"),
x,O)}function O(a,c){if("="==c)return b(u)}function Pa(a){if(","==a)return b(ca)}function ma(a,c){if("keyword b"==a&&"else"==c)return b(h("form","else"),r,e)}function Aa(a){if("("==a)return b(h(")"),Ra,k(")"),e)}function Ra(a){return"var"==a?b(ca,k(";"),W):";"==a?b(W):"variable"==a?b(Sa):g(m,k(";"),W)}function Sa(a,c){return"in"==c||"of"==c?(d.marked="keyword",b(m)):b(C,W)}function W(a,c){return";"==a?b(sa):"in"==c||"of"==c?(d.marked="keyword",b(m)):g(m,k(";"),sa)}function sa(a){")"!=a&&b(m)}function w(a,
c){if("*"==c)return d.marked="keyword",b(w);if("variable"==a)return H(c),b(w);if("("==a)return b(I,h(")"),y(ea,")"),e,M,r,J);if(v&&"<"==c)return b(h(">"),y(t,">"),e,w)}function ea(a){return"spread"==a?b(ea):g(x,M,O)}function Fa(a,b){return"variable"==a?na(a,b):X(a,b)}function na(a,c){if("variable"==a)return H(c),b(X)}function X(a,c){if("<"==c)return b(h(">"),y(t,">"),e,X);if("extends"==c||"implements"==c||v&&","==a)return b(v?t:m,X);if("{"==a)return b(h("}"),A,e)}function A(a,c){if("variable"==a||
"keyword"==d.style){if(("async"==c||"static"==c||"get"==c||"set"==c||v&&("public"==c||"private"==c||"protected"==c||"readonly"==c||"abstract"==c))&&d.stream.match(/^\s+[\w$\xa1-\uffff]/,!1))return d.marked="keyword",b(A);d.marked="property";return b(v?ha:w,A)}if("["==a)return b(m,k("]"),v?ha:w,A);if("*"==c)return d.marked="keyword",b(A);if(";"==a)return b(A);if("}"==a)return b();if("@"==c)return b(m,A)}function ha(a,c){return"?"==c?b(ha):":"==a?b(t,O):"="==c?b(u):g(w)}function Ca(a,c){return"*"==
c?(d.marked="keyword",b(ia,k(";"))):"default"==c?(d.marked="keyword",b(m,k(";"))):"{"==a?b(y(ta,"}"),ia,k(";")):g(r)}function ta(a,c){if("as"==c)return d.marked="keyword",b(k("variable"));if("variable"==a)return g(u,ta)}function Da(a){return"string"==a?b():g(Y,ua,ia)}function Y(a,c){if("{"==a)return L(Y,"}");"variable"==a&&H(c);"*"==c&&(d.marked="keyword");return b(Ta)}function ua(a){if(","==a)return b(Y,ua)}function Ta(a,c){if("as"==c)return d.marked="keyword",b(Y)}function ia(a,c){if("from"==c)return d.marked=
"keyword",b(m)}function Ha(a){return"]"==a?b():g(y(u,"]"))}var E=wa.indentUnit,va=q.statementIndent,S=q.jsonld,F=q.json||S,v=q.typescript,aa=q.wordCharacters||/[\w$\xa1-\uffff]/,ka=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),d=a("keyword b"),f=a("keyword c"),e=a("operator"),g={type:"atom",style:"atom"},b={"if":a("if"),"while":b,"with":b,"else":d,"do":d,"try":d,"finally":d,"return":f,"break":f,"continue":f,"new":a("new"),"delete":f,"throw":f,"debugger":f,"var":a("var"),
"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":e,"typeof":e,"instanceof":e,"true":g,"false":g,"null":g,undefined:g,NaN:g,Infinity:g,"this":a("this"),"class":a("class"),"super":a("atom"),yield:f,"export":a("export"),"import":a("import"),"extends":f,await:f,async:a("async")};if(v){var d={type:"variable",style:"variable-3"},f={"interface":a("class"),"implements":f,namespace:f,module:a("module"),
"enum":a("module"),"public":a("modifier"),"private":a("modifier"),"protected":a("modifier"),"abstract":a("modifier"),as:e,string:d,number:d,"boolean":d,any:d},h;for(h in f)b[h]=f[h]}return b}(),R=/[+\-*&%=<>!?|~^@]/,ya=/^@(context|id|value|language|type|container|list|set|reverse|index|base|vocab|graph)"/,G,P,Ea={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0,"jsonld-keyword":!0},d={state:null,column:null,marked:null,cc:null},za={name:"this",next:{name:"arguments"}};e.lex=!0;return{startState:function(a){a=
{tokenize:B,lastType:"sof",cc:[],lexical:new la((a||0)-E,0,"block",!1),localVars:q.localVars,context:q.localVars&&{vars:q.localVars},indented:a||0};q.globalVars&&"object"==typeof q.globalVars&&(a.globalVars=q.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation(),ba(a,b));if(b.tokenize!=Q&&a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==G)return c;b.lastType="operator"!=G||"++"!=P&&"--"!=P?G:"incdec";a:{var f=
G,e=P,g=b.cc;d.state=b;d.stream=a;d.marked=null;d.cc=g;d.style=c;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((g.length?g.pop():F?m:r)(f,e)){for(;g.length&&g[g.length-1].lex;)g.pop()();if(d.marked){c=d.marked;break a}if(a="variable"==f)b:{for(a=b.localVars;a;a=a.next)if(a.name==e){a=!0;break b}for(b=b.context;b;b=b.prev)for(a=b.vars;a;a=a.next)if(a.name==e){a=!0;break b}a=void 0}if(a){c="variable-2";break a}break a}}return c},indent:function(a,b){if(a.tokenize==Q)return p.Pass;
if(a.tokenize!=B)return 0;var c=b&&b.charAt(0),d=a.lexical,g;if(!/^\s*else\b/.test(b))for(var h=a.cc.length-1;0<=h;--h){var k=a.cc[h];if(k==e)d=d.prev;else if(k!=ma)break}for(;!("stat"!=d.type&&"form"!=d.type||"}"!=c&&(!(g=a.cc[a.cc.length-1])||g!=C&&g!=K||/^[,\.=+\-*:?[\(]/.test(b)));)d=d.prev;va&&")"==d.type&&"stat"==d.prev.type&&(d=d.prev);g=d.type;h=c==g;return"vardef"==g?d.indented+("operator"==a.lastType||","==a.lastType?d.info+1:0):"form"==g&&"{"==c?d.indented:"form"==g?d.indented+E:"stat"==
g?(c=d.indented,a="operator"==a.lastType||","==a.lastType||R.test(b.charAt(0))||/[,.]/.test(b.charAt(0)),c+(a?va||E:0)):"switch"!=d.info||h||0==q.doubleIndentSwitch?d.align?d.column+(h?0:1):d.indented+(h?0:E):d.indented+(/^(?:case|default)\b/.test(b)?E:2*E)},electricInput:/^\s*(?:case .*?:|default:|\{|\})$/,blockCommentStart:F?null:"/*",blockCommentEnd:F?null:"*/",lineComment:F?null:"//",fold:"brace",closeBrackets:"()[]{}''\"\"``",helperType:F?"json":"javascript",jsonldMode:S,jsonMode:F,expressionAllowed:ja,
skipExpression:function(a){var b=a.cc[a.cc.length-1];b!=m&&b!=u||a.cc.pop()}}});p.registerHelper("wordChars","javascript",/[\w$]/);p.defineMIME("text/javascript","javascript");p.defineMIME("text/ecmascript","javascript");p.defineMIME("application/javascript","javascript");p.defineMIME("application/x-javascript","javascript");p.defineMIME("application/ecmascript","javascript");p.defineMIME("application/json",{name:"javascript",json:!0});p.defineMIME("application/x-json",{name:"javascript",json:!0});
p.defineMIME("application/ld+json",{name:"javascript",jsonld:!0});p.defineMIME("text/typescript",{name:"javascript",typescript:!0});p.defineMIME("application/typescript",{name:"javascript",typescript:!0})});
