'use strict';(function(p){"object"==typeof exports&&"object"==typeof module?p(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],p):p(CodeMirror)})(function(p){function ca(p,q,n){return/^(?:operator|sof|keyword c|case|new|[\[{}\(,;:]|=>)$/.test(q.lastType)||"quasi"==q.lastType&&/\{\s*$/.test(p.string.slice(0,p.pos-(n||0)))}p.defineMode("javascript",function(ta,q){function n(a,c,b){B=a;J=b;return c}function w(a,c){var b=a.next();if('"'==b||"'"==b)return c.tokenize=
ua(b),c.tokenize(a,c);if("."==b&&a.match(/^\d+(?:[eE][+\-]?\d+)?/))return n("number","number");if("."==b&&a.match(".."))return n("spread","meta");if(/[\[\]{}\(\),;\:\.]/.test(b))return n(b);if("="==b&&a.eat(">"))return n("=>","operator");if("0"==b&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if("0"==b&&a.eat(/o/i))return a.eatWhile(/[0-7]/i),n("number","number");if("0"==b&&a.eat(/b/i))return a.eatWhile(/[01]/i),n("number","number");if(/\d/.test(b))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),
n("number","number");if("/"==b){if(a.eat("*"))return c.tokenize=K,K(a,c);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");if(ca(a,c,1)){a:for(var e=c=!1;null!=(b=a.next());){if(!c){if("/"==b&&!e)break a;"["==b?e=!0:e&&"]"==b&&(e=!1)}c=!c&&"\\"==b}a.match(/^\b(([gimyu])(?![gimyu]*\2))+\b/);return n("regexp","string-2")}a.eatWhile(L);return n("operator","operator",a.current())}if("`"==b)return c.tokenize=S,S(a,c);if("#"==b)return a.skipToEnd(),n("error","error");if(L.test(b))return a.eatWhile(L),
n("operator","operator",a.current());if(T.test(b))return a.eatWhile(T),a=a.current(),(b=da.propertyIsEnumerable(a)&&da[a])&&"."!=c.lastType?n(b.type,b.style,a):n("variable","variable",a)}function ua(a){return function(c,b){var e=!1,d;if(M&&"@"==c.peek()&&c.match(va))return b.tokenize=w,n("jsonld-keyword","meta");for(;null!=(d=c.next())&&(d!=a||e);)e=!e&&"\\"==d;e||(b.tokenize=w);return n("string","string")}}function K(a,c){for(var b=!1,e;e=a.next();){if("/"==e&&b){c.tokenize=w;break}b="*"==e}return n("comment",
"comment")}function S(a,c){for(var b=!1,e;null!=(e=a.next());){if(!b&&("`"==e||"$"==e&&a.eat("{"))){c.tokenize=w;break}b=!b&&"\\"==e}return n("quasi","string-2",a.current())}function U(a,c){c.fatArrowAt&&(c.fatArrowAt=null);var b=a.string.indexOf("=>",a.start);if(!(0>b)){for(var e=0,d=!1,b=b-1;0<=b;--b){var C=a.string.charAt(b),f="([{}])".indexOf(C);if(0<=f&&3>f){if(!e){++b;break}if(0==--e)break}else if(3<=f&&6>f)++e;else if(T.test(C))d=!0;else{if(/["'\/]/.test(C))return;if(d&&!e){++b;break}}}d&&
!e&&(c.fatArrowAt=b)}}function fa(a,b,d,e,f,C){this.indented=a;this.column=b;this.type=d;this.prev=f;this.info=C;null!=e&&(this.align=e)}function f(){for(var a=arguments.length-1;0<=a;a--)d.cc.push(arguments[a])}function b(){f.apply(null,arguments);return!0}function D(a){function b(c){for(;c;c=c.next)if(c.name==a)return!0;return!1}var l=d.state;d.marked="def";l.context?b(l.localVars)||(l.localVars={name:a,next:l.localVars}):!b(l.globalVars)&&q.globalVars&&(l.globalVars={name:a,next:l.globalVars})}
function E(){d.state.context={prev:d.state.context,vars:d.state.localVars};d.state.localVars=wa}function F(){d.state.localVars=d.state.context.vars;d.state.context=d.state.context.prev}function g(a,b){var l=function(){var e=d.state,l=e.indented;if("stat"==e.lexical.type)l=e.lexical.indented;else for(var f=e.lexical;f&&")"==f.type&&f.align;f=f.prev)l=f.indented;e.lexical=new fa(l,d.stream.column(),a,null,e.lexical,b)};l.lex=!0;return l}function h(){var a=d.state;a.lexical.prev&&(")"==a.lexical.type&&
(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function m(a){function c(d){return d==a?b():";"==a?f():b(c)}return c}function r(a,c){return"var"==a?b(g("vardef",c.length),V,m(";"),h):"keyword a"==a?b(g("form"),k,r,h):"keyword b"==a?b(g("form"),r,h):"{"==a?b(g("}"),N,h):";"==a?b():"if"==a?("else"==d.state.lexical.info&&d.state.cc[d.state.cc.length-1]==h&&d.state.cc.pop()(),b(g("form"),k,r,h,ga)):"function"==a?b(v):"for"==a?b(g("form"),ha,r,h):"variable"==a?b(g("stat"),xa):"switch"==a?b(g("form"),
k,g("}","switch"),m("{"),N,h,h):"case"==a?b(k,m(":")):"default"==a?b(m(":")):"catch"==a?b(g("form"),E,m("("),W,m(")"),r,h,F):"class"==a?b(g("form"),ya,h):"export"==a?b(g("stat"),za,h):"import"==a?b(g("stat"),Aa,h):"module"==a?b(g("form"),u,g("}"),m("{"),N,h,h):"async"==a?b(r):f(g("stat"),k,m(";"),h)}function k(a){return ia(a,!1)}function t(a){return ia(a,!0)}function ia(a,c){if(d.state.fatArrowAt==d.stream.start){var l=c?ja:ka;if("("==a)return b(E,g(")"),x(u,")"),h,m("=>"),l,F);if("variable"==a)return f(E,
u,m("=>"),l,F)}l=c?O:G;return Ba.hasOwnProperty(a)?b(l):"function"==a?b(v,l):"keyword c"==a?b(c?la:X):"("==a?b(g(")"),X,P,m(")"),h,l):"operator"==a||"spread"==a?b(c?t:k):"["==a?b(g("]"),Ca,h,l):"{"==a?H(ma,"}",null,l):"quasi"==a?f(Q,l):"new"==a?b(Da(c)):b()}function X(a){return a.match(/[;\}\)\],]/)?f():f(k)}function la(a){return a.match(/[;\}\)\],]/)?f():f(t)}function G(a,c){return","==a?b(k):O(a,c,!1)}function O(a,c,d){var e=0==d?G:O,ea=0==d?k:t;if("=>"==a)return b(E,d?ja:ka,F);if("operator"==a)return/\+\+|--/.test(c)?
b(e):"?"==c?b(k,m(":"),ea):b(ea);if("quasi"==a)return f(Q,e);if(";"!=a){if("("==a)return H(t,")","call",e);if("."==a)return b(Ea,e);if("["==a)return b(g("]"),X,m("]"),h,e)}}function Q(a,c){return"quasi"!=a?f():"${"!=c.slice(c.length-2)?b(Q):b(k,Fa)}function Fa(a){if("}"==a)return d.marked="string-2",d.state.tokenize=S,b(Q)}function ka(a){U(d.stream,d.state);return f("{"==a?r:k)}function ja(a){U(d.stream,d.state);return f("{"==a?r:t)}function Da(a){return function(c){return"."==c?b(a?Ga:Ha):f(a?t:
k)}}function Ha(a,c){if("target"==c)return d.marked="keyword",b(G)}function Ga(a,c){if("target"==c)return d.marked="keyword",b(O)}function xa(a){return":"==a?b(h,r):f(G,m(";"),h)}function Ea(a){if("variable"==a)return d.marked="property",b()}function ma(a,c){if("variable"==a||"keyword"==d.style)return d.marked="property","get"==c||"set"==c?b(Ia):b(I);if("number"==a||"string"==a)return d.marked=M?"property":d.style+" property",b(I);if("jsonld-keyword"==a)return b(I);if("modifier"==a)return b(ma);if("["==
a)return b(k,m("]"),I);if("spread"==a)return b(k)}function Ia(a){if("variable"!=a)return f(I);d.marked="property";return b(v)}function I(a){if(":"==a)return b(t);if("("==a)return f(v)}function x(a,c){function l(e,f){return","==e?(e=d.state.lexical,"call"==e.info&&(e.pos=(e.pos||0)+1),b(a,l)):e==c||f==c?b():b(m(c))}return function(e,d){return e==c||d==c?b():f(a,l)}}function H(a,c,l){for(var e=3;e<arguments.length;e++)d.cc.push(arguments[e]);return b(g(c,l),x(a,c),h)}function N(a){return"}"==a?b():
f(r,N)}function Y(a){if(na&&":"==a)return b(oa)}function Ja(a,c){if("="==c)return b(t)}function oa(a){if("variable"==a)return d.marked="variable-3",b(Z)}function Z(a,c){if("<"==c)return b(x(oa,">"),Z);if("["==a)return b(m("]"),Z)}function V(){return f(u,Y,aa,Ka)}function u(a,c){if("modifier"==a)return b(u);if("variable"==a)return D(c),b();if("spread"==a)return b(u);if("["==a)return H(u,"]");if("{"==a)return H(La,"}")}function La(a,c){if("variable"==a&&!d.stream.match(/^\s*:/,!1))return D(c),b(aa);
"variable"==a&&(d.marked="property");return"spread"==a?b(u):"}"==a?f():b(m(":"),u,aa)}function aa(a,c){if("="==c)return b(t)}function Ka(a){if(","==a)return b(V)}function ga(a,c){if("keyword b"==a&&"else"==c)return b(g("form","else"),r,h)}function ha(a){if("("==a)return b(g(")"),Ma,m(")"),h)}function Ma(a){return"var"==a?b(V,m(";"),R):";"==a?b(R):"variable"==a?b(Na):f(k,m(";"),R)}function Na(a,c){return"in"==c||"of"==c?(d.marked="keyword",b(k)):b(G,R)}function R(a,c){return";"==a?b(pa):"in"==c||"of"==
c?(d.marked="keyword",b(k)):f(k,m(";"),pa)}function pa(a){")"!=a&&b(k)}function v(a,c){if("*"==c)return d.marked="keyword",b(v);if("variable"==a)return D(c),b(v);if("("==a)return b(E,g(")"),x(W,")"),h,Y,r,F)}function W(a){return"spread"==a?b(W):f(u,Y,Ja)}function ya(a,c){if("variable"==a)return D(c),b(qa)}function qa(a,c){if("extends"==c)return b(k,qa);if("{"==a)return b(g("}"),y,h)}function y(a,c){if("variable"==a||"keyword"==d.style){if("static"==c)return d.marked="keyword",b(y);d.marked="property";
return"get"==c||"set"==c?b(Oa,v,y):b(v,y)}if("*"==c)return d.marked="keyword",b(y);if(";"==a)return b(y);if("}"==a)return b()}function Oa(a){if("variable"!=a)return f();d.marked="property";return b()}function za(a,c){return"*"==c?(d.marked="keyword",b(ra,m(";"))):"default"==c?(d.marked="keyword",b(k,m(";"))):f(r)}function Aa(a){return"string"==a?b():f(ba,ra)}function ba(a,c){if("{"==a)return H(ba,"}");"variable"==a&&D(c);"*"==c&&(d.marked="keyword");return b(Pa)}function Pa(a,c){if("as"==c)return d.marked=
"keyword",b(ba)}function ra(a,c){if("from"==c)return d.marked="keyword",b(k)}function Ca(a){return"]"==a?b():f(t,Qa)}function Qa(a){return"for"==a?f(P,m("]")):","==a?b(x(la,"]")):f(x(t,"]"))}function P(a){if("for"==a)return b(ha,P);if("if"==a)return b(k,P)}var z=ta.indentUnit,sa=q.statementIndent,M=q.jsonld,A=q.json||M,na=q.typescript,T=q.wordCharacters||/[\w$\xa1-\uffff]/,da=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),d=a("keyword b"),e=a("keyword c"),f=a("operator"),
h={type:"atom",style:"atom"},b={"if":a("if"),"while":b,"with":b,"else":d,"do":d,"try":d,"finally":d,"return":e,"break":e,"continue":e,"new":a("new"),"delete":e,"throw":e,"debugger":e,"var":a("var"),"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":f,"typeof":f,"instanceof":f,"true":h,"false":h,"null":h,undefined:h,NaN:h,Infinity:h,"this":a("this"),"class":a("class"),"super":a("atom"),yield:e,"export":a("export"),
"import":a("import"),"extends":e,await:e,async:a("async")};if(na){var d={type:"variable",style:"variable-3"},e={"interface":a("class"),"implements":e,namespace:e,module:a("module"),"enum":a("module"),"public":a("modifier"),"private":a("modifier"),"protected":a("modifier"),"abstract":a("modifier"),as:f,string:d,number:d,"boolean":d,any:d},k;for(k in e)b[k]=e[k]}return b}(),L=/[+\-*&%=<>!?|~^]/,va=/^@(context|id|value|language|type|container|list|set|reverse|index|base|vocab|graph)"/,B,J,Ba={atom:!0,
number:!0,variable:!0,string:!0,regexp:!0,"this":!0,"jsonld-keyword":!0},d={state:null,column:null,marked:null,cc:null},wa={name:"this",next:{name:"arguments"}};h.lex=!0;return{startState:function(a){a={tokenize:w,lastType:"sof",cc:[],lexical:new fa((a||0)-z,0,"block",!1),localVars:q.localVars,context:q.localVars&&{vars:q.localVars},indented:a||0};q.globalVars&&"object"==typeof q.globalVars&&(a.globalVars=q.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=
!1),b.indented=a.indentation(),U(a,b));if(b.tokenize!=K&&a.eatSpace())return null;var f=b.tokenize(a,b);if("comment"==B)return f;b.lastType="operator"!=B||"++"!=J&&"--"!=J?B:"incdec";a:{var e=B,h=J,g=b.cc;d.state=b;d.stream=a;d.marked=null;d.cc=g;d.style=f;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((g.length?g.pop():A?k:r)(e,h)){for(;g.length&&g[g.length-1].lex;)g.pop()();if(d.marked){f=d.marked;break a}if(a="variable"==e)b:{for(a=b.localVars;a;a=a.next)if(a.name==h){a=!0;break b}for(b=
b.context;b;b=b.prev)for(a=b.vars;a;a=a.next)if(a.name==h){a=!0;break b}a=void 0}if(a){f="variable-2";break a}break a}}return f},indent:function(a,b){if(a.tokenize==K)return p.Pass;if(a.tokenize!=w)return 0;var d=b&&b.charAt(0),e=a.lexical;if(!/^\s*else\b/.test(b))for(var f=a.cc.length-1;0<=f;--f){var g=a.cc[f];if(g==h)e=e.prev;else if(g!=ga)break}"stat"==e.type&&"}"==d&&(e=e.prev);sa&&")"==e.type&&"stat"==e.prev.type&&(e=e.prev);f=e.type;g=d==f;return"vardef"==f?e.indented+("operator"==a.lastType||
","==a.lastType?e.info+1:0):"form"==f&&"{"==d?e.indented:"form"==f?e.indented+z:"stat"==f?(d=e.indented,a="operator"==a.lastType||","==a.lastType||L.test(b.charAt(0))||/[,.]/.test(b.charAt(0)),d+(a?sa||z:0)):"switch"!=e.info||g||0==q.doubleIndentSwitch?e.align?e.column+(g?0:1):e.indented+(g?0:z):e.indented+(/^(?:case|default)\b/.test(b)?z:2*z)},electricInput:/^\s*(?:case .*?:|default:|\{|\})$/,blockCommentStart:A?null:"/*",blockCommentEnd:A?null:"*/",lineComment:A?null:"//",fold:"brace",closeBrackets:"()[]{}''\"\"``",
helperType:A?"json":"javascript",jsonldMode:M,jsonMode:A,expressionAllowed:ca,skipExpression:function(a){var b=a.cc[a.cc.length-1];b!=k&&b!=t||a.cc.pop()}}});p.registerHelper("wordChars","javascript",/[\w$]/);p.defineMIME("text/javascript","javascript");p.defineMIME("text/ecmascript","javascript");p.defineMIME("application/javascript","javascript");p.defineMIME("application/x-javascript","javascript");p.defineMIME("application/ecmascript","javascript");p.defineMIME("application/json",{name:"javascript",
json:!0});p.defineMIME("application/x-json",{name:"javascript",json:!0});p.defineMIME("application/ld+json",{name:"javascript",jsonld:!0});p.defineMIME("text/typescript",{name:"javascript",typescript:!0});p.defineMIME("application/typescript",{name:"javascript",typescript:!0})});
