'use strict';(function(r){"object"==typeof exports&&"object"==typeof module?r(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],r):r(CodeMirror)})(function(r){r.defineMode("haxe",function(l,t){function e(a){return{type:a,style:"keyword"}}function r(a,d){for(var c=!1,b;null!=(b=a.next());){if(b==d&&!c)return!0;c=!c&&"\\"==b}}function q(a,d,c){n=a;O=c;return d}function C(a,d){var c=a.next();if('"'==c||"'"==c)return c=aa(c),d.tokenize=c,c(a,d);if(/[\[\]{}\(\),;\:\.]/.test(c))return q(c);
if("0"==c&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),q("number","number");if(/\d/.test(c)||"-"==c&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*(?!\.))?(?:[eE][+\-]?\d+)?/),q("number","number");if(d.reAllowed&&"~"==c&&a.eat(/\//))return r(a,"/"),a.eatWhile(/[gimsu]/),q("regexp","string-2");if("/"==c){if(a.eat("*"))return c=ba,d.tokenize=c,c(a,d);if(a.eat("/"))return a.skipToEnd(),q("comment","comment");a.eatWhile(H);return q("operator",null,a.current())}if("#"==c)return a.skipToEnd(),q("conditional","meta");
if("@"==c)return a.eat(/:/),a.eatWhile(/[\w_]/),q("metadata","meta");if(H.test(c))return a.eatWhile(H),q("operator",null,a.current());if(/[A-Z]/.test(c))return a.eatWhile(/[\w_<>]/),c=a.current(),q("type","variable-3",c);a.eatWhile(/[\w_]/);var c=a.current(),b=P.propertyIsEnumerable(c)&&P[c];return b&&d.kwAllowed?q(b.type,b.style,c):q("variable","variable",c)}function aa(a){return function(d,b){r(d,a)&&(b.tokenize=C);return q("string","string")}}function ba(a,d){for(var b=!1,h;h=a.next();){if("/"==
h&&b){d.tokenize=C;break}b="*"==h}return q("comment","comment")}function Q(a,d,b,h,e,f){this.indented=a;this.column=d;this.type=b;this.prev=e;this.info=f;null!=h&&(this.align=h)}function R(a){for(var d=f.state,b=d.importedtypes;b;b=b.next)if(b.name==a)return;d.importedtypes={name:a,next:d.importedtypes}}function v(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}function b(){v.apply(null,arguments);return!0}function S(a,b){for(var c=b;c;c=c.next)if(c.name==a)return!0;return!1}function D(a){var b=
f.state;b.context?(f.marked="def",S(a,b.localVars)||(b.localVars={name:a,next:b.localVars})):b.globalVars&&!S(a,b.globalVars)&&(b.globalVars={name:a,next:b.globalVars})}function I(){f.state.context||(f.state.localVars=ca);f.state.context={prev:f.state.context,vars:f.state.localVars}}function E(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function k(a,b){var c=function(){var c=f.state;c.lexical=new Q(c.indented,f.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}
function g(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function p(a){function d(c){return c==a?b():";"==a?v():b(d)}return d}function w(a){return"@"==a?b(T):"var"==a?b(k("vardef"),J,p(";"),g):"keyword a"==a?b(k("form"),u,w,g):"keyword b"==a?b(k("form"),w,g):"{"==a?b(k("}"),I,K,g,E):";"==a?b():"attribute"==a?b(U):"function"==a?b(z):"for"==a?b(k("form"),p("("),k(")"),da,p(")"),g,w,g):"variable"==a?b(k("stat"),ea):"switch"==a?b(k("form"),
u,k("}","switch"),p("{"),K,g,g):"case"==a?b(u,p(":")):"default"==a?b(p(":")):"catch"==a?b(k("form"),I,p("("),V,p(")"),w,g,E):"import"==a?b(W,p(";")):"typedef"==a?b(fa):v(k("stat"),u,p(";"),g)}function u(a){return X.hasOwnProperty(a)||"type"==a?b(x):"function"==a?b(z):"keyword c"==a?b(L):"("==a?b(k(")"),L,p(")"),g,x):"operator"==a?b(u):"["==a?b(k("]"),y(L,"]"),g,x):"{"==a?b(k("}"),y(ga,"}"),g,x):b()}function L(a){return a.match(/[;\}\)\],]/)?v():v(u)}function x(a,d){if("operator"==a&&/\+\+|--/.test(d))return b(x);
if("operator"==a||":"==a)return b(u);if(";"!=a){if("("==a)return b(k(")"),y(u,")"),g,x);if("."==a)return b(ha,x);if("["==a)return b(k("]"),u,p("]"),g,x)}}function U(a){if("attribute"==a)return b(U);if("function"==a)return b(z);if("var"==a)return b(J)}function T(a){if(":"==a||"variable"==a)return b(T);if("("==a)return b(k(")"),y(ia,")"),g,w)}function ia(a){if("variable"==a)return b()}function W(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return R(d),b();if("variable"==a||"property"==a||"."==a||
"*"==d)return b(W)}function fa(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return R(d),b();if("type"==a&&/[A-Z]/.test(d.charAt(0)))return b()}function ea(a){return":"==a?b(g,w):v(x,p(";"),g)}function ha(a){if("variable"==a)return f.marked="property",b()}function ga(a){"variable"==a&&(f.marked="property");if(X.hasOwnProperty(a))return b(p(":"),u)}function y(a,d){function c(h){return","==h?b(a,c):h==d?b():b(p(d))}return function(h){return h==d?b():v(a,c)}}function K(a){return"}"==a?b():v(w,K)}
function J(a,d){return"variable"==a?(D(d),b(F,Y)):b()}function Y(a,d){if("="==d)return b(u,Y);if(","==a)return b(J)}function da(a,d){return"variable"==a?(D(d),b(ja,u)):v()}function ja(a,d){if("in"==d)return b()}function z(a,d){if("variable"==a||"type"==a)return D(d),b(z);if("new"==d)return b(z);if("("==a)return b(k(")"),I,y(V,")"),g,F,w,E)}function F(a){if(":"==a)return b(ka)}function ka(a){if("type"==a||"variable"==a)return b();if("{"==a)return b(k("}"),y(la,"}"),g)}function la(a){if("variable"==
a)return b(F)}function V(a,d){if("variable"==a)return D(d),b(F)}var A=l.indentUnit,Z=e("keyword a"),M=e("keyword b"),B=e("keyword c"),ma=e("operator"),N={type:"atom",style:"atom"},G={type:"attribute",style:"attribute"},n=e("typedef"),P={"if":Z,"while":Z,"else":M,"do":M,"try":M,"return":B,"break":B,"continue":B,"new":B,"throw":B,"var":e("var"),inline:G,"static":G,using:e("import"),"public":G,"private":G,cast:e("cast"),"import":e("import"),macro:e("macro"),"function":e("function"),"catch":e("catch"),
untyped:e("untyped"),callback:e("cb"),"for":e("for"),"switch":e("switch"),"case":e("case"),"default":e("default"),"in":ma,never:e("property_access"),trace:e("trace"),"class":n,"abstract":n,"enum":n,"interface":n,typedef:n,"extends":n,"implements":n,dynamic:n,"true":N,"false":N,"null":N},H=/[+\-*&%=<>!?|]/,O,X={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},f={state:null,column:null,marked:null,cc:null},ca={name:"this",next:null};E.lex=!0;g.lex=!0;return{startState:function(a){a={tokenize:C,reAllowed:!0,
kwAllowed:!0,cc:[],lexical:new Q((a||0)-A,0,"block",!1),localVars:t.localVars,importedtypes:"Int Float String Void Std Bool Dynamic Array".split(" "),context:t.localVars&&{vars:t.localVars},indented:0};t.globalVars&&"object"==typeof t.globalVars&&(a.globalVars=t.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==n)return c;b.reAllowed=!("operator"!=n&&
"keyword c"!=n&&!n.match(/^[\[{}\(,;:]$/));b.kwAllowed="."!=n;a:{var h=n,e=O,m=b.cc;f.state=b;f.stream=a;f.marked=null;f.cc=m;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((m.length?m.pop():w)(h,e)){for(;m.length&&m[m.length-1].lex;)m.pop()();if(f.marked){c=f.marked;break a}if(m="variable"==h)b:{for(m=b.localVars;m;m=m.next)if(m.name==e){m=!0;break b}m=void 0}if(m){c="variable-2";break a}if(h="variable"==h)b:if(h=b,/[a-z]/.test(e.charAt(0)))h=!1;else{for(var m=h.importedtypes.length,
g=0;g<m;g++)if(h.importedtypes[g]==e){h=!0;break b}h=void 0}if(h){c="variable-3";break a}break a}}return c},indent:function(a,b){if(a.tokenize!=C)return 0;var c=b&&b.charAt(0),e=a.lexical;"stat"==e.type&&"}"==c&&(e=e.prev);var f=e.type,g=c==f;return"vardef"==f?e.indented+4:"form"==f&&"{"==c?e.indented:"stat"==f||"form"==f?e.indented+A:"switch"!=e.info||g?e.align?e.column+(g?0:1):e.indented+(g?0:A):e.indented+(/^(?:case|default)\b/.test(b)?A:2*A)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",
lineComment:"//"}});r.defineMIME("text/x-haxe","haxe");r.defineMode("hxml",function(){return{startState:function(){return{define:!1,inString:!1}},token:function(l,t){var e=l.peek(),r=l.sol();if("#"==e)return l.skipToEnd(),"comment";if(r&&"-"==e)return e="variable-2",l.eat(/-/),"-"==l.peek()&&(l.eat(/-/),e="keyword a"),"D"==l.peek()&&(l.eat(/[D]/),e="keyword c",t.define=!0),l.eatWhile(/[A-Z]/i),e;e=l.peek();0==t.inString&&"'"==e&&(t.inString=!0,l.next());if(1==t.inString)return l.skipTo("'")||l.skipToEnd(),
"'"==l.peek()&&(l.next(),t.inString=!1),"string";l.next();return null},lineComment:"#"}});r.defineMIME("text/x-hxml","hxml")});
