'use strict';(function(p){"object"==typeof exports&&"object"==typeof module?p(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],p):p(CodeMirror)})(function(p){p.defineMode("haxe",function(g,q){function c(a){return{type:a,style:"keyword"}}function p(a,d){for(var b=!1,f;null!=(f=a.next());){if(f==d&&!b)return!0;b=!b&&"\\"==f}}function n(a,d,b){l=a;M=b;return d}function A(a,d){var b=a.next();if('"'==b||"'"==b)return b=X(b),d.tokenize=b,b(a,d);if(/[\[\]{}\(\),;\:\.]/.test(b))return n(b);
if("0"==b&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if(/\d/.test(b)||"-"==b&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*(?!\.))?(?:[eE][+\-]?\d+)?/),n("number","number");if(d.reAllowed&&"~"==b&&a.eat(/\//))return p(a,"/"),a.eatWhile(/[gimsu]/),n("regexp","string-2");if("/"==b){if(a.eat("*"))return b=Y,d.tokenize=b,b(a,d);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");a.eatWhile(F);return n("operator",null,a.current())}if("#"==b)return a.skipToEnd(),n("conditional","meta");
if("@"==b)return a.eat(/:/),a.eatWhile(/[\w_]/),n("metadata","meta");if(F.test(b))return a.eatWhile(F),n("operator",null,a.current());if(/[A-Z]/.test(b))return a.eatWhile(/[\w_<>]/),a=a.current(),n("type","variable-3",a);a.eatWhile(/[\w_]/);a=a.current();return(b=N.propertyIsEnumerable(a)&&N[a])&&d.kwAllowed?n(b.type,b.style,a):n("variable","variable",a)}function X(a){return function(b,c){p(b,a)&&(c.tokenize=A);return n("string","string")}}function Y(a,b){for(var c=!1,f;f=a.next();){if("/"==f&&c){b.tokenize=
A;break}c="*"==f}return n("comment","comment")}function O(a,b,c,f,h,g){this.indented=a;this.column=b;this.type=c;this.prev=h;this.info=g;null!=f&&(this.align=f)}function P(a){for(var b=h.state,c=b.importedtypes;c;c=c.next)if(c.name==a)return;b.importedtypes={name:a,next:b.importedtypes}}function t(){for(var a=arguments.length-1;0<=a;a--)h.cc.push(arguments[a])}function b(){t.apply(null,arguments);return!0}function Q(a,b){for(;b;b=b.next)if(b.name==a)return!0;return!1}function B(a){var b=h.state;b.context?
(h.marked="def",Q(a,b.localVars)||(b.localVars={name:a,next:b.localVars})):b.globalVars&&!Q(a,b.globalVars)&&(b.globalVars={name:a,next:b.globalVars})}function G(){h.state.context||(h.state.localVars=Z);h.state.context={prev:h.state.context,vars:h.state.localVars}}function C(){h.state.localVars=h.state.context.vars;h.state.context=h.state.context.prev}function k(a,b){var c=function(){var c=h.state;c.lexical=new O(c.indented,h.stream.column(),a,null,c.lexical,b)};c.lex=!0;return c}function e(){var a=
h.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function m(a){function d(c){return c==a?b():";"==a?t():b(d)}return d}function u(a){return"@"==a?b(R):"var"==a?b(k("vardef"),H,m(";"),e):"keyword a"==a?b(k("form"),r,u,e):"keyword b"==a?b(k("form"),u,e):"{"==a?b(k("}"),G,I,e,C):";"==a?b():"attribute"==a?b(S):"function"==a?b(x):"for"==a?b(k("form"),m("("),k(")"),aa,m(")"),e,u,e):"variable"==a?b(k("stat"),ba):"switch"==a?b(k("form"),r,k("}","switch"),
m("{"),I,e,e):"case"==a?b(r,m(":")):"default"==a?b(m(":")):"catch"==a?b(k("form"),G,m("("),T,m(")"),u,e,C):"import"==a?b(U,m(";")):"typedef"==a?b(ca):t(k("stat"),r,m(";"),e)}function r(a){return V.hasOwnProperty(a)||"type"==a?b(v):"function"==a?b(x):"keyword c"==a?b(J):"("==a?b(k(")"),J,m(")"),e,v):"operator"==a?b(r):"["==a?b(k("]"),w(J,"]"),e,v):"{"==a?b(k("}"),w(da,"}"),e,v):b()}function J(a){return a.match(/[;\}\)\],]/)?t():t(r)}function v(a,d){if("operator"==a&&/\+\+|--/.test(d))return b(v);if("operator"==
a||":"==a)return b(r);if(";"!=a){if("("==a)return b(k(")"),w(r,")"),e,v);if("."==a)return b(ea,v);if("["==a)return b(k("]"),r,m("]"),e,v)}}function S(a){if("attribute"==a)return b(S);if("function"==a)return b(x);if("var"==a)return b(H)}function R(a){if(":"==a||"variable"==a)return b(R);if("("==a)return b(k(")"),w(fa,")"),e,u)}function fa(a){if("variable"==a)return b()}function U(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return P(d),b();if("variable"==a||"property"==a||"."==a||"*"==d)return b(U)}
function ca(a,d){if("variable"==a&&/[A-Z]/.test(d.charAt(0)))return P(d),b();if("type"==a&&/[A-Z]/.test(d.charAt(0)))return b()}function ba(a){return":"==a?b(e,u):t(v,m(";"),e)}function ea(a){if("variable"==a)return h.marked="property",b()}function da(a){"variable"==a&&(h.marked="property");if(V.hasOwnProperty(a))return b(m(":"),r)}function w(a,d){function c(f){return","==f?b(a,c):f==d?b():b(m(d))}return function(f){return f==d?b():t(a,c)}}function I(a){return"}"==a?b():t(u,I)}function H(a,d){return"variable"==
a?(B(d),b(D,W)):b()}function W(a,d){if("="==d)return b(r,W);if(","==a)return b(H)}function aa(a,d){return"variable"==a?(B(d),b(ga,r)):t()}function ga(a,d){if("in"==d)return b()}function x(a,d){if("variable"==a||"type"==a)return B(d),b(x);if("new"==d)return b(x);if("("==a)return b(k(")"),G,w(T,")"),e,D,u,C)}function D(a){if(":"==a)return b(ha)}function ha(a){if("type"==a||"variable"==a)return b();if("{"==a)return b(k("}"),w(ia,"}"),e)}function ia(a){if("variable"==a)return b(D)}function T(a,d){if("variable"==
a)return B(d),b(D)}var y=g.indentUnit;g=c("keyword a");var K=c("keyword b"),z=c("keyword c"),ja=c("operator"),L={type:"atom",style:"atom"},E={type:"attribute",style:"attribute"},l=c("typedef"),N={"if":g,"while":g,"else":K,"do":K,"try":K,"return":z,"break":z,"continue":z,"new":z,"throw":z,"var":c("var"),inline:E,"static":E,using:c("import"),"public":E,"private":E,cast:c("cast"),"import":c("import"),macro:c("macro"),"function":c("function"),"catch":c("catch"),untyped:c("untyped"),callback:c("cb"),"for":c("for"),
"switch":c("switch"),"case":c("case"),"default":c("default"),"in":ja,never:c("property_access"),trace:c("trace"),"class":l,"abstract":l,"enum":l,"interface":l,typedef:l,"extends":l,"implements":l,dynamic:l,"true":L,"false":L,"null":L},F=/[+\-*&%=<>!?|]/,M,V={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},h={state:null,column:null,marked:null,cc:null},Z={name:"this",next:null};C.lex=!0;e.lex=!0;return{startState:function(a){a={tokenize:A,reAllowed:!0,kwAllowed:!0,cc:[],lexical:new O((a||0)-y,0,
"block",!1),localVars:q.localVars,importedtypes:"Int Float String Void Std Bool Dynamic Array".split(" "),context:q.localVars&&{vars:q.localVars},indented:0};q.globalVars&&"object"==typeof q.globalVars&&(a.globalVars=q.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==l)return c;b.reAllowed=!("operator"!=l&&"keyword c"!=l&&!l.match(/^[\[{}\(,;:]$/));
b.kwAllowed="."!=l;a:{var f=l,g=M,e=b.cc;h.state=b;h.stream=a;h.marked=null;h.cc=e;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((e.length?e.pop():u)(f,g)){for(;e.length&&e[e.length-1].lex;)e.pop()();if(h.marked){c=h.marked;break a}if(a="variable"==f)b:{for(a=b.localVars;a;a=a.next)if(a.name==g){a=!0;break b}a=void 0}if(a){c="variable-2";break a}if(f="variable"==f)b:if(/[a-z]/.test(g.charAt(0)))f=!1;else{f=b.importedtypes.length;for(a=0;a<f;a++)if(b.importedtypes[a]==g){f=!0;break b}f=
void 0}if(f){c="variable-3";break a}break a}}return c},indent:function(a,b){if(a.tokenize!=A)return 0;var c=b&&b.charAt(0);a=a.lexical;"stat"==a.type&&"}"==c&&(a=a.prev);var f=a.type,e=c==f;return"vardef"==f?a.indented+4:"form"==f&&"{"==c?a.indented:"stat"==f||"form"==f?a.indented+y:"switch"!=a.info||e?a.align?a.column+(e?0:1):a.indented+(e?0:y):a.indented+(/^(?:case|default)\b/.test(b)?y:2*y)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//"}});p.defineMIME("text/x-haxe",
"haxe");p.defineMode("hxml",function(){return{startState:function(){return{define:!1,inString:!1}},token:function(g,q){var c=g.peek(),p=g.sol();if("#"==c)return g.skipToEnd(),"comment";if(p&&"-"==c)return c="variable-2",g.eat(/-/),"-"==g.peek()&&(g.eat(/-/),c="keyword a"),"D"==g.peek()&&(g.eat(/[D]/),c="keyword c",q.define=!0),g.eatWhile(/[A-Z]/i),c;c=g.peek();0==q.inString&&"'"==c&&(q.inString=!0,g.next());if(1==q.inString)return g.skipTo("'")||g.skipToEnd(),"'"==g.peek()&&(g.next(),q.inString=!1),
"string";g.next();return null},lineComment:"#"}});p.defineMIME("text/x-hxml","hxml")});
