'use strict';(function(n){"object"==typeof exports&&"object"==typeof module?n(require("../lib/codemirror"),require("../addon/search/searchcursor"),require("../addon/edit/matchbrackets")):"function"==typeof define&&define.amd?define(["../lib/codemirror","../addon/search/searchcursor","../addon/edit/matchbrackets"],n):n(CodeMirror)})(function(n){function t(a,c){a.extendSelectionsBy(function(d){if(a.display.shift||a.doc.extend||d.empty()){var f;var m=a.doc;d=d.head;if(0>c&&0==d.ch)f=m.clipPos(k(d.line-
1));else{var b=m.getLine(d.line);if(0<c&&d.ch>=b.length)f=m.clipPos(k(d.line+1,0));else{for(var m="start",h=d.ch,e=0>c?0:b.length,g=0;h!=e;h+=c,g++){var q=b.charAt(0>c?h-1:h),p="_"!=q&&n.isWordChar(q)?"w":"o";"w"==p&&q.toUpperCase()==q&&(p="W");if("start"==m)"o"!=p&&(m="in",f=p);else if("in"==m&&f!=p)if("w"==f&&"W"==p&&0>c&&h--,"W"==f&&"w"==p&&0<c)f="w";else break}f=k(d.line,h)}}return f}return 0>c?d.from():d.to()})}function u(a,c){if(a.isReadOnly())return n.Pass;a.operation(function(){for(var d=
a.listSelections().length,f=[],m=-1,b=0;b<d;b++){var h=a.listSelections()[b].head;h.line<=m||(m=k(h.line+(c?0:1),0),a.replaceRange("\n",m,null,"+insertLine"),a.indentLine(m.line,null,!0),f.push({head:m,anchor:m}),m=h.line+1)}a.setSelections(f)});a.execCommand("indentAuto")}function r(a,c){var d=c.ch,f=d;for(a=a.getLine(c.line);d&&n.isWordChar(a.charAt(d-1));)--d;for(;f<a.length&&n.isWordChar(a.charAt(f));)++f;return{from:k(c.line,d),to:k(c.line,f),word:a.slice(d,f)}}function v(a){var c=a.getCursor(),
d=a.scanForBracket(c,-1);if(d)for(;;){c=a.scanForBracket(c,1);if(!c)break;if(c.ch=="(){}[]".charAt("(){}[]".indexOf(d.ch)+1))return a.setSelection(k(d.pos.line,d.pos.ch+1),c.pos,!1),!0;c=k(c.pos.line,c.pos.ch+1)}}function w(a,c){if(a.isReadOnly())return n.Pass;for(var d=a.listSelections(),f=[],m,b=0;b<d.length;b++){var h=d[b];if(!h.empty()){for(var e=h.from().line,g=h.to().line;b<d.length-1&&d[b+1].from().line==g;)g=h[++b].to().line;f.push(e,g)}}f.length?m=!0:f.push(a.firstLine(),a.lastLine());a.operation(function(){for(var d=
[],b=0;b<f.length;b+=2){var h=f[b+1],e=k(f[b],0),h=k(h),g=a.getRange(e,h,!1);c?g.sort():g.sort(function(a,c){var d=a.toUpperCase(),f=c.toUpperCase();d!=f&&(a=d,c=f);return a<c?-1:a==c?0:1});a.replaceRange(g,e,h);m&&d.push({anchor:e,head:h})}m&&a.setSelections(d,0)})}function x(a,c){a.operation(function(){for(var d=a.listSelections(),f=[],b=[],e=0;e<d.length;e++){var h=d[e];h.empty()?(f.push(e),b.push("")):b.push(c(a.getRange(h.from(),h.to())))}a.replaceSelections(b,"around","case");for(var e=f.length-
1,g;0<=e;e--)h=d[f[e]],g&&0<n.cmpPos(h.head,g)||(b=r(a,h.head),g=b.from,a.replaceRange(c(b.word),b.from,b.to))})}function y(a){var c=a.getCursor("from"),d=a.getCursor("to");if(0==n.cmpPos(c,d)){var f=r(a,c);if(!f.word)return;c=f.from;d=f.to}return{from:c,to:d,query:a.getRange(c,d),word:f}}function z(a,c){var d=y(a);if(d){var f=d.query,b=a.getSearchCursor(f,c?d.to:d.from);(c?b.findNext():b.findPrevious())?a.setSelection(b.from(),b.to()):(b=a.getSearchCursor(f,c?k(a.firstLine(),0):a.clipPos(k(a.lastLine()))),
(c?b.findNext():b.findPrevious())?a.setSelection(b.from(),b.to()):d.word&&a.setSelection(d.from,d.to))}}var b=n.keyMap.sublime={fallthrough:"default"},e=n.commands,k=n.Pos,l=n.keyMap["default"]==n.keyMap.macDefault,g=l?"Cmd-":"Ctrl-";e[b["Alt-Left"]="goSubwordLeft"]=function(a){t(a,-1)};e[b["Alt-Right"]="goSubwordRight"]=function(a){t(a,1)};l&&(b["Cmd-Left"]="goLineStartSmart");var A=l?"Ctrl-Alt-":"Ctrl-";e[b[A+"Up"]="scrollLineUp"]=function(a){var c=a.getScrollInfo();if(!a.somethingSelected()){var d=
a.lineAtHeight(c.top+c.clientHeight,"local");a.getCursor().line>=d&&a.execCommand("goLineUp")}a.scrollTo(null,c.top-a.defaultTextHeight())};e[b[A+"Down"]="scrollLineDown"]=function(a){var c=a.getScrollInfo();if(!a.somethingSelected()){var d=a.lineAtHeight(c.top,"local")+1;a.getCursor().line<=d&&a.execCommand("goLineDown")}a.scrollTo(null,c.top+a.defaultTextHeight())};e[b["Shift-"+g+"L"]="splitSelectionByLine"]=function(a){for(var c=a.listSelections(),d=[],f=0;f<c.length;f++)for(var b=c[f].from(),
e=c[f].to(),h=b.line;h<=e.line;++h)e.line>b.line&&h==e.line&&0==e.ch||d.push({anchor:h==b.line?b:k(h,0),head:h==e.line?e:k(h)});a.setSelections(d,0)};b["Shift-Tab"]="indentLess";e[b.Esc="singleSelectionTop"]=function(a){var c=a.listSelections()[0];a.setSelection(c.anchor,c.head,{scroll:!1})};e[b[g+"L"]="selectLine"]=function(a){for(var c=a.listSelections(),d=[],f=0;f<c.length;f++){var b=c[f];d.push({anchor:k(b.from().line,0),head:k(b.to().line+1,0)})}a.setSelections(d)};b["Shift-Ctrl-K"]="deleteLine";
e[b[g+"Enter"]="insertLineAfter"]=function(a){return u(a,!1)};e[b["Shift-"+g+"Enter"]="insertLineBefore"]=function(a){return u(a,!0)};e[b[g+"D"]="selectNextOccurrence"]=function(a){var c=a.getCursor("from"),d=a.getCursor("to"),f=a.state.sublimeFindFullWord==a.doc.sel;if(0==n.cmpPos(c,d)){f=r(a,c);if(!f.word)return;a.setSelection(f.from,f.to);f=!0}else c=a.getRange(c,d),c=f?new RegExp("\\b"+c+"\\b"):c,d=a.getSearchCursor(c,d),d.findNext()?a.addSelection(d.from(),d.to()):(d=a.getSearchCursor(c,k(a.firstLine(),
0)),d.findNext()&&a.addSelection(d.from(),d.to()));f&&(a.state.sublimeFindFullWord=a.doc.sel)};e[b["Shift-"+g+"Space"]="selectScope"]=function(a){v(a)||a.execCommand("selectAll")};e[b["Shift-"+g+"M"]="selectBetweenBrackets"]=function(a){if(!v(a))return n.Pass};e[b[g+"M"]="goToBracket"]=function(a){a.extendSelectionsBy(function(c){var d=a.scanForBracket(c.head,1);return d&&0!=n.cmpPos(d.pos,c.head)?d.pos:(d=a.scanForBracket(c.head,-1))&&k(d.pos.line,d.pos.ch+1)||c.head})};l=l?"Cmd-Ctrl-":"Shift-Ctrl-";
e[b[l+"Up"]="swapLineUp"]=function(a){if(a.isReadOnly())return n.Pass;for(var c=a.listSelections(),d=[],f=a.firstLine()-1,b=[],e=0;e<c.length;e++){var h=c[e],g=h.from().line-1,l=h.to().line;b.push({anchor:k(h.anchor.line-1,h.anchor.ch),head:k(h.head.line-1,h.head.ch)});0!=h.to().ch||h.empty()||--l;g>f?d.push(g,l):d.length&&(d[d.length-1]=l);f=l}a.operation(function(){for(var c=0;c<d.length;c+=2){var f=d[c],e=d[c+1],h=a.getLine(f);a.replaceRange("",k(f,0),k(f+1,0),"+swapLine");e>a.lastLine()?a.replaceRange("\n"+
h,k(a.lastLine()),null,"+swapLine"):a.replaceRange(h+"\n",k(e,0),null,"+swapLine")}a.setSelections(b);a.scrollIntoView()})};e[b[l+"Down"]="swapLineDown"]=function(a){if(a.isReadOnly())return n.Pass;for(var c=a.listSelections(),d=[],f=a.lastLine()+1,b=c.length-1;0<=b;b--){var e=c[b],h=e.to().line+1,g=e.from().line;0!=e.to().ch||e.empty()||h--;h<f?d.push(h,g):d.length&&(d[d.length-1]=g);f=g}a.operation(function(){for(var c=d.length-2;0<=c;c-=2){var b=d[c],f=d[c+1],e=a.getLine(b);b==a.lastLine()?a.replaceRange("",
k(b-1),k(b),"+swapLine"):a.replaceRange("",k(b,0),k(b+1,0),"+swapLine");a.replaceRange(e+"\n",k(f,0),null,"+swapLine")}a.scrollIntoView()})};e[b[g+"/"]="toggleCommentIndented"]=function(a){a.toggleComment({indent:!0})};e[b[g+"J"]="joinLines"]=function(a){for(var c=a.listSelections(),d=[],b=0;b<c.length;b++){for(var e=c[b],g=e.from(),h=g.line,l=e.to().line;b<c.length-1&&c[b+1].from().line==l;)l=c[++b].to().line;d.push({start:h,end:l,anchor:!e.empty()&&g})}a.operation(function(){for(var c=0,b=[],f=
0;f<d.length;f++){for(var e=d[f],h=e.anchor&&k(e.anchor.line-c,e.anchor.ch),g,l=e.start;l<=e.end;l++){var m=l-c;l==e.end&&(g=k(m,a.getLine(m).length+1));m<a.lastLine()&&(a.replaceRange(" ",k(m),k(m+1,/^\s*/.exec(a.getLine(m+1))[0].length)),++c)}b.push({anchor:h||g,head:g})}a.setSelections(b,0)})};e[b["Shift-"+g+"D"]="duplicateLine"]=function(a){a.operation(function(){for(var c=a.listSelections().length,d=0;d<c;d++){var b=a.listSelections()[d];b.empty()?a.replaceRange(a.getLine(b.head.line)+"\n",k(b.head.line,
0)):a.replaceRange(a.getRange(b.from(),b.to()),b.from())}a.scrollIntoView()})};b[g+"T"]="transposeChars";e[b.F9="sortLines"]=function(a){w(a,!0)};e[b[g+"F9"]="sortLinesInsensitive"]=function(a){w(a,!1)};e[b.F2="nextBookmark"]=function(a){var c=a.state.sublimeBookmarks;if(c)for(;c.length;){var d=c.shift(),b=d.find();if(b)return c.push(d),a.setSelection(b.from,b.to)}};e[b["Shift-F2"]="prevBookmark"]=function(a){var c=a.state.sublimeBookmarks;if(c)for(;c.length;){c.unshift(c.pop());var d=c[c.length-
1].find();if(d)return a.setSelection(d.from,d.to);c.pop()}};e[b[g+"F2"]="toggleBookmark"]=function(a){for(var c=a.listSelections(),d=a.state.sublimeBookmarks||(a.state.sublimeBookmarks=[]),b=0;b<c.length;b++){for(var e=c[b].from(),g=c[b].to(),h=a.findMarks(e,g),k=0;k<h.length;k++)if(h[k].sublimeBookmark){h[k].clear();for(var l=0;l<d.length;l++)d[l]==h[k]&&d.splice(l--,1);break}k==h.length&&d.push(a.markText(e,g,{sublimeBookmark:!0,clearWhenEmpty:!1}))}};e[b["Shift-"+g+"F2"]="clearBookmarks"]=function(a){if(a=
a.state.sublimeBookmarks)for(var c=0;c<a.length;c++)a[c].clear();a.length=0};e[b["Alt-F2"]="selectBookmarks"]=function(a){var c=a.state.sublimeBookmarks,d=[];if(c)for(var b=0;b<c.length;b++){var e=c[b].find();e?d.push({anchor:e.from,head:e.to}):c.splice(b--,0)}d.length&&a.setSelections(d,0)};b["Alt-Q"]="wrapLines";l=g+"K ";b[l+g+"Backspace"]="delLineLeft";e[b[l+g+"K"]="delLineRight"]=function(a){a.operation(function(){for(var c=a.listSelections(),b=c.length-1;0<=b;b--)a.replaceRange("",c[b].anchor,
k(c[b].to().line),"+delete");a.scrollIntoView()})};e[b[l+g+"U"]="upcaseAtCursor"]=function(a){x(a,function(a){return a.toUpperCase()})};e[b[l+g+"L"]="downcaseAtCursor"]=function(a){x(a,function(a){return a.toLowerCase()})};e[b[l+g+"Space"]="setSublimeMark"]=function(a){a.state.sublimeMark&&a.state.sublimeMark.clear();a.state.sublimeMark=a.setBookmark(a.getCursor())};e[b[l+g+"A"]="selectToSublimeMark"]=function(a){var c=a.state.sublimeMark&&a.state.sublimeMark.find();c&&a.setSelection(a.getCursor(),
c)};e[b[l+g+"W"]="deleteToSublimeMark"]=function(a){var c=a.state.sublimeMark&&a.state.sublimeMark.find();if(c){var b=a.getCursor();if(0<n.cmpPos(b,c))var e=c,c=b,b=e;a.state.sublimeKilled=a.getRange(b,c);a.replaceRange("",b,c)}};e[b[l+g+"X"]="swapWithSublimeMark"]=function(a){var c=a.state.sublimeMark&&a.state.sublimeMark.find();c&&(a.state.sublimeMark.clear(),a.state.sublimeMark=a.setBookmark(a.getCursor()),a.setCursor(c))};e[b[l+g+"Y"]="sublimeYank"]=function(a){null!=a.state.sublimeKilled&&a.replaceSelection(a.state.sublimeKilled,
null,"paste")};b[l+g+"G"]="clearBookmarks";e[b[l+g+"C"]="showInCenter"]=function(a){var c=a.cursorCoords(null,"local");a.scrollTo(null,(c.top+c.bottom)/2-a.getScrollInfo().clientHeight/2)};e[b["Shift-Alt-Up"]="selectLinesUpward"]=function(a){a.operation(function(){for(var c=a.listSelections(),b=0;b<c.length;b++){var e=c[b];e.head.line>a.firstLine()&&a.addSelection(k(e.head.line-1,e.head.ch))}})};e[b["Shift-Alt-Down"]="selectLinesDownward"]=function(a){a.operation(function(){for(var b=a.listSelections(),
d=0;d<b.length;d++){var e=b[d];e.head.line<a.lastLine()&&a.addSelection(k(e.head.line+1,e.head.ch))}})};e[b[g+"F3"]="findUnder"]=function(a){z(a,!0)};e[b["Shift-"+g+"F3"]="findUnderPrevious"]=function(a){z(a,!1)};e[b["Alt-F3"]="findAllUnder"]=function(a){var b=y(a);if(b){for(var d=a.getSearchCursor(b.query),e=[],g=-1;d.findNext();)e.push({anchor:d.from(),head:d.to()}),d.from().line<=b.from.line&&d.from().ch<=b.from.ch&&g++;a.setSelections(e,g)}};b["Shift-"+g+"["]="fold";b["Shift-"+g+"]"]="unfold";
b[l+g+"0"]=b[l+g+"j"]="unfoldAll";b[g+"I"]="findIncremental";b["Shift-"+g+"I"]="findIncrementalReverse";b[g+"H"]="replace";b.F3="findNext";b["Shift-F3"]="findPrev";n.normalizeKeyMap(b)});
