'use strict';var $jscomp={scope:{},findInternal:function(e,q,p){e instanceof String&&(e=String(e));for(var r=e.length,t=0;t<r;t++){var w=e[t];if(q.call(p,w,t,e))return{i:t,v:w}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,q,p){if(p.get||p.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[q]=p.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,q,p,r){if(q){p=$jscomp.global;e=e.split(".");for(r=0;r<e.length-1;r++){var t=e[r];t in p||(p[t]={});p=p[t]}e=e[e.length-1];r=p[e];q=q(r);q!=r&&null!=q&&$jscomp.defineProperty(p,e,{configurable:!0,writable:!0,value:q})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,p){return $jscomp.findInternal(this,e,p).v}},"es6-impl","es3");
(function(e){"object"==typeof exports&&"object"==typeof module?e(require("../lib/codemirror"),require("../addon/search/searchcursor"),require("../addon/edit/matchbrackets")):"function"==typeof define&&define.amd?define(["../lib/codemirror","../addon/search/searchcursor","../addon/edit/matchbrackets"],e):e(CodeMirror)})(function(e){function q(a,d){a.extendSelectionsBy(function(c){if(a.display.shift||a.doc.extend||c.empty()){var g;var m=a.doc;c=c.head;if(0>d&&0==c.ch)g=m.clipPos(l(c.line-1));else{var x=
m.getLine(c.line);if(0<d&&c.ch>=x.length)g=m.clipPos(l(c.line+1,0));else{for(var m="start",b=c.ch,f=0>d?0:x.length,h=0;b!=f;b+=d,h++){var k=x.charAt(0>d?b-1:b),v="_"!=k&&e.isWordChar(k)?"w":"o";"w"==v&&k.toUpperCase()==k&&(v="W");if("start"==m)"o"!=v&&(m="in",g=v);else if("in"==m&&g!=v)if("w"==g&&"W"==v&&0>d&&b--,"W"==g&&"w"==v&&0<d)g="w";else break}g=l(c.line,b)}}return g}return 0>d?c.from():c.to()})}function p(a,d){if(a.isReadOnly())return e.Pass;a.operation(function(){for(var c=a.listSelections().length,
g=[],m=-1,b=0;b<c;b++){var e=a.listSelections()[b].head;e.line<=m||(m=l(e.line+(d?0:1),0),a.replaceRange("\n",m,null,"+insertLine"),a.indentLine(m.line,null,!0),g.push({head:m,anchor:m}),m=e.line+1)}a.setSelections(g)});a.execCommand("indentAuto")}function r(a,d){var c=d.ch,g=c;for(a=a.getLine(d.line);c&&e.isWordChar(a.charAt(c-1));)--c;for(;g<a.length&&e.isWordChar(a.charAt(g));)++g;return{from:l(d.line,c),to:l(d.line,g),word:a.slice(c,g)}}function t(a){for(var d=a.listSelections(),c=[],g=0;g<d.length;g++){var m=
d[g].head,b=a.scanForBracket(m,-1);if(!b)return!1;for(;;){m=a.scanForBracket(m,1);if(!m)return!1;if(m.ch=="(){}[]".charAt("(){}[]".indexOf(b.ch)+1)){c.push({anchor:l(b.pos.line,b.pos.ch+1),head:m.pos});break}m=l(m.pos.line,m.pos.ch+1)}}a.setSelections(c);return!0}function w(a,d){if(a.isReadOnly())return e.Pass;for(var c=a.listSelections(),g=[],m,b=0;b<c.length;b++){var n=c[b];if(!n.empty()){for(var f=n.from().line,h=n.to().line;b<c.length-1&&c[b+1].from().line==h;)h=n[++b].to().line;g.push(f,h)}}g.length?
m=!0:g.push(a.firstLine(),a.lastLine());a.operation(function(){for(var c=[],b=0;b<g.length;b+=2){var e=g[b+1],f=l(g[b],0),e=l(e),n=a.getRange(f,e,!1);d?n.sort():n.sort(function(a,c){var d=a.toUpperCase(),g=c.toUpperCase();d!=g&&(a=d,c=g);return a<c?-1:a==c?0:1});a.replaceRange(n,f,e);m&&c.push({anchor:f,head:e})}m&&a.setSelections(c,0)})}function y(a,d){a.operation(function(){for(var c=a.listSelections(),g=[],b=[],f=0;f<c.length;f++){var n=c[f];n.empty()?(g.push(f),b.push("")):b.push(d(a.getRange(n.from(),
n.to())))}a.replaceSelections(b,"around","case");for(var f=g.length-1,h;0<=f;f--)n=c[g[f]],h&&0<e.cmpPos(n.head,h)||(b=r(a,n.head),h=b.from,a.replaceRange(d(b.word),b.from,b.to))})}function z(a){var d=a.getCursor("from"),c=a.getCursor("to");if(0==e.cmpPos(d,c)){var g=r(a,d);if(!g.word)return;d=g.from;c=g.to}return{from:d,to:c,query:a.getRange(d,c),word:g}}function A(a,d){var c=z(a);if(c){var g=c.query,b=a.getSearchCursor(g,d?c.to:c.from);(d?b.findNext():b.findPrevious())?a.setSelection(b.from(),b.to()):
(b=a.getSearchCursor(g,d?l(a.firstLine(),0):a.clipPos(l(a.lastLine()))),(d?b.findNext():b.findPrevious())?a.setSelection(b.from(),b.to()):c.word&&a.setSelection(c.from,c.to))}}var b=e.keyMap.sublime={fallthrough:"default"},f=e.commands,l=e.Pos,u=e.keyMap["default"]==e.keyMap.macDefault,h=u?"Cmd-":"Ctrl-",k=u?"Ctrl-":"Alt-";f[b[k+"Left"]="goSubwordLeft"]=function(a){q(a,-1)};f[b[k+"Right"]="goSubwordRight"]=function(a){q(a,1)};u&&(b["Cmd-Left"]="goLineStartSmart");k=u?"Ctrl-Alt-":"Ctrl-";f[b[k+"Up"]=
"scrollLineUp"]=function(a){var d=a.getScrollInfo();if(!a.somethingSelected()){var c=a.lineAtHeight(d.top+d.clientHeight,"local");a.getCursor().line>=c&&a.execCommand("goLineUp")}a.scrollTo(null,d.top-a.defaultTextHeight())};f[b[k+"Down"]="scrollLineDown"]=function(a){var d=a.getScrollInfo();if(!a.somethingSelected()){var c=a.lineAtHeight(d.top,"local")+1;a.getCursor().line<=c&&a.execCommand("goLineDown")}a.scrollTo(null,d.top+a.defaultTextHeight())};f[b["Shift-"+h+"L"]="splitSelectionByLine"]=function(a){for(var d=
a.listSelections(),c=[],g=0;g<d.length;g++)for(var b=d[g].from(),e=d[g].to(),f=b.line;f<=e.line;++f)e.line>b.line&&f==e.line&&0==e.ch||c.push({anchor:f==b.line?b:l(f,0),head:f==e.line?e:l(f)});a.setSelections(c,0)};b["Shift-Tab"]="indentLess";f[b.Esc="singleSelectionTop"]=function(a){var d=a.listSelections()[0];a.setSelection(d.anchor,d.head,{scroll:!1})};f[b[h+"L"]="selectLine"]=function(a){for(var d=a.listSelections(),c=[],g=0;g<d.length;g++){var b=d[g];c.push({anchor:l(b.from().line,0),head:l(b.to().line+
1,0)})}a.setSelections(c)};b["Shift-Ctrl-K"]="deleteLine";f[b[h+"Enter"]="insertLineAfter"]=function(a){return p(a,!1)};f[b["Shift-"+h+"Enter"]="insertLineBefore"]=function(a){return p(a,!0)};f[b[h+"D"]="selectNextOccurrence"]=function(a){var d=a.getCursor("from"),c=a.getCursor("to"),b=a.state.sublimeFindFullWord==a.doc.sel;if(0==e.cmpPos(d,c)){b=r(a,d);if(!b.word)return;a.setSelection(b.from,b.to);b=!0}else d=a.getRange(d,c),d=b?new RegExp("\\b"+d+"\\b"):d,c=a.getSearchCursor(d,c),c.findNext()?a.addSelection(c.from(),
c.to()):(c=a.getSearchCursor(d,l(a.firstLine(),0)),c.findNext()&&a.addSelection(c.from(),c.to()));b&&(a.state.sublimeFindFullWord=a.doc.sel)};f[b["Shift-"+h+"Space"]="selectScope"]=function(a){t(a)||a.execCommand("selectAll")};f[b["Shift-"+h+"M"]="selectBetweenBrackets"]=function(a){if(!t(a))return e.Pass};f[b[h+"M"]="goToBracket"]=function(a){a.extendSelectionsBy(function(d){var c=a.scanForBracket(d.head,1);return c&&0!=e.cmpPos(c.pos,d.head)?c.pos:(c=a.scanForBracket(d.head,-1))&&l(c.pos.line,c.pos.ch+
1)||d.head})};k=u?"Cmd-Ctrl-":"Shift-Ctrl-";f[b[k+"Up"]="swapLineUp"]=function(a){if(a.isReadOnly())return e.Pass;for(var d=a.listSelections(),c=[],b=a.firstLine()-1,f=[],h=0;h<d.length;h++){var n=d[h],k=n.from().line-1,p=n.to().line;f.push({anchor:l(n.anchor.line-1,n.anchor.ch),head:l(n.head.line-1,n.head.ch)});0!=n.to().ch||n.empty()||--p;k>b?c.push(k,p):c.length&&(c[c.length-1]=p);b=p}a.operation(function(){for(var d=0;d<c.length;d+=2){var b=c[d],g=c[d+1],e=a.getLine(b);a.replaceRange("",l(b,0),
l(b+1,0),"+swapLine");g>a.lastLine()?a.replaceRange("\n"+e,l(a.lastLine()),null,"+swapLine"):a.replaceRange(e+"\n",l(g,0),null,"+swapLine")}a.setSelections(f);a.scrollIntoView()})};f[b[k+"Down"]="swapLineDown"]=function(a){if(a.isReadOnly())return e.Pass;for(var d=a.listSelections(),c=[],b=a.lastLine()+1,f=d.length-1;0<=f;f--){var h=d[f],n=h.to().line+1,k=h.from().line;0!=h.to().ch||h.empty()||n--;n<b?c.push(n,k):c.length&&(c[c.length-1]=k);b=k}a.operation(function(){for(var d=c.length-2;0<=d;d-=
2){var b=c[d],g=c[d+1],e=a.getLine(b);b==a.lastLine()?a.replaceRange("",l(b-1),l(b),"+swapLine"):a.replaceRange("",l(b,0),l(b+1,0),"+swapLine");a.replaceRange(e+"\n",l(g,0),null,"+swapLine")}a.scrollIntoView()})};f[b[h+"/"]="toggleCommentIndented"]=function(a){a.toggleComment({indent:!0})};f[b[h+"J"]="joinLines"]=function(a){for(var d=a.listSelections(),c=[],b=0;b<d.length;b++){for(var e=d[b],f=e.from(),h=f.line,k=e.to().line;b<d.length-1&&d[b+1].from().line==k;)k=d[++b].to().line;c.push({start:h,
end:k,anchor:!e.empty()&&f})}a.operation(function(){for(var d=0,b=[],g=0;g<c.length;g++){for(var e=c[g],f=e.anchor&&l(e.anchor.line-d,e.anchor.ch),h,m=e.start;m<=e.end;m++){var k=m-d;m==e.end&&(h=l(k,a.getLine(k).length+1));k<a.lastLine()&&(a.replaceRange(" ",l(k),l(k+1,/^\s*/.exec(a.getLine(k+1))[0].length)),++d)}b.push({anchor:f||h,head:h})}a.setSelections(b,0)})};f[b["Shift-"+h+"D"]="duplicateLine"]=function(a){a.operation(function(){for(var d=a.listSelections().length,c=0;c<d;c++){var b=a.listSelections()[c];
b.empty()?a.replaceRange(a.getLine(b.head.line)+"\n",l(b.head.line,0)):a.replaceRange(a.getRange(b.from(),b.to()),b.from())}a.scrollIntoView()})};u||(b[h+"T"]="transposeChars");f[b.F9="sortLines"]=function(a){w(a,!0)};f[b[h+"F9"]="sortLinesInsensitive"]=function(a){w(a,!1)};f[b.F2="nextBookmark"]=function(a){var d=a.state.sublimeBookmarks;if(d)for(;d.length;){var b=d.shift(),g=b.find();if(g)return d.push(b),a.setSelection(g.from,g.to)}};f[b["Shift-F2"]="prevBookmark"]=function(a){var d=a.state.sublimeBookmarks;
if(d)for(;d.length;){d.unshift(d.pop());var b=d[d.length-1].find();if(b)return a.setSelection(b.from,b.to);d.pop()}};f[b[h+"F2"]="toggleBookmark"]=function(a){for(var b=a.listSelections(),c=a.state.sublimeBookmarks||(a.state.sublimeBookmarks=[]),g=0;g<b.length;g++){for(var e=b[g].from(),f=b[g].to(),h=a.findMarks(e,f),k=0;k<h.length;k++)if(h[k].sublimeBookmark){h[k].clear();for(var l=0;l<c.length;l++)c[l]==h[k]&&c.splice(l--,1);break}k==h.length&&c.push(a.markText(e,f,{sublimeBookmark:!0,clearWhenEmpty:!1}))}};
f[b["Shift-"+h+"F2"]="clearBookmarks"]=function(a){if(a=a.state.sublimeBookmarks)for(var b=0;b<a.length;b++)a[b].clear();a.length=0};f[b["Alt-F2"]="selectBookmarks"]=function(a){var b=a.state.sublimeBookmarks,c=[];if(b)for(var g=0;g<b.length;g++){var e=b[g].find();e?c.push({anchor:e.from,head:e.to}):b.splice(g--,0)}c.length&&a.setSelections(c,0)};b["Alt-Q"]="wrapLines";k=h+"K ";b[k+h+"Backspace"]="delLineLeft";f[b.Backspace="smartBackspace"]=function(a){if(a.somethingSelected())return e.Pass;a.operation(function(){for(var b=
a.listSelections(),c=a.getOption("indentUnit"),g=b.length-1;0<=g;g--){var f=b[g].head,h=a.getRange({line:f.line,ch:0},f),k=e.countColumn(h,null,a.getOption("tabSize")),p=a.findPosH(f,-1,"char",!1);h&&!/\S/.test(h)&&0==k%c&&(h=new l(f.line,e.findColumn(h,k-c,c)),h.ch!=f.ch&&(p=h));a.replaceRange("",p,f,"+delete")}})};f[b[k+h+"K"]="delLineRight"]=function(a){a.operation(function(){for(var b=a.listSelections(),c=b.length-1;0<=c;c--)a.replaceRange("",b[c].anchor,l(b[c].to().line),"+delete");a.scrollIntoView()})};
f[b[k+h+"U"]="upcaseAtCursor"]=function(a){y(a,function(a){return a.toUpperCase()})};f[b[k+h+"L"]="downcaseAtCursor"]=function(a){y(a,function(a){return a.toLowerCase()})};f[b[k+h+"Space"]="setSublimeMark"]=function(a){a.state.sublimeMark&&a.state.sublimeMark.clear();a.state.sublimeMark=a.setBookmark(a.getCursor())};f[b[k+h+"A"]="selectToSublimeMark"]=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&a.setSelection(a.getCursor(),b)};f[b[k+h+"W"]="deleteToSublimeMark"]=function(a){var b=
a.state.sublimeMark&&a.state.sublimeMark.find();if(b){var c=a.getCursor();if(0<e.cmpPos(c,b))var g=b,b=c,c=g;a.state.sublimeKilled=a.getRange(c,b);a.replaceRange("",c,b)}};f[b[k+h+"X"]="swapWithSublimeMark"]=function(a){var b=a.state.sublimeMark&&a.state.sublimeMark.find();b&&(a.state.sublimeMark.clear(),a.state.sublimeMark=a.setBookmark(a.getCursor()),a.setCursor(b))};f[b[k+h+"Y"]="sublimeYank"]=function(a){null!=a.state.sublimeKilled&&a.replaceSelection(a.state.sublimeKilled,null,"paste")};b[k+
h+"G"]="clearBookmarks";f[b[k+h+"C"]="showInCenter"]=function(a){var b=a.cursorCoords(null,"local");a.scrollTo(null,(b.top+b.bottom)/2-a.getScrollInfo().clientHeight/2)};u=u?"Ctrl-Shift-":"Ctrl-Alt-";f[b[u+"Up"]="selectLinesUpward"]=function(a){a.operation(function(){for(var b=a.listSelections(),c=0;c<b.length;c++){var e=b[c];e.head.line>a.firstLine()&&a.addSelection(l(e.head.line-1,e.head.ch))}})};f[b[u+"Down"]="selectLinesDownward"]=function(a){a.operation(function(){for(var b=a.listSelections(),
c=0;c<b.length;c++){var e=b[c];e.head.line<a.lastLine()&&a.addSelection(l(e.head.line+1,e.head.ch))}})};f[b[h+"F3"]="findUnder"]=function(a){A(a,!0)};f[b["Shift-"+h+"F3"]="findUnderPrevious"]=function(a){A(a,!1)};f[b["Alt-F3"]="findAllUnder"]=function(a){var b=z(a);if(b){for(var c=a.getSearchCursor(b.query),e=[],f=-1;c.findNext();)e.push({anchor:c.from(),head:c.to()}),c.from().line<=b.from.line&&c.from().ch<=b.from.ch&&f++;a.setSelections(e,f)}};b["Shift-"+h+"["]="fold";b["Shift-"+h+"]"]="unfold";
b[k+h+"0"]=b[k+h+"J"]="unfoldAll";b[h+"I"]="findIncremental";b["Shift-"+h+"I"]="findIncrementalReverse";b[h+"H"]="replace";b.F3="findNext";b["Shift-F3"]="findPrev";e.normalizeKeyMap(b)});
