'use strict';(function(d){"object"==typeof exports&&"object"==typeof module?d(require("codemirror")):"function"==typeof define&&define.amd?define(["codemirror"],d):d(window.CodeMirror)})(function(d){d.defineMode("powershell",function(){function d(b,a){a=a||{};for(var c=void 0!==a.prefix?a.prefix:"^",t=void 0!==a.suffix?a.suffix:"\\b",e=0;e<b.length;e++)b[e]=b[e]instanceof RegExp?b[e].source:b[e].replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&");return new RegExp(c+"("+b.join("|")+")"+t,"i")}function e(b,a){var c=
a.returnStack[a.returnStack.length-1];if(c&&c.shouldReturnFrom(a))return a.tokenize=c.tokenize,a.returnStack.pop(),a.tokenize(b,a);if(b.eatSpace())return null;if(b.eat("("))return a.bracketNesting+=1,"punctuation";if(b.eat(")"))return--a.bracketNesting,"punctuation";for(var d in m)if(b.match(m[d]))return d;c=b.next();if("'"===c){a:{for(;null!=(c=b.peek());)if(b.next(),"'"===c&&!b.eat("'")){a.tokenize=e;c="string";break a}c="error"}return c}if("$"===c)return g(b,a);if('"'===c)return n(b,a);if("<"===
c&&b.eat("#"))return a.tokenize=p,p(b,a);if("#"===c)return b.skipToEnd(),"comment";if("@"===c){if((c=b.eat(/["']/))&&b.eol())return a.tokenize=f,a.startQuote=c[0],f(b,a);if(b.peek().match(/[({]/))return"punctuation";if(b.peek().match(h))return g(b,a)}return"error"}function n(b,a){for(var c;null!=(c=b.peek());){if("$"===c)return a.tokenize=u,"string";b.next();if("`"===c)b.next();else if('"'===c&&!b.eat('"'))return a.tokenize=e,"string"}return"error"}function u(b,a){return q(b,a,n)}function v(b,a){a.tokenize=
f;a.startQuote='"';return f(b,a)}function w(b,a){return q(b,a,v)}function q(b,a,c){if(b.match("$(")){var d=a.bracketNesting;a.returnStack.push({shouldReturnFrom:function(a){return a.bracketNesting===d},tokenize:c});a.tokenize=e;a.bracketNesting+=1;return"punctuation"}b.next();a.returnStack.push({shouldReturnFrom:function(){return!0},tokenize:c});a.tokenize=g;return a.tokenize(b,a)}function p(b,a){for(var c=!1,d;null!=(d=b.next());){if(c&&">"==d){a.tokenize=e;break}c="#"===d}return"comment"}function g(b,
a){var c=b.peek();if(b.eat("{"))return a.tokenize=r,r(b,a);if(void 0!=c&&c.match(h))return b.eatWhile(h),a.tokenize=e,"variable-2";a.tokenize=e;return"error"}function r(b,a){for(var c;null!=(c=b.next());)if("}"===c){a.tokenize=e;break}return"variable-2"}function f(b,a){var c=a.startQuote;if(b.sol()&&b.match(new RegExp(c+"@")))a.tokenize=e;else if('"'===c)for(;!b.eol();){c=b.peek();if("$"===c){a.tokenize=w;break}b.next();"`"===c&&b.next()}else b.skipToEnd();return"string"}var h=/[\w\-:]/,x=d([/begin|break|catch|continue|data|default|do|dynamicparam/,
/else|elseif|end|exit|filter|finally|for|foreach|from|function|if|in/,/param|process|return|switch|throw|trap|try|until|where|while/],{suffix:"(?=[^A-Za-z\\d\\-_]|$)"}),k=d(["f",/b?not/,/[ic]?split/,"join",/is(not)?/,"as",/[ic]?(eq|ne|[gl][te])/,/[ic]?(not)?(like|match|contains)/,/[ic]?replace/,/b?(and|or|xor)/],{prefix:"-"}),k=d([k,/[+\-*\/%]=|\+\+|--|\.\.|[+\-*&^%:=!|\/]|<(?!#)|(?!#)>/],{suffix:""}),l=d([/Add-(Computer|Content|History|Member|PSSnapin|Type)/,/Checkpoint-Computer/,/Clear-(Content|EventLog|History|Host|Item(Property)?|Variable)/,
/Compare-Object/,/Complete-Transaction/,/Connect-PSSession/,/ConvertFrom-(Csv|Json|SecureString|StringData)/,/Convert-Path/,/ConvertTo-(Csv|Html|Json|SecureString|Xml)/,/Copy-Item(Property)?/,/Debug-Process/,/Disable-(ComputerRestore|PSBreakpoint|PSRemoting|PSSessionConfiguration)/,/Disconnect-PSSession/,/Enable-(ComputerRestore|PSBreakpoint|PSRemoting|PSSessionConfiguration)/,/(Enter|Exit)-PSSession/,/Export-(Alias|Clixml|Console|Counter|Csv|FormatData|ModuleMember|PSSession)/,/ForEach-Object/,/Format-(Custom|List|Table|Wide)/,
/Get-(Acl|Alias|AuthenticodeSignature|ChildItem|Command|ComputerRestorePoint|Content|ControlPanelItem|Counter|Credential|Culture|Date|Event|EventLog|EventSubscriber|ExecutionPolicy|FormatData|Help|History|Host|HotFix|Item|ItemProperty|Job|Location|Member|Module|PfxCertificate|Process|PSBreakpoint|PSCallStack|PSDrive|PSProvider|PSSession|PSSessionConfiguration|PSSnapin|Random|Service|TraceSource|Transaction|TypeData|UICulture|Unique|Variable|Verb|WinEvent|WmiObject)/,/Group-Object/,/Import-(Alias|Clixml|Counter|Csv|LocalizedData|Module|PSSession)/,
/ImportSystemModules/,/Invoke-(Command|Expression|History|Item|RestMethod|WebRequest|WmiMethod)/,/Join-Path/,/Limit-EventLog/,/Measure-(Command|Object)/,/Move-Item(Property)?/,/New-(Alias|Event|EventLog|Item(Property)?|Module|ModuleManifest|Object|PSDrive|PSSession|PSSessionConfigurationFile|PSSessionOption|PSTransportOption|Service|TimeSpan|Variable|WebServiceProxy|WinEvent)/,/Out-(Default|File|GridView|Host|Null|Printer|String)/,/Pause/,/(Pop|Push)-Location/,/Read-Host/,/Receive-(Job|PSSession)/,
/Register-(EngineEvent|ObjectEvent|PSSessionConfiguration|WmiEvent)/,/Remove-(Computer|Event|EventLog|Item(Property)?|Job|Module|PSBreakpoint|PSDrive|PSSession|PSSnapin|TypeData|Variable|WmiObject)/,/Rename-(Computer|Item(Property)?)/,/Reset-ComputerMachinePassword/,/Resolve-Path/,/Restart-(Computer|Service)/,/Restore-Computer/,/Resume-(Job|Service)/,/Save-Help/,/Select-(Object|String|Xml)/,/Send-MailMessage/,/Set-(Acl|Alias|AuthenticodeSignature|Content|Date|ExecutionPolicy|Item(Property)?|Location|PSBreakpoint|PSDebug|PSSessionConfiguration|Service|StrictMode|TraceSource|Variable|WmiInstance)/,
/Show-(Command|ControlPanelItem|EventLog)/,/Sort-Object/,/Split-Path/,/Start-(Job|Process|Service|Sleep|Transaction|Transcript)/,/Stop-(Computer|Job|Process|Service|Transcript)/,/Suspend-(Job|Service)/,/TabExpansion2/,/Tee-Object/,/Test-(ComputerSecureChannel|Connection|ModuleManifest|Path|PSSessionConfigurationFile)/,/Trace-Command/,/Unblock-File/,/Undo-Transaction/,/Unregister-(Event|PSSessionConfiguration)/,/Update-(FormatData|Help|List|TypeData)/,/Use-Transaction/,/Wait-(Event|Job|Process)/,/Where-Object/,
/Write-(Debug|Error|EventLog|Host|Output|Progress|Verbose|Warning)/,/cd|help|mkdir|more|oss|prompt/,/ac|asnp|cat|cd|chdir|clc|clear|clhy|cli|clp|cls|clv|cnsn|compare|copy|cp|cpi|cpp|cvpa|dbp|del|diff|dir|dnsn|ebp/,/echo|epal|epcsv|epsn|erase|etsn|exsn|fc|fl|foreach|ft|fw|gal|gbp|gc|gci|gcm|gcs|gdr|ghy|gi|gjb|gl|gm|gmo|gp|gps/,/group|gsn|gsnp|gsv|gu|gv|gwmi|h|history|icm|iex|ihy|ii|ipal|ipcsv|ipmo|ipsn|irm|ise|iwmi|iwr|kill|lp|ls|man|md/,/measure|mi|mount|move|mp|mv|nal|ndr|ni|nmo|npssc|nsn|nv|ogv|oh|popd|ps|pushd|pwd|r|rbp|rcjb|rcsn|rd|rdr|ren|ri/,
/rjb|rm|rmdir|rmo|rni|rnp|rp|rsn|rsnp|rujb|rv|rvpa|rwmi|sajb|sal|saps|sasv|sbp|sc|select|set|shcm|si|sl|sleep|sls/,/sort|sp|spjb|spps|spsv|start|sujb|sv|swmi|tee|trcm|type|where|wjb|write/],{prefix:"",suffix:""}),y=d([/[$?^_]|Args|ConfirmPreference|ConsoleFileName|DebugPreference|Error|ErrorActionPreference|ErrorView|ExecutionContext/,/FormatEnumerationLimit|Home|Host|Input|MaximumAliasCount|MaximumDriveCount|MaximumErrorCount|MaximumFunctionCount/,/MaximumHistoryCount|MaximumVariableCount|MyInvocation|NestedPromptLevel|OutputEncoding|Pid|Profile|ProgressPreference/,
/PSBoundParameters|PSCommandPath|PSCulture|PSDefaultParameterValues|PSEmailServer|PSHome|PSScriptRoot|PSSessionApplicationName/,/PSSessionConfigurationName|PSSessionOption|PSUICulture|PSVersionTable|Pwd|ShellId|StackTrace|VerbosePreference/,/WarningPreference|WhatIfPreference/,/Event|EventArgs|EventSubscriber|Sender/,/Matches|Ofs|ForEach|LastExitCode|PSCmdlet|PSItem|PSSenderInfo|This/,/true|false|null/],{prefix:"\\$",suffix:""}),l=d([/[A-Z]:|%|\?/i,l,y],{suffix:"(?=[^A-Za-z\\d\\-_]|$)"}),m={keyword:x,
number:/^((0x[\da-f]+)|((\d+\.\d+|\d\.|\.\d+|\d+)(e[\+\-]?\d+)?))[ld]?([kmgtp]b)?/i,operator:k,builtin:l,punctuation:/[\[\]{},;`\.]|@[({]/,identifier:/^[A-Za-z\_][A-Za-z\-\_\d]*\b/};return{startState:function(){return{returnStack:[],bracketNesting:0,tokenize:e}},token:function(b,a){return a.tokenize(b,a)},blockCommentStart:"<#",blockCommentEnd:"#>",lineComment:"#",fold:"brace"}});d.defineMIME("application/x-powershell","powershell")});
