'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var f=0;return function(){return f<c.length?{done:!1,value:c[f++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.ENABLE_UNHANDLED_REJECTION_POLYFILL=!0;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,f,h){if(c==Array.prototype||c==Object.prototype)return c;c[f]=h.value;return c};$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var f=0;f<c.length;++f){var h=c[f];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,f){var h=$jscomp.propertyToPolyfillSymbol[f];if(null==h)return c[f];h=c[h];return void 0!==h?h:c[f]};
$jscomp.polyfill=function(c,f,h,k){f&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,f,h,k):$jscomp.polyfillUnisolated(c,f,h,k))};$jscomp.polyfillUnisolated=function(c,f,h,k){h=$jscomp.global;c=c.split(".");for(k=0;k<c.length-1;k++){var e=c[k];if(!(e in h))return;h=h[e]}c=c[c.length-1];k=h[c];f=f(k);f!=k&&null!=f&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:f})};
$jscomp.polyfillIsolated=function(c,f,h,k){var e=c.split(".");c=1===e.length;k=e[0];k=!c&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<e.length-1;l++){var n=e[l];if(!(n in k))return;k=k[n]}e=e[e.length-1];h=$jscomp.IS_SYMBOL_NATIVE&&"es6"===h?k[e]:null;f=f(h);null!=f&&(c?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:f}):f!==h&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(k,e,{configurable:!0,writable:!0,value:f})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(c){if(c)return c;var f=function(e,l){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};f.prototype.toString=function(){return this.$jscomp$symbol$id_};var h=0,k=function(e){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new f("jscomp_symbol_"+(e||"")+"_"+h++,e)};return k},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var f="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),h=0;h<f.length;h++){var k=$jscomp.global[f[h]];"function"===typeof k&&"function"!=typeof k.prototype[c]&&$jscomp.defineProperty(k.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return c},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,f){c instanceof String&&(c+="");var h=0,k=!1,e={next:function(){if(!k&&h<c.length){var l=h++;return{value:f(l,c[l]),done:!1}}k=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(f){return f})}},"es6","es3");
(function(c){"object"==typeof exports&&"object"==typeof module?c(require("../../lib/codemirror"),require("../htmlmixed/htmlmixed")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../htmlmixed/htmlmixed"],c):c(CodeMirror)})(function(c){var f={noEndTag:!0,soyState:"param-def"},h={alias:{noEndTag:!0},delpackage:{noEndTag:!0},namespace:{noEndTag:!0,soyState:"namespace-def"},"@param":f,"@param?":f,"@inject":f,"@inject?":f,"@state":f,template:{soyState:"templ-def",variableScope:!0},
literal:{},msg:{},fallbackmsg:{noEndTag:!0,reduceIndent:!0},select:{},plural:{},let:{soyState:"var-def"},"if":{},elseif:{noEndTag:!0,reduceIndent:!0},"else":{noEndTag:!0,reduceIndent:!0},"switch":{},"case":{noEndTag:!0,reduceIndent:!0},"default":{noEndTag:!0,reduceIndent:!0},foreach:{variableScope:!0,soyState:"for-loop"},ifempty:{noEndTag:!0,reduceIndent:!0},"for":{variableScope:!0,soyState:"for-loop"},call:{soyState:"templ-ref"},param:{soyState:"param-ref"},print:{noEndTag:!0},deltemplate:{soyState:"templ-def",
variableScope:!0},delcall:{soyState:"templ-ref"},log:{},element:{variableScope:!0}},k=Object.keys(h).filter(function(e){return!h[e].noEndTag||h[e].reduceIndent});c.defineMode("soy",function(e){function l(b){return b[b.length-1]}function n(b,a,d){if(b.sol()){for(var g=0;g<a.indent&&b.eat(/\s/);g++);if(g)return null}g=b.string;if(d=d.exec(g.substr(b.pos)))b.string=g.substr(0,b.pos+d.index);d=b.hideFirstChars(a.indent,function(){var m=l(a.localStates);return m.mode.token(b,m.state)});b.string=g;return d}
function p(b,a){return{element:a,next:b}}function u(b){b.context&&(b.context.scope&&(b.variables=b.context.scope),b.context=b.context.previousContext)}function w(b,a,d){a:{for(;b;){if(b.element===a){a=!0;break a}b=b.next}a=!1}return a?"variable-2":d?"variable":"variable-2 error"}function v(b,a,d){this.previousContext=b;this.tag=a;this.kind=null;this.scope=d}function q(b,a){var d;if(b.match(/[[]/))return a.soyState.push("list-literal"),a.context=new v(a.context,"list-literal",a.variables),a.lookupVariables=
!1,null;if(b.match(/map\b/))return a.soyState.push("map-literal"),"keyword";if(b.match(/record\b/))return a.soyState.push("record-literal"),"keyword";if(b.match(/([\w]+)(?=\()/))return"variable callee";if(d=b.match(/^["']/))return a.soyState.push("string"),a.quoteKind=d[0],"string";if(b.match(/^[(]/))return a.soyState.push("open-parentheses"),null;if(b.match(/(null|true|false)(?!\w)/)||b.match(/0x([0-9a-fA-F]{2,})/)||b.match(/-?([0-9]*[.])?[0-9]+(e[0-9]*)?/))return"atom";if(b.match(/(\||[+\-*\/%]|[=!]=|\?:|[<>]=?)/))return"operator";
if(d=b.match(/^\$([\w]+)/))return w(a.variables,d[1],!a.lookupVariables);if(d=b.match(/^\w+/))return/^(?:as|and|or|not|in|if)$/.test(d[0])?"keyword":null;b.next();return null}var r=c.getMode(e,"text/plain"),t={html:c.getMode(e,{name:"text/html",multilineTagIndentFactor:2,multilineTagIndentPastTag:!1}),attributes:r,text:r,uri:r,trusted_resource_uri:r,css:c.getMode(e,"text/css"),js:c.getMode(e,{name:"text/javascript",statementIndent:2*e.indentUnit})};return{startState:function(){return{soyState:[],
variables:p(null,"ij"),scopes:null,indent:0,quoteKind:null,context:null,lookupVariables:!0,localStates:[{mode:t.html,state:c.startState(t.html)}]}},copyState:function(b){return{tag:b.tag,soyState:b.soyState.concat([]),variables:b.variables,context:b.context,indent:b.indent,quoteKind:b.quoteKind,lookupVariables:b.lookupVariables,localStates:b.localStates.map(function(a){return{mode:a.mode,state:c.copyState(a.mode,a.state)}})}},token:function(b,a){var d;switch(l(a.soyState)){case "comment":b.match(/^.*?\*\//)?
a.soyState.pop():b.skipToEnd();if(!a.context||!a.context.scope)for(var g=/@param\??\s+(\S+)/g,m=b.current();d=g.exec(m);)a.variables=p(a.variables,d[1]);return"comment";case "string":return d=b.match(/^.*?(["']|\\[\s\S])/),d?d[1]==a.quoteKind&&(a.quoteKind=null,a.soyState.pop()):b.skipToEnd(),"string"}if(!a.soyState.length||"literal"!=l(a.soyState)){if(b.match(/^\/\*/))return a.soyState.push("comment"),"comment";if(b.match(b.sol()?/^\s*\/\/.*/:/^\s+\/\/.*/))return"comment"}switch(l(a.soyState)){case "templ-def":if(b.match(/^\.?([\w]+(?!\.[\w]+)*)/))return a.soyState.pop(),
"def";b.next();return null;case "templ-ref":if(d=b.match(/(\.?[a-zA-Z_][a-zA-Z_0-9]+)+/))return a.soyState.pop(),"."==d[0][0]?"variable-2":"variable";if(d=b.match(/^\$([\w]+)/))return a.soyState.pop(),w(a.variables,d[1],!a.lookupVariables);b.next();return null;case "namespace-def":if(b.match(/^\.?([\w\.]+)/))return a.soyState.pop(),"variable";b.next();return null;case "param-def":if(d=b.match(/^\w+/))return a.variables=p(a.variables,d[0]),a.soyState.pop(),a.soyState.push("param-type"),"def";b.next();
return null;case "param-ref":if(b.match(/^\w+/))return a.soyState.pop(),"property";b.next();return null;case "open-parentheses":return b.match(/[)]/)?(a.soyState.pop(),null):q(b,a);case "param-type":g=b.peek();if(-1!="}]=>,".indexOf(g))return a.soyState.pop(),null;if("["==g)return a.soyState.push("param-type-record"),null;if("("==g)return a.soyState.push("param-type-template"),null;if("<"==g)return a.soyState.push("param-type-parameter"),null;if(b.match(/^([\w]+|[?])/))return"type";b.next();return null;
case "param-type-record":g=b.peek();if("]"==g)return a.soyState.pop(),null;if(b.match(/^\w+/))return a.soyState.push("param-type"),"property";b.next();return null;case "param-type-parameter":if(b.match(/^[>]/))return a.soyState.pop(),null;if(b.match(/^[<,]/))return a.soyState.push("param-type"),null;b.next();return null;case "param-type-template":if(b.match(/[>]/))return a.soyState.pop(),a.soyState.push("param-type"),null;if(b.match(/^\w+/))return a.soyState.push("param-type"),"def";b.next();return null;
case "var-def":if(d=b.match(/^\$([\w]+)/))return a.variables=p(a.variables,d[1]),a.soyState.pop(),"def";b.next();return null;case "for-loop":if(b.match(/\bin\b/))return a.soyState.pop(),"keyword";if("$"==b.peek())return a.soyState.push("var-def"),null;b.next();return null;case "record-literal":if(b.match(/^[)]/))return a.soyState.pop(),null;if(b.match(/[(,]/))return a.soyState.push("map-value"),a.soyState.push("record-key"),null;b.next();return null;case "map-literal":if(b.match(/^[)]/))return a.soyState.pop(),
null;if(b.match(/[(,]/))return a.soyState.push("map-value"),a.soyState.push("map-value"),null;b.next();return null;case "list-literal":return b.match(/\]/)?(a.soyState.pop(),a.lookupVariables=!0,u(a),null):b.match(/\bfor\b/)?(a.lookupVariables=!0,a.soyState.push("for-loop"),"keyword"):q(b,a);case "record-key":if(b.match(/[\w]+/))return"property";if(b.match(/^[:]/))return a.soyState.pop(),null;b.next();return null;case "map-value":return")"==b.peek()||","==b.peek()||b.match(/^[:)]/)?(a.soyState.pop(),
null):q(b,a);case "import":if(b.eat(";"))return a.soyState.pop(),a.indent-=2*e.indentUnit,null;if(b.match(/\w+(?=\s+as)/))return"variable";if(d=b.match(/\w+/))return/(from|as)/.test(d[0])?"keyword":"def";if(d=b.match(/^["']/))return a.soyState.push("string"),a.quoteKind=d[0],"string";b.next();return null;case "tag":return m=(g="/"==a.tag[0])?a.tag.substring(1):a.tag,b.match(/^\/?}/)?((m="/}"==b.current())&&!g&&u(a),"/template"==a.tag||"/deltemplate"==a.tag?(a.variables=p(null,"ij"),a.indent=0):a.indent-=
e.indentUnit*(m||-1==k.indexOf(a.tag)?2:1),a.soyState.pop(),"keyword"):b.match(/^([\w?]+)(?==)/)?(a.context&&a.context.tag==m&&"kind"==b.current()&&(d=b.match(/^="([^"]+)/,!1))&&(g=d[1],a.context.kind=g,m=t[g]||t.html,g=l(a.localStates),g.mode.indent&&(a.indent+=g.mode.indent(g.state,"","")),a.localStates.push({mode:m,state:c.startState(m)})),"attribute"):q(b,a);case "literal":return b.match(/^(?=\{\/literal})/)?(a.soyState.pop(),this.token(b,a)):n(b,a,/\{\/literal}/)}if(b.match(/^\{literal}/))return a.indent+=
e.indentUnit,a.soyState.push("literal"),a.context=new v(a.context,"literal",a.variables),"keyword";if(d=b.match(/^\{([/@\\]?\w+\??)(?=$|[\s}]|\/[/*])/)){b=a.tag;a.tag=d[1];g="/"==a.tag[0];var x=!!h[a.tag];m=g?a.tag.substring(1):a.tag;d=h[m];"/switch"!=a.tag&&(a.indent+=((g||d&&d.reduceIndent)&&"switch"!=b?1:2)*e.indentUnit);a.soyState.push("tag");b=!1;d?(g||d.soyState&&a.soyState.push(d.soyState),d.noEndTag||!x&&g)?g&&(a.context&&a.context.tag==m?a.context&&(a.context.kind&&(a.localStates.pop(),g=
l(a.localStates),g.mode.indent&&(a.indent-=g.mode.indent(g.state,"",""))),u(a)):b=!0):a.context=new v(a.context,a.tag,d.variableScope?a.variables:null):g&&(b=!0);return(b?"error ":"")+"keyword"}return b.eat("{")?(a.tag="print",a.indent+=2*e.indentUnit,a.soyState.push("tag"),"keyword"):!a.context&&b.match(/\bimport\b/)?(a.soyState.push("import"),a.indent+=2*e.indentUnit,"keyword"):n(b,a,/\{|\s+\/\/|\/\*/)},indent:function(b,a,d){var g=b.indent,m=l(b.soyState);if("comment"==m)return c.Pass;if("literal"==
m)/^\{\/literal}/.test(a)&&(g-=e.indentUnit);else{if(/^\s*\{\/(template|deltemplate)\b/.test(a))return 0;/^\{(\/|(fallbackmsg|elseif|else|ifempty)\b)/.test(a)&&(g-=e.indentUnit);"switch"!=b.tag&&/^\{(case|default)\b/.test(a)&&(g-=e.indentUnit);/^\{\/switch\b/.test(a)&&(g-=e.indentUnit)}b=l(b.localStates);g&&b.mode.indent&&(g+=b.mode.indent(b.state,a,d));return g},innerMode:function(b){return b.soyState.length&&"literal"!=l(b.soyState)?null:l(b.localStates)},electricInput:/^\s*\{(\/|\/template|\/deltemplate|\/switch|fallbackmsg|elseif|else|case|default|ifempty|\/literal\})$/,
lineComment:"//",blockCommentStart:"/*",blockCommentEnd:"*/",blockCommentContinue:" * ",useInnerComments:!1,fold:"indent"}},"htmlmixed");c.registerHelper("wordChars","soy",/[\w$]/);c.registerHelper("hintWords","soy",Object.keys(h).concat(["css","debugger"]));c.defineMIME("text/x-soy","soy")});
