'use strict';(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],k):k(CodeMirror)})(function(k){function z(a,c,d){function e(f){if(!b.parentNode)return k.off(document,"mousemove",e);b.style.top=Math.max(0,f.clientY-b.offsetHeight-5)+"px";b.style.left=f.clientX+5+"px"}var b=document.createElement("div");b.className="CodeMirror-lint-tooltip cm-s-"+a.options.theme;b.appendChild(d.cloneNode(!0));
a.state.lint.options.selfContain?a.getWrapperElement().appendChild(b):document.body.appendChild(b);k.on(document,"mousemove",e);e(c);null!=b.style.opacity&&(b.style.opacity=1);return b}function A(a){a.parentNode&&(null==a.style.opacity&&a.parentNode&&a.parentNode.removeChild(a),a.style.opacity=0,setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},600))}function t(a,c,d,e){function b(){k.off(e,"mouseout",b);f&&(A(f),f=null)}var f=z(a,c,d),h=setInterval(function(){if(f)for(var g=e;;g=g.parentNode){g&&
11==g.nodeType&&(g=g.host);if(g==document.body)return;if(!g){b();break}}if(!f)return clearInterval(h)},400);k.on(e,"mouseout",b)}function B(a,c,d){this.marked=[];this.options=c;this.timeout=null;this.hasGutter=d;this.onMouseOver=function(e){var b=e.target||e.srcElement;if(/\bCodeMirror-lint-mark-/.test(b.className)){b=b.getBoundingClientRect();var f=a.findMarksAt(a.coordsChar({left:(b.left+b.right)/2,top:(b.top+b.bottom)/2},"client"));b=[];for(var h=0;h<f.length;++h){var g=f[h].__annotation;g&&b.push(g)}if(b.length){f=
e.target||e.srcElement;h=document.createDocumentFragment();for(g=0;g<b.length;g++)h.appendChild(u(b[g]));t(a,e,h,f)}}};this.waitingFor=0}function v(a){var c=a.state.lint;c.hasGutter&&a.clearGutter("CodeMirror-lint-markers");for(a=0;a<c.marked.length;++a)c.marked[a].clear();c.marked.length=0}function C(a,c,d,e,b){var f=document.createElement("div"),h=f;f.className="CodeMirror-lint-marker CodeMirror-lint-marker-"+d;e&&(h=f.appendChild(document.createElement("div")),h.className="CodeMirror-lint-marker CodeMirror-lint-marker-multiple");
if(0!=b)k.on(h,"mouseover",function(g){t(a,g,c,h)});return f}function D(a){for(var c=[],d=0;d<a.length;++d){var e=a[d],b=e.from.line;(c[b]||(c[b]=[])).push(e)}return c}function u(a){var c=a.severity;c||(c="error");var d=document.createElement("div");d.className="CodeMirror-lint-message CodeMirror-lint-message-"+c;"undefined"!=typeof a.messageHTML?d.innerHTML=a.messageHTML:d.appendChild(document.createTextNode(a.message));return d}function E(a,c,d){function e(){f=-1;a.off("change",e)}var b=a.state.lint,
f=++b.waitingFor;a.on("change",e);c(a.getValue(),function(h,g){a.off("change",e);b.waitingFor==f&&(g&&h instanceof k&&(h=g),a.operation(function(){n(a,h)}))},d,a)}function p(a){var c=a.state.lint.options,d=c.options||c,e=c.getAnnotations||a.getHelper(k.Pos(0,0),"lint");if(e)if(c.async||e.async)E(a,e,d);else{var b=e(a.getValue(),d,a);b&&(b.then?b.then(function(f){a.operation(function(){n(a,f)})}):a.operation(function(){n(a,b)}))}}function n(a,c){v(a);for(var d=a.state.lint,e=d.options,b=D(c),f=0;f<
b.length;++f){var h=b[f];if(h){var g=[];h=h.filter(function(w){return-1<g.indexOf(w.message)?!1:g.push(w.message)});for(var q=null,x=d.hasGutter&&document.createDocumentFragment(),r=0;r<h.length;++r){var l=h[r],m=l.severity;m||(m="error");"error"!=q&&(q=m);e.formatAnnotation&&(l=e.formatAnnotation(l));d.hasGutter&&x.appendChild(u(l));l.to&&d.marked.push(a.markText(l.from,l.to,{className:"CodeMirror-lint-mark CodeMirror-lint-mark-"+m,__annotation:l}))}d.hasGutter&&a.setGutterMarker(f,"CodeMirror-lint-markers",
C(a,x,q,1<b[f].length,d.options.tooltips))}}if(e.onUpdateLinting)e.onUpdateLinting(c,b,a)}function y(a){var c=a.state.lint;c&&(clearTimeout(c.timeout),c.timeout=setTimeout(function(){p(a)},c.options.delay||500))}k.defineOption("lint",!1,function(a,c,d){d&&d!=k.Init&&(v(a),!1!==a.state.lint.options.lintOnChange&&a.off("change",y),k.off(a.getWrapperElement(),"mouseover",a.state.lint.onMouseOver),clearTimeout(a.state.lint.timeout),delete a.state.lint);if(c){var e=a.getOption("gutters");d=!1;for(var b=
0;b<e.length;++b)"CodeMirror-lint-markers"==e[b]&&(d=!0);e=a.state;c instanceof Function?c={getAnnotations:c}:c&&!0!==c||(c={});d=e.lint=new B(a,c,d);if(!1!==d.options.lintOnChange)a.on("change",y);if(0!=d.options.tooltips&&"gutter"!=d.options.tooltips)k.on(a.getWrapperElement(),"mouseover",d.onMouseOver);p(a)}});k.defineExtension("performLint",function(){this.state.lint&&p(this)})});
