'use strict';(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],k):k(CodeMirror)})(function(k){function z(a,b,d){function e(f){if(!c.parentNode)return k.off(document,"mousemove",e);c.style.top=Math.max(0,f.clientY-c.offsetHeight-5)+"px";c.style.left=f.clientX+5+"px"}var c=document.createElement("div");c.className="CodeMirror-lint-tooltip cm-s-"+a.options.theme;c.appendChild(d.cloneNode(!0));
a.state.lint.options.selfContain?a.getWrapperElement().appendChild(c):document.body.appendChild(c);k.on(document,"mousemove",e);e(b);null!=c.style.opacity&&(c.style.opacity=1);return c}function A(a){a.parentNode&&(null==a.style.opacity&&a.parentNode&&a.parentNode.removeChild(a),a.style.opacity=0,setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},600))}function t(a,b,d,e){function c(){k.off(e,"mouseout",c);f&&(A(f),f=null)}var f=z(a,b,d),h=setInterval(function(){if(f)for(var g=e;;g=g.parentNode){g&&
11==g.nodeType&&(g=g.host);if(g==document.body)return;if(!g){c();break}}if(!f)return clearInterval(h)},400);k.on(e,"mouseout",c)}function B(a,b,d){this.marked=[];this.options=b;this.timeout=null;this.hasGutter=d;this.onMouseOver=function(e){var c=e.target||e.srcElement;if(/\bCodeMirror-lint-mark-/.test(c.className)){c=c.getBoundingClientRect();var f=a.findMarksAt(a.coordsChar({left:(c.left+c.right)/2,top:(c.top+c.bottom)/2},"client"));c=[];for(var h=0;h<f.length;++h){var g=f[h].__annotation;g&&c.push(g)}if(c.length){f=
e.target||e.srcElement;h=document.createDocumentFragment();for(g=0;g<c.length;g++)h.appendChild(u(c[g]));t(a,e,h,f)}}};this.waitingFor=0}function v(a){var b=a.state.lint;b.hasGutter&&a.clearGutter("CodeMirror-lint-markers");b.options.highlightLines&&C(a);for(a=0;a<b.marked.length;++a)b.marked[a].clear();b.marked.length=0}function C(a){a.eachLine(function(b){var d=b.wrapClass&&/\bCodeMirror-lint-line-\w+\b/.exec(b.wrapClass);d&&a.removeLineClass(b,"wrap",d[0])})}function D(a,b,d,e,c){var f=document.createElement("div"),
h=f;f.className="CodeMirror-lint-marker CodeMirror-lint-marker-"+d;e&&(h=f.appendChild(document.createElement("div")),h.className="CodeMirror-lint-marker CodeMirror-lint-marker-multiple");if(0!=c)k.on(h,"mouseover",function(g){t(a,g,b,h)});return f}function E(a){for(var b=[],d=0;d<a.length;++d){var e=a[d],c=e.from.line;(b[c]||(b[c]=[])).push(e)}return b}function u(a){var b=a.severity;b||(b="error");var d=document.createElement("div");d.className="CodeMirror-lint-message CodeMirror-lint-message-"+
b;"undefined"!=typeof a.messageHTML?d.innerHTML=a.messageHTML:d.appendChild(document.createTextNode(a.message));return d}function F(a,b,d){function e(){f=-1;a.off("change",e)}var c=a.state.lint,f=++c.waitingFor;a.on("change",e);b(a.getValue(),function(h,g){a.off("change",e);c.waitingFor==f&&(g&&h instanceof k&&(h=g),a.operation(function(){p(a,h)}))},d,a)}function q(a){var b=a.state.lint;if(b){b=b.options;var d=b.options||b,e=b.getAnnotations||a.getHelper(k.Pos(0,0),"lint");if(e)if(b.async||e.async)F(a,
e,d);else{var c=e(a.getValue(),d,a);c&&(c.then?c.then(function(f){a.operation(function(){p(a,f)})}):a.operation(function(){p(a,c)}))}}}function p(a,b){var d=a.state.lint;if(d){var e=d.options;v(a);for(var c=E(b),f=0;f<c.length;++f){var h=c[f];if(h){var g=[];h=h.filter(function(w){return-1<g.indexOf(w.message)?!1:g.push(w.message)});for(var m=null,x=d.hasGutter&&document.createDocumentFragment(),r=0;r<h.length;++r){var l=h[r],n=l.severity;n||(n="error");"error"!=m&&(m=n);e.formatAnnotation&&(l=e.formatAnnotation(l));
d.hasGutter&&x.appendChild(u(l));l.to&&d.marked.push(a.markText(l.from,l.to,{className:"CodeMirror-lint-mark CodeMirror-lint-mark-"+n,__annotation:l}))}d.hasGutter&&a.setGutterMarker(f,"CodeMirror-lint-markers",D(a,x,m,1<c[f].length,d.options.tooltips));d.options.highlightLines&&a.addLineClass(f,"wrap","CodeMirror-lint-line-"+m)}}if(e.onUpdateLinting)e.onUpdateLinting(b,c,a)}}function y(a){var b=a.state.lint;b&&(clearTimeout(b.timeout),b.timeout=setTimeout(function(){q(a)},b.options.delay||500))}
k.defineOption("lint",!1,function(a,b,d){d&&d!=k.Init&&(v(a),!1!==a.state.lint.options.lintOnChange&&a.off("change",y),k.off(a.getWrapperElement(),"mouseover",a.state.lint.onMouseOver),clearTimeout(a.state.lint.timeout),delete a.state.lint);if(b){var e=a.getOption("gutters");d=!1;for(var c=0;c<e.length;++c)"CodeMirror-lint-markers"==e[c]&&(d=!0);e=a.state;b instanceof Function?b={getAnnotations:b}:b&&!0!==b||(b={});d=e.lint=new B(a,b,d);if(!1!==d.options.lintOnChange)a.on("change",y);if(0!=d.options.tooltips&&
"gutter"!=d.options.tooltips)k.on(a.getWrapperElement(),"mouseover",d.onMouseOver);q(a)}});k.defineExtension("performLint",function(){q(this)})});
