'use strict';(function(l){"object"==typeof exports&&"object"==typeof module?l(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],l):l(CodeMirror)})(function(l){function B(a,c,b){var d=a.docs[c];d?b(x(a,d)):a.options.getFile?a.options.getFile(c,b):b(null)}function v(a,c,b){for(var d in a.docs){var e=a.docs[d];if(e.doc==c)return e}if(!b)for(b=0;;++b)if(d="[doc"+(b||"")+"]",!a.docs[d]){b=d;break}return a.addDoc(b,c)}function C(a,c){if("string"==typeof c)return a.docs[c];
c instanceof l&&(c=c.getDoc());if(c instanceof l.Doc)return v(a,c)}function L(a,c,b){var d=v(a,c),e=a.cachedArgHints;e&&e.doc==c&&0<=y(e.start,b.to)&&(a.cachedArgHints=null);e=d.changed;null==e&&(d.changed=e={from:b.from.line,to:b.from.line});var f=b.from.line+(b.text.length-1);b.from.line<e.to&&(e.to-=b.to.line-f);f>=e.to&&(e.to=f+1);e.from>b.from.line&&(e.from=b.from.line);c.lineCount()>D&&100<b.to-e.from&&setTimeout(function(){d.changed&&100<d.changed.to-d.changed.from&&E(a,d)},200)}function E(a,
c){a.server.request({files:[{type:"full",name:c.name,text:x(a,c)}]},function(a){a?window.console.error(a):c.changed=null})}function M(a,c,b){a.request(c,{type:"completions",types:!0,docs:!0,urls:!0},function(d,e){if(d)return u(a,c,d);d=[];var f="",g=e.start,h=e.end;'["'==c.getRange(r(g.line,g.ch-2),g)&&'"]'!=c.getRange(h,r(h.line,h.ch+2))&&(f='"]');for(var k=0;k<e.completions.length;++k){var m=e.completions[k],t=N(m.type);e.guess&&(t+=" "+p+"guess");d.push({text:m.name+f,displayText:m.displayName||
m.name,className:t,data:m})}e={from:g,to:h,list:d};var n=null;l.on(e,"close",function(){w(n)});l.on(e,"update",function(){w(n)});l.on(e,"select",function(c,b){w(n);if(c=a.options.completionTip?a.options.completionTip(c.data):c.data.doc)n=A(b.parentNode.getBoundingClientRect().right+window.pageXOffset,b.getBoundingClientRect().top+window.pageYOffset,c),n.className+=" "+p+"hint-doc"});b(e)})}function N(a){a="?"==a?"unknown":"number"==a||"string"==a||"bool"==a?a:/^fn\(/.test(a)?"fn":/^\[/.test(a)?"array":
"object";return p+"completion "+p+"completion-"+a}function F(a,c,b,d,e){a.request(c,d,function(b,d){if(b)return u(a,c,b);if(a.options.typeTip)b=a.options.typeTip(d);else if(b=q("span",null,q("strong",null,d.type||"not found")),d.doc&&b.appendChild(document.createTextNode(" \u2014 "+d.doc)),d.url){b.appendChild(document.createTextNode(" "));var h=b.appendChild(q("a",null,"[docs]"));h.href=d.url;h.target="_blank"}G(c,b,a);e&&e()},b)}function O(a,c){z(a);if(!c.somethingSelected()){var b=c.getTokenAt(c.getCursor()).state,
b=l.innerMode(c.getMode(),b);if("javascript"==b.mode.name&&(b=b.state.lexical,"call"==b.info)){for(var d,e=b.pos||0,f=c.getOption("tabSize"),g=c.getCursor().line,h=Math.max(0,g-9),k=!1;g>=h;--g){for(var m=c.getLine(g),t=d=0;;){t=m.indexOf("\t",t);if(-1==t)break;d+=f-(t+d)%f-1;t+=1}d=b.column-d;if("("==m.charAt(d)){k=!0;break}}if(k){var n=r(g,d);if((b=a.cachedArgHints)&&b.doc==c.getDoc()&&0==y(n,b.start))return H(a,c,e);a.request(c,{type:"type",preferFunction:!0,end:n},function(b,d){!b&&d.type&&/^fn\(/.test(d.type)&&
(a.cachedArgHints={start:n,type:P(d.type),name:d.exprName||d.name||"fn",guess:d.guess,doc:c.getDoc()},H(a,c,e))})}}}}function H(a,c,b){z(a);for(var d=a.cachedArgHints,e=d.type,d=q("span",d.guess?p+"fhint-guess":null,q("span",p+"fname",d.name),"("),f=0;f<e.args.length;++f){f&&d.appendChild(document.createTextNode(", "));var g=e.args[f];d.appendChild(q("span",p+"farg"+(f==b?" "+p+"farg-current":""),g.name||"?"));"?"!=g.type&&(d.appendChild(document.createTextNode(":\u00a0")),d.appendChild(q("span",
p+"type",g.type)))}d.appendChild(document.createTextNode(e.rettype?") ->\u00a0":")"));e.rettype&&d.appendChild(q("span",p+"type",e.rettype));c=c.cursorCoords(null,"page");a.activeArgHints=A(c.right+1,c.bottom,d)}function P(a){function c(c){for(var b=0,e=d;;){var k=a.charAt(d);if(c.test(k)&&!b)return a.slice(e,d);/[{\[\(]/.test(k)?++b:/[}\]\)]/.test(k)&&--b;++d}}var b=[],d=3;if(")"!=a.charAt(d))for(;;){var e=a.slice(d).match(/^([^, \(\[\{]+): /);e&&(d+=e[0].length,e=e[1]);b.push({name:e,type:c(/[\),]/)});
if(")"==a.charAt(d))break;d+=2}e=a.slice(d).match(/^\) -> (.*)$/);return{args:b,rettype:e&&e[1]}}function Q(a,c){function b(b){b={type:"definition",variable:b||null};var e=v(a,c.getDoc());a.server.request(I(a,e,b),function(b,d){if(b)return u(a,c,b);if(!d.file&&d.url)window.open(d.url);else{if(d.file){b=a.docs[d.file];var h,k;if(k=b){var m;var l=b.doc;h=d.context.slice(0,d.contextOffset).split("\n");var n=d.start.line-(h.length-1);k=r(n,(1==h.length?d.start.ch:l.getLine(n).length)-h[0].length);for(var p=
l.getLine(n).slice(k.ch),n=n+1;n<l.lineCount()&&p.length<d.context.length;++n)p+="\n"+l.getLine(n);if(p.slice(0,d.context.length)==d.context)m=d;else{l=l.getSearchCursor(d.context,0,!1);for(p=Infinity;l.findNext();){var n=l.from(),q=1E4*Math.abs(n.line-k.line);q||(q=Math.abs(n.ch-k.ch));q<p&&(m=n,p=q)}m?(1==h.length?m.ch+=h[0].length:m=r(m.line+(h.length-1),h[h.length-1].length),d=d.start.line==d.end.line?r(m.line,m.ch+(d.end.ch-d.start.ch)):r(m.line+(d.end.line-d.start.line),d.end.ch),m={start:m,
end:d}):m=null}k=h=m}if(k){a.jumpStack.push({file:e.name,start:c.getCursor("from"),end:c.getCursor("to")});J(a,e,b,h.start,h.end);return}}u(a,c,"Could not find a definition.")}})}R(c)?b():K(c,"Jump to variable",function(a){a&&b(a)})}function J(a,c,b,d,e){b.doc.setSelection(d,e);c!=b&&a.options.switchToDoc&&(z(a),a.options.switchToDoc(b.name,b.doc))}function R(a){var c=a.getCursor("end"),b=a.getTokenAt(c);return b.start<c.ch&&"comment"==b.type?!1:/[\w)\]]/.test(a.getLine(c.line).slice(Math.max(c.ch-
1,0),c.ch+1))}function S(a,c){var b=c.getTokenAt(c.getCursor());if(!/\w/.test(b.string))return u(a,c,"Not at a variable");K(c,"New name for "+b.string,function(b){a.request(c,{type:"rename",newName:b,fullDocs:!0},function(b,d){if(b)return u(a,c,b);T(a,d.changes)})})}function U(a,c){var b=v(a,c.doc).name;a.request(c,{type:"refs"},function(d,e){if(d)return u(a,c,d);d=[];for(var f=0,g=c.getCursor(),h=0;h<e.refs.length;h++){var k=e.refs[h];k.file==b&&(d.push({anchor:k.start,head:k.end}),0<=y(g,k.start)&&
0>=y(g,k.end)&&(f=d.length-1))}c.setSelections(d,f)})}function T(a,c){for(var b=Object.create(null),d=0;d<c.length;++d){var e=c[d];(b[e.file]||(b[e.file]=[])).push(e)}for(var f in b){c=a.docs[f];var g=b[f];if(c){g.sort(function(a,b){return y(b.start,a.start)});for(var h="*rename"+ ++V,d=0;d<g.length;++d)e=g[d],c.doc.replaceRange(e.text,e.start,e.end,h)}}}function I(a,c,b,d){var e=[],f;(f=!b.fullDocs)||delete b.fullDocs;"string"==typeof b&&(b={type:b});b.lineCharPositions=!0;null==b.end&&(b.end=d||
c.doc.getCursor("end"),c.doc.somethingSelected()&&(b.start=c.doc.getCursor("start")));d=b.start||b.end;c.changed?c.doc.lineCount()>D&&!1!==f&&100>c.changed.to-c.changed.from&&c.changed.from<=d.line&&c.changed.to>b.end.line?(e.push(W(c,d,b.end)),b.file="#0",f=e[0].offsetLines,null!=b.start&&(b.start=r(b.start.line- -f,b.start.ch)),b.end=r(b.end.line-f,b.end.ch)):(e.push({type:"full",name:c.name,text:x(a,c)}),b.file=c.name,c.changed=null):b.file=c.name;for(var g in a.docs)f=a.docs[g],f.changed&&f!=
c&&(e.push({type:"full",name:f.name,text:x(a,f)}),f.changed=null);return{query:b,files:e}}function W(a,c,b){for(var d=a.doc,e=null,f=null,g=c.line-1,h=Math.max(0,g-50);g>=h;--g){var k=d.getLine(g);0>k.search(/\bfunction\b/)||(k=l.countColumn(k,null,4),null!=e&&e<=k||(e=k,f=g))}null==f&&(f=h);g=Math.min(d.lastLine(),b.line+20);if(null==e||e==l.countColumn(d.getLine(c.line),null,4))c=g;else for(c=b.line+1;c<g&&!(k=l.countColumn(d.getLine(c),null,4),k<=e);++c);e=r(f,0);return{type:"part",name:a.name,
offsetLines:e.line,text:d.getRange(e,r(c,0))}}function q(a,c){var b=document.createElement(a);c&&(b.className=c);for(var d=2;d<arguments.length;++d){var e=arguments[d];"string"==typeof e&&(e=document.createTextNode(e));b.appendChild(e)}return b}function K(a,c,b){a.openDialog?a.openDialog(c+": <input type=text>",b):b(prompt(c,""))}function G(a,c,b){function d(){a.state.ternTooltip=null;f.parentNode&&(a.off("cursorActivity",d),a.off("blur",d),a.off("scroll",d),X(f))}a.state.ternTooltip&&w(a.state.ternTooltip);
var e=a.cursorCoords(),f=a.state.ternTooltip=A(e.right+1,e.bottom,c),g=!1,h=!1;l.on(f,"mousemove",function(){g=!0});l.on(f,"mouseout",function(a){l.contains(f,a.relatedTarget||a.toElement)||(h?d():g=!1)});setTimeout(function(){h=!0;g||d()},b.options.hintDelay?b.options.hintDelay:1700);a.on("cursorActivity",d);a.on("blur",d);a.on("scroll",d)}function A(a,c,b){b=q("div",p+"tooltip",b);b.style.left=a+"px";b.style.top=c+"px";document.body.appendChild(b);return b}function w(a){var c=a&&a.parentNode;c&&
c.removeChild(a)}function X(a){a.style.opacity="0";setTimeout(function(){w(a)},1100)}function u(a,c,b){a.options.showError?a.options.showError(c,b):G(c,String(b),a)}function z(a){a.activeArgHints&&(w(a.activeArgHints),a.activeArgHints=null)}function x(a,c){var b=c.doc.getValue();a.options.fileFilter&&(b=a.options.fileFilter(b,c.name,c.doc));return b}function Y(a){function c(a,c){c&&(a.id=++d,e[d]=c);b.postMessage(a)}var b=a.worker=new Worker(a.options.workerScript);b.postMessage({type:"init",defs:a.options.defs,
plugins:a.options.plugins,scripts:a.options.workerDeps});var d=0,e={};b.onmessage=function(b){var d=b.data;"getFile"==d.type?B(a,d.name,function(a,b){c({type:"getFile",err:String(a),text:b,id:d.id})}):"debug"==d.type?window.console.log(d.message):d.id&&e[d.id]&&(e[d.id](d.err,d.body),delete e[d.id])};b.onerror=function(a){for(var b in e)e[b](a);e={}};this.addFile=function(a,b){c({type:"add",name:a,text:b})};this.delFile=function(a){c({type:"del",name:a})};this.request=function(a,b){c({type:"req",
body:a},b)}}l.TernServer=function(a){var c=this;this.options=a||{};a=this.options.plugins||(this.options.plugins={});a.doc_comment||(a.doc_comment=!0);this.docs=Object.create(null);this.server=this.options.useWorker?new Y(this):new tern.Server({getFile:function(a,d){return B(c,a,d)},async:!0,defs:this.options.defs||[],plugins:a});this.trackChange=function(a,d){L(c,a,d)};this.activeArgHints=this.cachedArgHints=null;this.jumpStack=[];this.getHint=function(a,d){return M(c,a,d)};this.getHint.async=!0};
l.TernServer.prototype={addDoc:function(a,c){var b={doc:c,name:a,changed:null};this.server.addFile(a,x(this,b));l.on(c,"change",this.trackChange);return this.docs[a]=b},delDoc:function(a){if(a=C(this,a))l.off(a.doc,"change",this.trackChange),delete this.docs[a.name],this.server.delFile(a.name)},hideDoc:function(a){z(this);(a=C(this,a))&&a.changed&&E(this,a)},complete:function(a){a.showHint({hint:this.getHint})},showType:function(a,c,b){F(this,a,c,"type",b)},showDocs:function(a,c,b){F(this,a,c,"documentation",
b)},updateArgHints:function(a){O(this,a)},jumpToDef:function(a){Q(this,a)},jumpBack:function(a){var c=this.jumpStack.pop(),b=c&&this.docs[c.file];b&&J(this,v(this,a.getDoc()),b,c.start,c.end)},rename:function(a){S(this,a)},selectName:function(a){U(this,a)},request:function(a,c,b,d){var e=this,f=v(this,a.getDoc()),g=I(this,f,c,d);if(a=g.query&&this.options.queryOptions&&this.options.queryOptions[g.query.type])for(var h in a)g.query[h]=a[h];this.server.request(g,function(a,d){!a&&e.options.responseFilter&&
(d=e.options.responseFilter(f,c,g,a,d));b(a,d)})},destroy:function(){z(this);this.worker&&(this.worker.terminate(),this.worker=null)}};var r=l.Pos,p="CodeMirror-Tern-",D=250,V=0,y=l.cmpPos});
