'use strict';(function(f){"object"==typeof exports&&"object"==typeof module?f(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],f):f(CodeMirror)})(function(f){function C(a,d,b){var c=a.docs[d];c?b(y(a,c)):a.options.getFile?a.options.getFile(d,b):b(null)}function w(a,d,b){for(var c in a.docs){var e=a.docs[c];if(e.doc==d)return e}if(!b)for(b=0;;++b)if(c="[doc"+(b||"")+"]",!a.docs[c]){b=c;break}return a.addDoc(b,d)}function D(a,d){if("string"==typeof d)return a.docs[d];
d instanceof f&&(d=d.getDoc());if(d instanceof f.Doc)return w(a,d)}function M(a,d,b){var c=w(a,d),e=a.cachedArgHints;e&&e.doc==d&&0>=z(e.start,b.to)&&(a.cachedArgHints=null);e=c.changed;null==e&&(c.changed=e={from:b.from.line,to:b.from.line});var g=b.from.line+(b.text.length-1);b.from.line<e.to&&(e.to-=b.to.line-g);g>=e.to&&(e.to=g+1);e.from>b.from.line&&(e.from=b.from.line);d.lineCount()>E&&100<b.to-e.from&&setTimeout(function(){c.changed&&100<c.changed.to-c.changed.from&&F(a,c)},200)}function F(a,
d){a.server.request({files:[{type:"full",name:d.name,text:y(a,d)}]},function(a){a?window.console.error(a):d.changed=null})}function N(a,d,b){a.request(d,{type:"completions",types:!0,docs:!0,urls:!0},function(c,e){if(c)return u(a,d,c);var g=[],k="",l=e.start,h=e.end;'["'==d.getRange(t(l.line,l.ch-2),l)&&'"]'!=d.getRange(h,t(h.line,h.ch+2))&&(k='"]');for(var q=0;q<e.completions.length;++q){var m=e.completions[q],v=O(m.type);e.guess&&(v+=" "+n+"guess");g.push({text:m.name+k,displayText:m.displayName||
m.name,className:v,data:m})}var g={from:l,to:h,list:g},p=null;f.on(g,"close",function(){x(p)});f.on(g,"update",function(){x(p)});f.on(g,"select",function(d,b){x(p);var c=a.options.completionTip?a.options.completionTip(d.data):d.data.doc;c&&(p=B(b.parentNode.getBoundingClientRect().right+window.pageXOffset,b.getBoundingClientRect().top+window.pageYOffset,c),p.className+=" "+n+"hint-doc")});b(g)})}function O(a){a="?"==a?"unknown":"number"==a||"string"==a||"bool"==a?a:/^fn\(/.test(a)?"fn":/^\[/.test(a)?
"array":"object";return n+"completion "+n+"completion-"+a}function G(a,d,b,c,e){a.request(d,c,function(b,c){if(b)return u(a,d,b);if(a.options.typeTip)var l=a.options.typeTip(c);else if(l=r("span",null,r("strong",null,c.type||"not found")),c.doc&&l.appendChild(document.createTextNode(" \u2014 "+c.doc)),c.url){l.appendChild(document.createTextNode(" "));var h=l.appendChild(r("a",null,"[docs]"));h.href=c.url;h.target="_blank"}H(d,l,a);e&&e()},b)}function P(a,d){A(a);if(!d.somethingSelected()){var b=
d.getTokenAt(d.getCursor()).state,b=f.innerMode(d.getMode(),b);if("javascript"==b.mode.name&&(b=b.state.lexical,"call"==b.info)){for(var c,e=b.pos||0,g=d.getOption("tabSize"),k=d.getCursor().line,l=Math.max(0,k-9),h=!1;k>=l;--k){for(var q=d.getLine(k),m=c=0;;){var v=q.indexOf("\t",m);if(-1==v)break;c+=g-(v+c)%g-1;m=v+1}c=b.column-c;if("("==q.charAt(c)){h=!0;break}}if(h){b=t(k,c);if((c=a.cachedArgHints)&&c.doc==d.getDoc()&&0==z(b,c.start))return I(a,d,e);a.request(d,{type:"type",preferFunction:!0,
end:b},function(b,c){!b&&c.type&&/^fn\(/.test(c.type)&&(a.cachedArgHints={start:m,type:Q(c.type),name:c.exprName||c.name||"fn",guess:c.guess,doc:d.getDoc()},I(a,d,e))})}}}}function I(a,d,b){A(a);for(var c=a.cachedArgHints,e=c.type,c=r("span",c.guess?n+"fhint-guess":null,r("span",n+"fname",c.name),"("),g=0;g<e.args.length;++g){g&&c.appendChild(document.createTextNode(", "));var k=e.args[g];c.appendChild(r("span",n+"farg"+(g==b?" "+n+"farg-current":""),k.name||"?"));"?"!=k.type&&(c.appendChild(document.createTextNode(":\u00a0")),
c.appendChild(r("span",n+"type",k.type)))}c.appendChild(document.createTextNode(e.rettype?") ->\u00a0":")"));e.rettype&&c.appendChild(r("span",n+"type",e.rettype));d=d.cursorCoords(null,"page");a.activeArgHints=B(d.right+1,d.bottom,c)}function Q(a){function d(d){for(var b=0,e=c;;){var h=a.charAt(c);if(d.test(h)&&!b)return a.slice(e,c);/[{\[\(]/.test(h)?++b:/[}\]\)]/.test(h)&&--b;++c}}var b=[],c=3;if(")"!=a.charAt(c))for(;;){var e=a.slice(c).match(/^([^, \(\[\{]+): /);e&&(c+=e[0].length,e=e[1]);b.push({name:e,
type:d(/[\),]/)});if(")"==a.charAt(c))break;c+=2}e=a.slice(c).match(/^\) -> (.*)$/);return{args:b,rettype:e&&e[1]}}function R(a,d){function b(b){b={type:"definition",variable:b||null};var e=w(a,d.getDoc());a.server.request(J(a,e,b),function(b,c){if(b)return u(a,d,b);if(!c.file&&c.url)window.open(c.url);else{if(c.file){var l=a.docs[c.file],h,q;if(q=l){var m;var f=l.doc;h=c.context.slice(0,c.contextOffset).split("\n");var p=c.start.line-(h.length-1);q=t(p,(1==h.length?c.start.ch:f.getLine(p).length)-
h[0].length);for(var n=f.getLine(p).slice(q.ch),p=p+1;p<f.lineCount()&&n.length<c.context.length;++p)n+="\n"+f.getLine(p);if(n.slice(0,c.context.length)==c.context)m=c;else{f=f.getSearchCursor(c.context,0,!1);for(n=Infinity;f.findNext();){var p=f.from(),r=1E4*Math.abs(p.line-q.line);r||(r=Math.abs(p.ch-q.ch));r<n&&(m=p,n=r)}m?(1==h.length?m.ch+=h[0].length:m=t(m.line+(h.length-1),h[h.length-1].length),h=c.start.line==c.end.line?t(m.line,m.ch+(c.end.ch-c.start.ch)):t(m.line+(c.end.line-c.start.line),
c.end.ch),m={start:m,end:h}):m=null}q=h=m}if(q){a.jumpStack.push({file:e.name,start:d.getCursor("from"),end:d.getCursor("to")});K(a,e,l,h.start,h.end);return}}u(a,d,"Could not find a definition.")}})}S(d)?b():L(d,"Jump to variable",function(a){a&&b(a)})}function K(a,d,b,c,e){b.doc.setSelection(c,e);d!=b&&a.options.switchToDoc&&(A(a),a.options.switchToDoc(b.name,b.doc))}function S(a){var d=a.getCursor("end"),b=a.getTokenAt(d);return b.start<d.ch&&"comment"==b.type?!1:/[\w)\]]/.test(a.getLine(d.line).slice(Math.max(d.ch-
1,0),d.ch+1))}function T(a,d){var b=d.getTokenAt(d.getCursor());if(!/\w/.test(b.string))return u(a,d,"Not at a variable");L(d,"New name for "+b.string,function(b){a.request(d,{type:"rename",newName:b,fullDocs:!0},function(b,c){if(b)return u(a,d,b);U(a,c.changes)})})}function V(a,d){var b=w(a,d.doc).name;a.request(d,{type:"refs"},function(c,e){if(c)return u(a,d,c);for(var g=[],k=0,l=d.getCursor(),h=0;h<e.refs.length;h++){var f=e.refs[h];f.file==b&&(g.push({anchor:f.start,head:f.end}),0<=z(l,f.start)&&
0>=z(l,f.end)&&(k=g.length-1))}d.setSelections(g,k)})}function U(a,d){for(var b=Object.create(null),c=0;c<d.length;++c){var e=d[c];(b[e.file]||(b[e.file]=[])).push(e)}for(var g in b){var k=a.docs[g],f=b[g];if(k){f.sort(function(a,b){return z(b.start,a.start)});for(var h="*rename"+ ++W,c=0;c<f.length;++c)e=f[c],k.doc.replaceRange(e.text,e.start,e.end,h)}}}function J(a,d,b,c){var e=[],g=0;(g=!b.fullDocs)||delete b.fullDocs;"string"==typeof b&&(b={type:b});b.lineCharPositions=!0;null==b.end&&(b.end=
c||d.doc.getCursor("end"),d.doc.somethingSelected()&&(b.start=d.doc.getCursor("start")));c=b.start||b.end;d.changed?d.doc.lineCount()>E&&!1!==g&&100>d.changed.to-d.changed.from&&d.changed.from<=c.line&&d.changed.to>b.end.line?(e.push(X(d,c,b.end)),b.file="#0",g=e[0].offsetLines,null!=b.start&&(b.start=t(b.start.line- -g,b.start.ch)),b.end=t(b.end.line-g,b.end.ch)):(e.push({type:"full",name:d.name,text:y(a,d)}),b.file=d.name,d.changed=null):b.file=d.name;for(var k in a.docs)c=a.docs[k],c.changed&&
c!=d&&(e.push({type:"full",name:c.name,text:y(a,c)}),c.changed=null);return{query:b,files:e}}function X(a,d,b){for(var c=a.doc,e=null,g=null,k=d.line-1,l=Math.max(0,k-50);k>=l;--k){var h=c.getLine(k);0>h.search(/\bfunction\b/)||(h=f.countColumn(h,null,4),null!=e&&e<=h||(e=h,g=k))}null==g&&(g=l);k=Math.min(c.lastLine(),b.line+20);if(null==e||e==f.countColumn(c.getLine(d.line),null,4))d=k;else for(d=b.line+1;d<k&&!(h=f.countColumn(c.getLine(d),null,4),h<=e);++d);e=t(g,0);return{type:"part",name:a.name,
offsetLines:e.line,text:c.getRange(e,t(d,0))}}function r(a,d){var b=document.createElement(a);d&&(b.className=d);for(var c=2;c<arguments.length;++c){var e=arguments[c];"string"==typeof e&&(e=document.createTextNode(e));b.appendChild(e)}return b}function L(a,d,b){a.openDialog?a.openDialog(d+": <input type=text>",b):b(prompt(d,""))}function H(a,d,b){function c(){a.state.ternTooltip=null;g.parentNode&&(a.off("cursorActivity",c),a.off("blur",c),a.off("scroll",c),Y(g))}a.state.ternTooltip&&x(a.state.ternTooltip);
var e=a.cursorCoords(),g=a.state.ternTooltip=B(e.right+1,e.bottom,d),k=!1,l=!1;f.on(g,"mousemove",function(){k=!0});f.on(g,"mouseout",function(a){f.contains(g,a.relatedTarget||a.toElement)||(l?c():k=!1)});setTimeout(function(){l=!0;k||c()},b.options.hintDelay?b.options.hintDelay:1700);a.on("cursorActivity",c);a.on("blur",c);a.on("scroll",c)}function B(a,d,b){b=r("div",n+"tooltip",b);b.style.left=a+"px";b.style.top=d+"px";document.body.appendChild(b);return b}function x(a){var d=a&&a.parentNode;d&&
d.removeChild(a)}function Y(a){a.style.opacity="0";setTimeout(function(){x(a)},1100)}function u(a,d,b){a.options.showError?a.options.showError(d,b):H(d,String(b),a)}function A(a){a.activeArgHints&&(x(a.activeArgHints),a.activeArgHints=null)}function y(a,d){var b=d.doc.getValue();a.options.fileFilter&&(b=a.options.fileFilter(b,d.name,d.doc));return b}function Z(a){function d(a,d){d&&(a.id=++c,e[c]=d);b.postMessage(a)}var b=a.worker=new Worker(a.options.workerScript);b.postMessage({type:"init",defs:a.options.defs,
plugins:a.options.plugins,scripts:a.options.workerDeps});var c=0,e={};b.onmessage=function(b){var c=b.data;"getFile"==c.type?C(a,c.name,function(a,b){d({type:"getFile",err:String(a),text:b,id:c.id})}):"debug"==c.type?window.console.log(c.message):c.id&&e[c.id]&&(e[c.id](c.err,c.body),delete e[c.id])};b.onerror=function(a){for(var b in e)e[b](a);e={}};this.addFile=function(a,b){d({type:"add",name:a,text:b})};this.delFile=function(a){d({type:"del",name:a})};this.request=function(a,b){d({type:"req",
body:a},b)}}f.TernServer=function(a){var d=this;this.options=a||{};a=this.options.plugins||(this.options.plugins={});a.doc_comment||(a.doc_comment=!0);this.docs=Object.create(null);this.server=this.options.useWorker?new Z(this):new tern.Server({getFile:function(a,c){return C(d,a,c)},async:!0,defs:this.options.defs||[],plugins:a});this.trackChange=function(a,c){M(d,a,c)};this.activeArgHints=this.cachedArgHints=null;this.jumpStack=[];this.getHint=function(a,c){return N(d,a,c)};this.getHint.async=!0};
f.TernServer.prototype={addDoc:function(a,d){var b={doc:d,name:a,changed:null};this.server.addFile(a,y(this,b));f.on(d,"change",this.trackChange);return this.docs[a]=b},delDoc:function(a){if(a=D(this,a))f.off(a.doc,"change",this.trackChange),delete this.docs[a.name],this.server.delFile(a.name)},hideDoc:function(a){A(this);(a=D(this,a))&&a.changed&&F(this,a)},complete:function(a){a.showHint({hint:this.getHint})},showType:function(a,d,b){G(this,a,d,"type",b)},showDocs:function(a,d,b){G(this,a,d,"documentation",
b)},updateArgHints:function(a){P(this,a)},jumpToDef:function(a){R(this,a)},jumpBack:function(a){var d=this.jumpStack.pop(),b=d&&this.docs[d.file];b&&K(this,w(this,a.getDoc()),b,d.start,d.end)},rename:function(a){T(this,a)},selectName:function(a){V(this,a)},request:function(a,d,b,c){var e=this,g=w(this,a.getDoc()),f=J(this,g,d,c);if(a=f.query&&this.options.queryOptions&&this.options.queryOptions[f.query.type])for(var l in a)f.query[l]=a[l];this.server.request(f,function(a,c){!a&&e.options.responseFilter&&
(c=e.options.responseFilter(g,d,f,a,c));b(a,c)})},destroy:function(){A(this);this.worker&&(this.worker.terminate(),this.worker=null)}};var t=f.Pos,n="CodeMirror-Tern-",E=250,W=0,z=f.cmpPos});
